pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 6'
  inputs:
    version: '6.x'

- task: UseDotNet@2
  displayName: 'Install .NET 7'
  inputs:
    version: '7.x'

- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    version: '8.x'

- script: dotnet workload restore
  displayName: 'Restore .NET Workloads'

- script: dotnet workload restore --runtime win-x64
  displayName: 'Restore .NET Workloads (win-x64)'

- task: DotNetCoreCLI@2
  displayName: 'Restore referenced NuGet packages'
  inputs:
    command: 'restore'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet restore --runtime win-x64
  displayName: 'Restore referenced NuGet packages (win-x64)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage" --settings .runsettings'
    publishTestResults: true

- task: CopyFiles@2
  displayName: 'Copy artifacts to staging'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      **/$(buildConfiguration)/**/?(*.nupkg)
      **/$(buildConfiguration)/**/?(*.snupkg)
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
    
- task: PublishPipelineArtifact@1
  displayName: 'Publish artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop