// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Animation.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimationEventHandler : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_type", IsRequired = true)]
        public uint EventType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_id", IsRequired = true)]
        public uint EventId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"tag", IsRequired = true)]
        public ulong Tag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimationRequestBlock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"arb_data", IsRequired = true)]
        public byte[] ArbData { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_handlers")]
        public global::System.Collections.Generic.List<AnimationEventHandler> EventHandlers { get; } = new global::System.Collections.Generic.List<AnimationEventHandler>();

        [global::ProtoBuf.ProtoMember(3, Name = @"objects_to_reset")]
        public global::System.Collections.Generic.List<ManagerObjectId> ObjectsToResets { get; } = new global::System.Collections.Generic.List<ManagerObjectId>();

        [global::ProtoBuf.ProtoMember(4, Name = @"is_interruptible")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsInterruptible
        {
            get => __pbn__IsInterruptible ?? false;
            set => __pbn__IsInterruptible = value;
        }
        public bool ShouldSerializeIsInterruptible() => __pbn__IsInterruptible != null;
        public void ResetIsInterruptible() => __pbn__IsInterruptible = null;
        private bool? __pbn__IsInterruptible;

        [global::ProtoBuf.ProtoMember(5, Name = @"should_analyze")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool ShouldAnalyze
        {
            get => __pbn__ShouldAnalyze ?? false;
            set => __pbn__ShouldAnalyze = value;
        }
        public bool ShouldSerializeShouldAnalyze() => __pbn__ShouldAnalyze != null;
        public void ResetShouldAnalyze() => __pbn__ShouldAnalyze = null;
        private bool? __pbn__ShouldAnalyze;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimationStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"asm")]
        public ResourceKey Asm { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"state_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StateName
        {
            get => __pbn__StateName ?? "";
            set => __pbn__StateName = value;
        }
        public bool ShouldSerializeStateName() => __pbn__StateName != null;
        public void ResetStateName() => __pbn__StateName = null;
        private string __pbn__StateName;

        [global::ProtoBuf.ProtoMember(3, Name = @"actor_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActorName
        {
            get => __pbn__ActorName ?? "";
            set => __pbn__ActorName = value;
        }
        public bool ShouldSerializeActorName() => __pbn__ActorName != null;
        public void ResetActorName() => __pbn__ActorName = null;
        private string __pbn__ActorName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CurveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"input_value", IsRequired = true)]
        public float InputValue { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"output_value", IsRequired = true)]
        public float OutputValue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FocusEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public EventType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"layer")]
        public uint Layer
        {
            get => __pbn__Layer.GetValueOrDefault();
            set => __pbn__Layer = value;
        }
        public bool ShouldSerializeLayer() => __pbn__Layer != null;
        public void ResetLayer() => __pbn__Layer = null;
        private uint? __pbn__Layer;

        [global::ProtoBuf.ProtoMember(4, Name = @"flags")]
        public uint Flags
        {
            get => __pbn__Flags.GetValueOrDefault();
            set => __pbn__Flags = value;
        }
        public bool ShouldSerializeFlags() => __pbn__Flags != null;
        public void ResetFlags() => __pbn__Flags = null;
        private uint? __pbn__Flags;

        [global::ProtoBuf.ProtoMember(5, Name = @"score")]
        public float Score
        {
            get => __pbn__Score.GetValueOrDefault();
            set => __pbn__Score = value;
        }
        public bool ShouldSerializeScore() => __pbn__Score != null;
        public void ResetScore() => __pbn__Score = null;
        private float? __pbn__Score;

        [global::ProtoBuf.ProtoMember(6, Name = @"joint_name_hash")]
        public uint JointNameHash
        {
            get => __pbn__JointNameHash.GetValueOrDefault();
            set => __pbn__JointNameHash = value;
        }
        public bool ShouldSerializeJointNameHash() => __pbn__JointNameHash != null;
        public void ResetJointNameHash() => __pbn__JointNameHash = null;
        private uint? __pbn__JointNameHash;

        [global::ProtoBuf.ProtoMember(7, Name = @"target_id")]
        public ulong TargetId
        {
            get => __pbn__TargetId.GetValueOrDefault();
            set => __pbn__TargetId = value;
        }
        public bool ShouldSerializeTargetId() => __pbn__TargetId != null;
        public void ResetTargetId() => __pbn__TargetId = null;
        private ulong? __pbn__TargetId;

        [global::ProtoBuf.ProtoMember(8, Name = @"offset")]
        public Vector3 Offset { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"distance_curve")]
        public global::System.Collections.Generic.List<CurveData> DistanceCurves { get; } = new global::System.Collections.Generic.List<CurveData>();

        [global::ProtoBuf.ProtoMember(10, Name = @"facing_curve")]
        public global::System.Collections.Generic.List<CurveData> FacingCurves { get; } = new global::System.Collections.Generic.List<CurveData>();

        [global::ProtoBuf.ProtoMember(11, Name = @"source_id")]
        public ulong SourceId
        {
            get => __pbn__SourceId.GetValueOrDefault();
            set => __pbn__SourceId = value;
        }
        public bool ShouldSerializeSourceId() => __pbn__SourceId != null;
        public void ResetSourceId() => __pbn__SourceId = null;
        private ulong? __pbn__SourceId;

        [global::ProtoBuf.ProtoContract()]
        public enum EventType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_ADD")]
            FocusAdd = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_DELETE")]
            FocusDelete = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_CLEAR")]
            FocusClear = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_MODIFY_SCORE")]
            FocusModifyScore = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_DISABLE")]
            FocusDisable = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_FORCE_UPDATE")]
            FocusForceUpdate = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"FOCUS_PRINT")]
            FocusPrint = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConfigureAwarenessActor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"channels_to_remove")]
        public global::System.Collections.Generic.List<AwarenessChannelName> ChannelsToRemoves { get; } = new global::System.Collections.Generic.List<AwarenessChannelName>();

        [global::ProtoBuf.ProtoMember(4, Name = @"channels_to_configure")]
        public global::System.Collections.Generic.List<ChannelOptions> ChannelsToConfigures { get; } = new global::System.Collections.Generic.List<ChannelOptions>();

        [global::ProtoBuf.ProtoMember(5, Name = @"proximity_inner_radius")]
        public float ProximityInnerRadius
        {
            get => __pbn__ProximityInnerRadius.GetValueOrDefault();
            set => __pbn__ProximityInnerRadius = value;
        }
        public bool ShouldSerializeProximityInnerRadius() => __pbn__ProximityInnerRadius != null;
        public void ResetProximityInnerRadius() => __pbn__ProximityInnerRadius = null;
        private float? __pbn__ProximityInnerRadius;

        [global::ProtoBuf.ProtoMember(6, Name = @"proximity_outer_radius")]
        public float ProximityOuterRadius
        {
            get => __pbn__ProximityOuterRadius.GetValueOrDefault();
            set => __pbn__ProximityOuterRadius = value;
        }
        public bool ShouldSerializeProximityOuterRadius() => __pbn__ProximityOuterRadius != null;
        public void ResetProximityOuterRadius() => __pbn__ProximityOuterRadius = null;
        private float? __pbn__ProximityOuterRadius;

        [global::ProtoBuf.ProtoContract()]
        public partial class ChannelOptions : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public AwarenessChannelName Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"eval_mode")]
            [global::System.ComponentModel.DefaultValue(ConfigureAwarenessActor.ChannelEvaluationMode.AwarenessChannelEvalmodePeak)]
            public ConfigureAwarenessActor.ChannelEvaluationMode EvalMode
            {
                get => __pbn__EvalMode ?? ConfigureAwarenessActor.ChannelEvaluationMode.AwarenessChannelEvalmodePeak;
                set => __pbn__EvalMode = value;
            }
            public bool ShouldSerializeEvalMode() => __pbn__EvalMode != null;
            public void ResetEvalMode() => __pbn__EvalMode = null;
            private ConfigureAwarenessActor.ChannelEvaluationMode? __pbn__EvalMode;

            [global::ProtoBuf.ProtoMember(3, Name = @"gate")]
            public float Gate
            {
                get => __pbn__Gate.GetValueOrDefault();
                set => __pbn__Gate = value;
            }
            public bool ShouldSerializeGate() => __pbn__Gate != null;
            public void ResetGate() => __pbn__Gate = null;
            private float? __pbn__Gate;

            [global::ProtoBuf.ProtoMember(4, Name = @"gain")]
            public float Gain
            {
                get => __pbn__Gain.GetValueOrDefault();
                set => __pbn__Gain = value;
            }
            public bool ShouldSerializeGain() => __pbn__Gain != null;
            public void ResetGain() => __pbn__Gain = null;
            private float? __pbn__Gain;

            [global::ProtoBuf.ProtoMember(5, Name = @"limit")]
            public float Limit
            {
                get => __pbn__Limit.GetValueOrDefault();
                set => __pbn__Limit = value;
            }
            public bool ShouldSerializeLimit() => __pbn__Limit != null;
            public void ResetLimit() => __pbn__Limit = null;
            private float? __pbn__Limit;

            [global::ProtoBuf.ProtoMember(6, Name = @"trigger_threshold_delta")]
            public float TriggerThresholdDelta
            {
                get => __pbn__TriggerThresholdDelta.GetValueOrDefault();
                set => __pbn__TriggerThresholdDelta = value;
            }
            public bool ShouldSerializeTriggerThresholdDelta() => __pbn__TriggerThresholdDelta != null;
            public void ResetTriggerThresholdDelta() => __pbn__TriggerThresholdDelta = null;
            private float? __pbn__TriggerThresholdDelta;

            [global::ProtoBuf.ProtoMember(7, Name = @"type_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TypeName
            {
                get => __pbn__TypeName ?? "";
                set => __pbn__TypeName = value;
            }
            public bool ShouldSerializeTypeName() => __pbn__TypeName != null;
            public void ResetTypeName() => __pbn__TypeName = null;
            private string __pbn__TypeName;

            [global::ProtoBuf.ProtoMember(8, Name = @"hold_time")]
            [global::System.ComponentModel.DefaultValue(1.5f)]
            public float HoldTime
            {
                get => __pbn__HoldTime ?? 1.5f;
                set => __pbn__HoldTime = value;
            }
            public bool ShouldSerializeHoldTime() => __pbn__HoldTime != null;
            public void ResetHoldTime() => __pbn__HoldTime = null;
            private float? __pbn__HoldTime;

            [global::ProtoBuf.ProtoMember(9, Name = @"cool_down_time")]
            [global::System.ComponentModel.DefaultValue(1.5f)]
            public float CoolDownTime
            {
                get => __pbn__CoolDownTime ?? 1.5f;
                set => __pbn__CoolDownTime = value;
            }
            public bool ShouldSerializeCoolDownTime() => __pbn__CoolDownTime != null;
            public void ResetCoolDownTime() => __pbn__CoolDownTime = null;
            private float? __pbn__CoolDownTime;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ChannelEvaluationMode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_EVALMODE_PEAK")]
            AwarenessChannelEvalmodePeak = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_EVALMODE_AVERAGE")]
            AwarenessChannelEvalmodeAverage = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_EVALMODE_SUM")]
            AwarenessChannelEvalmodeSum = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_EVALMODE_SUM_SPLITSIGN")]
            AwarenessChannelEvalmodeSumSplitsign = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_EVALMODE_AVERAGE_SPLITSIGN")]
            AwarenessChannelEvalmodeAverageSplitsign = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConfigureAwarenessSourceObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"gameplay_channel_values")]
        public global::System.Collections.Generic.List<GameplayChannelValue> GameplayChannelValues { get; } = new global::System.Collections.Generic.List<GameplayChannelValue>();

        [global::ProtoBuf.ProtoMember(4, Name = @"audio_volume_multiplier")]
        public float AudioVolumeMultiplier
        {
            get => __pbn__AudioVolumeMultiplier.GetValueOrDefault();
            set => __pbn__AudioVolumeMultiplier = value;
        }
        public bool ShouldSerializeAudioVolumeMultiplier() => __pbn__AudioVolumeMultiplier != null;
        public void ResetAudioVolumeMultiplier() => __pbn__AudioVolumeMultiplier = null;
        private float? __pbn__AudioVolumeMultiplier;

        [global::ProtoBuf.ProtoMember(5, Name = @"audio_full_volume_radius")]
        public float AudioFullVolumeRadius
        {
            get => __pbn__AudioFullVolumeRadius.GetValueOrDefault();
            set => __pbn__AudioFullVolumeRadius = value;
        }
        public bool ShouldSerializeAudioFullVolumeRadius() => __pbn__AudioFullVolumeRadius != null;
        public void ResetAudioFullVolumeRadius() => __pbn__AudioFullVolumeRadius = null;
        private float? __pbn__AudioFullVolumeRadius;

        [global::ProtoBuf.ProtoMember(6, Name = @"audio_falloff_radius")]
        public float AudioFalloffRadius
        {
            get => __pbn__AudioFalloffRadius.GetValueOrDefault();
            set => __pbn__AudioFalloffRadius = value;
        }
        public bool ShouldSerializeAudioFalloffRadius() => __pbn__AudioFalloffRadius != null;
        public void ResetAudioFalloffRadius() => __pbn__AudioFalloffRadius = null;
        private float? __pbn__AudioFalloffRadius;

        [global::ProtoBuf.ProtoContract()]
        public partial class GameplayChannelValue : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public AwarenessChannelName Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
            public float Value { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProceduralControl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"control_id")]
        public uint ControlId
        {
            get => __pbn__ControlId.GetValueOrDefault();
            set => __pbn__ControlId = value;
        }
        public bool ShouldSerializeControlId() => __pbn__ControlId != null;
        public void ResetControlId() => __pbn__ControlId = null;
        private uint? __pbn__ControlId;

        [global::ProtoBuf.ProtoMember(2, Name = @"control_type")]
        [global::System.ComponentModel.DefaultValue(ProceduralControlType.Unknown)]
        public ProceduralControlType ControlType
        {
            get => __pbn__ControlType ?? ProceduralControlType.Unknown;
            set => __pbn__ControlType = value;
        }
        public bool ShouldSerializeControlType() => __pbn__ControlType != null;
        public void ResetControlType() => __pbn__ControlType = null;
        private ProceduralControlType? __pbn__ControlType;

        [global::ProtoBuf.ProtoMember(3, Name = @"joint_name_hash")]
        public uint JointNameHash
        {
            get => __pbn__JointNameHash.GetValueOrDefault();
            set => __pbn__JointNameHash = value;
        }
        public bool ShouldSerializeJointNameHash() => __pbn__JointNameHash != null;
        public void ResetJointNameHash() => __pbn__JointNameHash = null;
        private uint? __pbn__JointNameHash;

        [global::ProtoBuf.ProtoMember(4, Name = @"reference_joint_name_hash")]
        public uint ReferenceJointNameHash
        {
            get => __pbn__ReferenceJointNameHash.GetValueOrDefault();
            set => __pbn__ReferenceJointNameHash = value;
        }
        public bool ShouldSerializeReferenceJointNameHash() => __pbn__ReferenceJointNameHash != null;
        public void ResetReferenceJointNameHash() => __pbn__ReferenceJointNameHash = null;
        private uint? __pbn__ReferenceJointNameHash;

        [global::ProtoBuf.ProtoMember(5, Name = @"enable_terrain_alignment")]
        public bool EnableTerrainAlignment
        {
            get => __pbn__EnableTerrainAlignment.GetValueOrDefault();
            set => __pbn__EnableTerrainAlignment = value;
        }
        public bool ShouldSerializeEnableTerrainAlignment() => __pbn__EnableTerrainAlignment != null;
        public void ResetEnableTerrainAlignment() => __pbn__EnableTerrainAlignment = null;
        private bool? __pbn__EnableTerrainAlignment;

        [global::ProtoBuf.ProtoMember(6, Name = @"bump_sound_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BumpSoundName
        {
            get => __pbn__BumpSoundName ?? "";
            set => __pbn__BumpSoundName = value;
        }
        public bool ShouldSerializeBumpSoundName() => __pbn__BumpSoundName != null;
        public void ResetBumpSoundName() => __pbn__BumpSoundName = null;
        private string __pbn__BumpSoundName;

        [global::ProtoBuf.ProtoMember(7, Name = @"dimensions")]
        public Vector3 Dimensions { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"start_vfx")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StartVfx
        {
            get => __pbn__StartVfx ?? "";
            set => __pbn__StartVfx = value;
        }
        public bool ShouldSerializeStartVfx() => __pbn__StartVfx != null;
        public void ResetStartVfx() => __pbn__StartVfx = null;
        private string __pbn__StartVfx;

        [global::ProtoBuf.ProtoMember(9, Name = @"stop_vfx")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StopVfx
        {
            get => __pbn__StopVfx ?? "";
            set => __pbn__StopVfx = value;
        }
        public bool ShouldSerializeStopVfx() => __pbn__StopVfx != null;
        public void ResetStopVfx() => __pbn__StopVfx = null;
        private string __pbn__StopVfx;

        [global::ProtoBuf.ProtoMember(10, Name = @"start_sound")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StartSound
        {
            get => __pbn__StartSound ?? "";
            set => __pbn__StartSound = value;
        }
        public bool ShouldSerializeStartSound() => __pbn__StartSound != null;
        public void ResetStartSound() => __pbn__StartSound = null;
        private string __pbn__StartSound;

        [global::ProtoBuf.ProtoMember(11, Name = @"loop_sound")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LoopSound
        {
            get => __pbn__LoopSound ?? "";
            set => __pbn__LoopSound = value;
        }
        public bool ShouldSerializeLoopSound() => __pbn__LoopSound != null;
        public void ResetLoopSound() => __pbn__LoopSound = null;
        private string __pbn__LoopSound;

        [global::ProtoBuf.ProtoMember(12, Name = @"stop_sound")]
        [global::System.ComponentModel.DefaultValue("")]
        public string StopSound
        {
            get => __pbn__StopSound ?? "";
            set => __pbn__StopSound = value;
        }
        public bool ShouldSerializeStopSound() => __pbn__StopSound != null;
        public void ResetStopSound() => __pbn__StopSound = null;
        private string __pbn__StopSound;

        [global::ProtoBuf.ProtoMember(13, Name = @"vfx_joint_name_hash")]
        public uint VfxJointNameHash
        {
            get => __pbn__VfxJointNameHash.GetValueOrDefault();
            set => __pbn__VfxJointNameHash = value;
        }
        public bool ShouldSerializeVfxJointNameHash() => __pbn__VfxJointNameHash != null;
        public void ResetVfxJointNameHash() => __pbn__VfxJointNameHash = null;
        private uint? __pbn__VfxJointNameHash;

        [global::ProtoBuf.ProtoMember(14, Name = @"effect_speed_threshold")]
        public float EffectSpeedThreshold
        {
            get => __pbn__EffectSpeedThreshold.GetValueOrDefault();
            set => __pbn__EffectSpeedThreshold = value;
        }
        public bool ShouldSerializeEffectSpeedThreshold() => __pbn__EffectSpeedThreshold != null;
        public void ResetEffectSpeedThreshold() => __pbn__EffectSpeedThreshold = null;
        private float? __pbn__EffectSpeedThreshold;

        [global::ProtoBuf.ProtoMember(15, Name = @"jaw_flap_override")]
        public uint JawFlapOverride
        {
            get => __pbn__JawFlapOverride.GetValueOrDefault();
            set => __pbn__JawFlapOverride = value;
        }
        public bool ShouldSerializeJawFlapOverride() => __pbn__JawFlapOverride != null;
        public void ResetJawFlapOverride() => __pbn__JawFlapOverride = null;
        private uint? __pbn__JawFlapOverride;

        [global::ProtoBuf.ProtoContract()]
        public enum ProceduralControlType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"WHEEL")]
            Wheel = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SPHERE_WHEEL")]
            SphereWheel = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SKATE")]
            Skate = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"LIP_SYNC")]
            LipSync = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProceduralAnimationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"controls")]
        public global::System.Collections.Generic.List<ProceduralControl> Controls { get; } = new global::System.Collections.Generic.List<ProceduralControl>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProceduralControlRotation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"control_id")]
        public uint ControlId
        {
            get => __pbn__ControlId.GetValueOrDefault();
            set => __pbn__ControlId = value;
        }
        public bool ShouldSerializeControlId() => __pbn__ControlId != null;
        public void ResetControlId() => __pbn__ControlId = null;
        private uint? __pbn__ControlId;

        [global::ProtoBuf.ProtoMember(2, Name = @"joint_hash")]
        public uint JointHash
        {
            get => __pbn__JointHash.GetValueOrDefault();
            set => __pbn__JointHash = value;
        }
        public bool ShouldSerializeJointHash() => __pbn__JointHash != null;
        public void ResetJointHash() => __pbn__JointHash = null;
        private uint? __pbn__JointHash;

        [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float Duration
        {
            get => __pbn__Duration ?? 0f;
            set => __pbn__Duration = value;
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private float? __pbn__Duration;

        [global::ProtoBuf.ProtoMember(4, Name = @"target_id")]
        public ulong TargetId
        {
            get => __pbn__TargetId.GetValueOrDefault();
            set => __pbn__TargetId = value;
        }
        public bool ShouldSerializeTargetId() => __pbn__TargetId != null;
        public void ResetTargetId() => __pbn__TargetId = null;
        private ulong? __pbn__TargetId;

        [global::ProtoBuf.ProtoMember(5, Name = @"target_joint_hash")]
        public uint TargetJointHash
        {
            get => __pbn__TargetJointHash.GetValueOrDefault();
            set => __pbn__TargetJointHash = value;
        }
        public bool ShouldSerializeTargetJointHash() => __pbn__TargetJointHash != null;
        public void ResetTargetJointHash() => __pbn__TargetJointHash = null;
        private uint? __pbn__TargetJointHash;

        [global::ProtoBuf.ProtoMember(6, Name = @"rotation")]
        public Quaternion Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rotation_around_facing")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float RotationAroundFacing
        {
            get => __pbn__RotationAroundFacing ?? 0f;
            set => __pbn__RotationAroundFacing = value;
        }
        public bool ShouldSerializeRotationAroundFacing() => __pbn__RotationAroundFacing != null;
        public void ResetRotationAroundFacing() => __pbn__RotationAroundFacing = null;
        private float? __pbn__RotationAroundFacing;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AwarenessChannelName
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_PROXIMITY")]
        AwarenessChannelProximity = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_AUDIO_VOLUME")]
        AwarenessChannelAudioVolume = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_0")]
        AwarenessChannelGameplay0 = 1000,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_1")]
        AwarenessChannelGameplay1 = 1001,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_2")]
        AwarenessChannelGameplay2 = 1002,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_3")]
        AwarenessChannelGameplay3 = 1003,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_4")]
        AwarenessChannelGameplay4 = 1004,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_5")]
        AwarenessChannelGameplay5 = 1005,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_6")]
        AwarenessChannelGameplay6 = 1006,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_7")]
        AwarenessChannelGameplay7 = 1007,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_8")]
        AwarenessChannelGameplay8 = 1008,
        [global::ProtoBuf.ProtoEnum(Name = @"AWARENESS_CHANNEL_GAMEPLAY_9")]
        AwarenessChannelGameplay9 = 1009,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
