// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Area.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ZoneConnectedLotVersionData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint lotID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"version", IsRequired = true)]
        public ulong Version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectedNeighborhoodLot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint lotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong zoneInstanceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ZoneConnectedData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"instance_info", IsRequired = true)]
        public global::EA.Sims4.GameInstanceInfoPB InstanceInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"active_lot_id", IsRequired = true)]
        public uint ActiveLotId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"lot_versions")]
        public global::System.Collections.Generic.List<ZoneConnectedLotVersionData> LotVersions { get; } = new global::System.Collections.Generic.List<ZoneConnectedLotVersionData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"neighborhood_lots")]
        public global::System.Collections.Generic.List<ConnectedNeighborhoodLot> NeighborhoodLots { get; } = new global::System.Collections.Generic.List<ConnectedNeighborhoodLot>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"GSI_Open")]
    public partial class GSIOpen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ip", IsRequired = true)]
        public string Ip { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"port", IsRequired = true)]
        public uint Port { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"zone_id")]
        public ulong ZoneId
        {
            get => __pbn__ZoneId.GetValueOrDefault();
            set => __pbn__ZoneId = value;
        }
        public bool ShouldSerializeZoneId() => __pbn__ZoneId != null;
        public void ResetZoneId() => __pbn__ZoneId = null;
        private ulong? __pbn__ZoneId;

        [global::ProtoBuf.ProtoMember(4, Name = @"additional_params")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AdditionalParams
        {
            get => __pbn__AdditionalParams ?? "";
            set => __pbn__AdditionalParams = value;
        }
        public bool ShouldSerializeAdditionalParams() => __pbn__AdditionalParams != null;
        public void ResetAdditionalParams() => __pbn__AdditionalParams = null;
        private string __pbn__AdditionalParams;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AchievementTrackerUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_id")]
        public ulong AccountId
        {
            get => __pbn__AccountId.GetValueOrDefault();
            set => __pbn__AccountId = value;
        }
        public bool ShouldSerializeAccountId() => __pbn__AccountId != null;
        public void ResetAccountId() => __pbn__AccountId = null;
        private ulong? __pbn__AccountId;

        [global::ProtoBuf.ProtoMember(2, Name = @"achievements_completed")]
        public ulong[] AchievementsCompleteds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"objectives_completed")]
        public ulong[] ObjectivesCompleteds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"init_message")]
        public bool InitMessage
        {
            get => __pbn__InitMessage.GetValueOrDefault();
            set => __pbn__InitMessage = value;
        }
        public bool ShouldSerializeInitMessage() => __pbn__InitMessage != null;
        public void ResetInitMessage() => __pbn__InitMessage = null;
        private bool? __pbn__InitMessage;

        [global::ProtoBuf.ProtoMember(5, Name = @"cheats_used")]
        public bool CheatsUsed
        {
            get => __pbn__CheatsUsed.GetValueOrDefault();
            set => __pbn__CheatsUsed = value;
        }
        public bool ShouldSerializeCheatsUsed() => __pbn__CheatsUsed != null;
        public void ResetCheatsUsed() => __pbn__CheatsUsed = null;
        private bool? __pbn__CheatsUsed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AcctGoalsStatusUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_id")]
        public ulong AccountId
        {
            get => __pbn__AccountId.GetValueOrDefault();
            set => __pbn__AccountId = value;
        }
        public bool ShouldSerializeAccountId() => __pbn__AccountId != null;
        public void ResetAccountId() => __pbn__AccountId = null;
        private ulong? __pbn__AccountId;

        [global::ProtoBuf.ProtoMember(2, Name = @"goals_updated")]
        public ulong[] GoalsUpdateds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"goal_values")]
        public long[] GoalValues { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"goal_objectives")]
        public long[] GoalObjectives { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"goals_that_are_money")]
        public bool[] GoalsThatAreMoneys { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"goals_that_show_progress")]
        public bool[] GoalsThatShowProgresses { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameTimeCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clock_speed", IsRequired = true)]
        public uint ClockSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"game_speed", IsRequired = true)]
        public float GameSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"server_time", IsRequired = true)]
        public ulong ServerTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sync_game_time", IsRequired = true)]
        public ulong SyncGameTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"monotonic_time", IsRequired = true)]
        public ulong MonotonicTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"super_speed")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool SuperSpeed
        {
            get => __pbn__SuperSpeed ?? false;
            set => __pbn__SuperSpeed = value;
        }
        public bool ShouldSerializeSuperSpeed() => __pbn__SuperSpeed != null;
        public void ResetSuperSpeed() => __pbn__SuperSpeed = null;
        private bool? __pbn__SuperSpeed;

        [global::ProtoBuf.ProtoMember(7, Name = @"serial_number")]
        public ulong SerialNumber
        {
            get => __pbn__SerialNumber.GetValueOrDefault();
            set => __pbn__SerialNumber = value;
        }
        public bool ShouldSerializeSerialNumber() => __pbn__SerialNumber != null;
        public void ResetSerialNumber() => __pbn__SerialNumber = null;
        private ulong? __pbn__SerialNumber;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public SocialNotificationType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"localized_string", IsRequired = true)]
        public LocalizedString LocalizedString { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"account_id")]
        public ulong AccountId
        {
            get => __pbn__AccountId.GetValueOrDefault();
            set => __pbn__AccountId = value;
        }
        public bool ShouldSerializeAccountId() => __pbn__AccountId != null;
        public void ResetAccountId() => __pbn__AccountId = null;
        private ulong? __pbn__AccountId;

        [global::ProtoBuf.ProtoMember(4, Name = @"sim_id")]
        public ulong SimId
        {
            get => __pbn__SimId.GetValueOrDefault();
            set => __pbn__SimId = value;
        }
        public bool ShouldSerializeSimId() => __pbn__SimId != null;
        public void ResetSimId() => __pbn__SimId = null;
        private ulong? __pbn__SimId;

        [global::ProtoBuf.ProtoMember(6, Name = @"event_uid")]
        public uint EventUid
        {
            get => __pbn__EventUid.GetValueOrDefault();
            set => __pbn__EventUid = value;
        }
        public bool ShouldSerializeEventUid() => __pbn__EventUid != null;
        public void ResetEventUid() => __pbn__EventUid = null;
        private uint? __pbn__EventUid;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SocialNotificationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CHAT")]
        Chat = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BUDDYLIST")]
        Buddylist = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BUDDYLIST_INVITE")]
        BuddylistInvite = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"WALL")]
        Wall = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"GAMEPLAY")]
        Gameplay = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"MTX")]
        Mtx = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"IMMEDIATE")]
        Immediate = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"GAMEPLAY_ASPIRATION")]
        GameplayAspiration = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"SYSTEM")]
        System = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"EXCHANGE")]
        Exchange = 9,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
