// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Audio.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundStart : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id")]
        public ulong ObjectId
        {
            get => __pbn__ObjectId.GetValueOrDefault();
            set => __pbn__ObjectId = value;
        }
        public bool ShouldSerializeObjectId() => __pbn__ObjectId != null;
        public void ResetObjectId() => __pbn__ObjectId = null;
        private ulong? __pbn__ObjectId;

        [global::ProtoBuf.ProtoMember(2, Name = @"channel")]
        public uint Channel
        {
            get => __pbn__Channel.GetValueOrDefault();
            set => __pbn__Channel = value;
        }
        public bool ShouldSerializeChannel() => __pbn__Channel != null;
        public void ResetChannel() => __pbn__Channel = null;
        private uint? __pbn__Channel;

        [global::ProtoBuf.ProtoMember(3, Name = @"sound_id", IsRequired = true)]
        public ulong SoundId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_vox")]
        public bool IsVox
        {
            get => __pbn__IsVox.GetValueOrDefault();
            set => __pbn__IsVox = value;
        }
        public bool ShouldSerializeIsVox() => __pbn__IsVox != null;
        public void ResetIsVox() => __pbn__IsVox = null;
        private bool? __pbn__IsVox;

        [global::ProtoBuf.ProtoMember(5, Name = @"joint_name_hash")]
        public uint JointNameHash
        {
            get => __pbn__JointNameHash.GetValueOrDefault();
            set => __pbn__JointNameHash = value;
        }
        public bool ShouldSerializeJointNameHash() => __pbn__JointNameHash != null;
        public void ResetJointNameHash() => __pbn__JointNameHash = null;
        private uint? __pbn__JointNameHash;

        [global::ProtoBuf.ProtoMember(6, Name = @"play_on_active_sim_only")]
        public bool PlayOnActiveSimOnly
        {
            get => __pbn__PlayOnActiveSimOnly.GetValueOrDefault();
            set => __pbn__PlayOnActiveSimOnly = value;
        }
        public bool ShouldSerializePlayOnActiveSimOnly() => __pbn__PlayOnActiveSimOnly != null;
        public void ResetPlayOnActiveSimOnly() => __pbn__PlayOnActiveSimOnly = null;
        private bool? __pbn__PlayOnActiveSimOnly;

        [global::ProtoBuf.ProtoMember(7, Name = @"sound_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SoundName
        {
            get => __pbn__SoundName ?? "";
            set => __pbn__SoundName = value;
        }
        public bool ShouldSerializeSoundName() => __pbn__SoundName != null;
        public void ResetSoundName() => __pbn__SoundName = null;
        private string __pbn__SoundName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id", IsRequired = true)]
        public ulong ObjectId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"channel", IsRequired = true)]
        public uint Channel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundSkipToNext : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id", IsRequired = true)]
        public ulong ObjectId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"channel", IsRequired = true)]
        public uint Channel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundResource : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sound")]
        public ResourceKey Sound { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"music_track_snippet")]
        public ResourceKey MusicTrackSnippet { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
