// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Calendar.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CalendarFavoriteData : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong HouseholdId
    {
        get => __pbn__HouseholdId.GetValueOrDefault();
        set => __pbn__HouseholdId = value;
    }
    public bool ShouldSerializeHouseholdId() => __pbn__HouseholdId != null;
    public void ResetHouseholdId() => __pbn__HouseholdId = null;
    private ulong? __pbn__HouseholdId;

    [global::ProtoBuf.ProtoMember(2, Name = @"favorited_event_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong[] FavoritedEventIds { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class PersistableCalendarService : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"favorite_data")]
    public global::System.Collections.Generic.List<CalendarFavoriteData> FavoriteDatas { get; } = new global::System.Collections.Generic.List<CalendarFavoriteData>();

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
