// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Clubs.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubCriteria : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"category", IsRequired = true)]
        public ClubCriteriaCategory Category { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"criteria_infos")]
        public global::System.Collections.Generic.List<ClubCriteriaInfo> CriteriaInfos { get; } = new global::System.Collections.Generic.List<ClubCriteriaInfo>();

        [global::ProtoBuf.ProtoMember(3, Name = @"multi_select")]
        public bool MultiSelect
        {
            get => __pbn__MultiSelect.GetValueOrDefault();
            set => __pbn__MultiSelect = value;
        }
        public bool ShouldSerializeMultiSelect() => __pbn__MultiSelect != null;
        public void ResetMultiSelect() => __pbn__MultiSelect = null;
        private bool? __pbn__MultiSelect;

        [global::ProtoBuf.ProtoMember(4, Name = @"criteria_id")]
        public uint CriteriaId
        {
            get => __pbn__CriteriaId.GetValueOrDefault();
            set => __pbn__CriteriaId = value;
        }
        public bool ShouldSerializeCriteriaId() => __pbn__CriteriaId != null;
        public void ResetCriteriaId() => __pbn__CriteriaId = null;
        private uint? __pbn__CriteriaId;

        [global::ProtoBuf.ProtoContract()]
        public enum ClubCriteriaCategory
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SKILL")]
            Skill = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TRAIT")]
            Trait = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RELATIONSHIP")]
            Relationship = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CAREER")]
            Career = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"HOUSEHOLD_VALUE")]
            HouseholdValue = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"AGE")]
            Age = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"CLUB_MEMBERSHIP")]
            ClubMembership = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"FAME_RANK")]
            FameRank = 7,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubCriteriaInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        public LocalizedString Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"icon")]
        public ResourceKey Icon { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"resource_value")]
        public ResourceKey ResourceValue { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"enum_value")]
        public uint EnumValue
        {
            get => __pbn__EnumValue.GetValueOrDefault();
            set => __pbn__EnumValue = value;
        }
        public bool ShouldSerializeEnumValue() => __pbn__EnumValue != null;
        public void ResetEnumValue() => __pbn__EnumValue = null;
        private uint? __pbn__EnumValue;

        [global::ProtoBuf.ProtoMember(5, Name = @"resource_id")]
        public ulong ResourceId
        {
            get => __pbn__ResourceId.GetValueOrDefault();
            set => __pbn__ResourceId = value;
        }
        public bool ShouldSerializeResourceId() => __pbn__ResourceId != null;
        public void ResetResourceId() => __pbn__ResourceId = null;
        private ulong? __pbn__ResourceId;

        [global::ProtoBuf.ProtoMember(6, Name = @"tooltip_name")]
        public LocalizedString TooltipName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubConductRule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"encouraged", IsRequired = true)]
        public bool Encouraged { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"interaction_group", IsRequired = true)]
        public ResourceKey InteractionGroup { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"with_whom")]
        public ClubCriteria WithWhom { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubBuildingInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"criterias")]
        public global::System.Collections.Generic.List<ClubCriteria> Criterias { get; } = new global::System.Collections.Generic.List<ClubCriteria>();

        [global::ProtoBuf.ProtoMember(2, Name = @"available_lots")]
        public global::System.Collections.Generic.List<LotInfoItem> AvailableLots { get; } = new global::System.Collections.Generic.List<LotInfoItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClubInteractionRuleUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rule_status", IsRequired = true)]
        public ClubInteractionRuleStatus RuleStatus { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ClubInteractionRuleStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ENCOURAGED")]
            Encouraged = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DISCOURAGED")]
            Discouraged = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"NO_EFFECT")]
            NoEffect = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ShowClubInfoUI : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"club_id")]
        public ulong ClubId
        {
            get => __pbn__ClubId.GetValueOrDefault();
            set => __pbn__ClubId = value;
        }
        public bool ShouldSerializeClubId() => __pbn__ClubId != null;
        public void ResetClubId() => __pbn__ClubId = null;
        private ulong? __pbn__ClubId;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
