// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: CustomSchedule.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ScheduleAssignmentOutfit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"outfit_setting")]
        [global::System.ComponentModel.DefaultValue(ScheduleOutfitSetting.NoOutfit)]
        public ScheduleOutfitSetting OutfitSetting
        {
            get => __pbn__OutfitSetting ?? ScheduleOutfitSetting.NoOutfit;
            set => __pbn__OutfitSetting = value;
        }
        public bool ShouldSerializeOutfitSetting() => __pbn__OutfitSetting != null;
        public void ResetOutfitSetting() => __pbn__OutfitSetting = null;
        private ScheduleOutfitSetting? __pbn__OutfitSetting;

        [global::ProtoBuf.ProtoMember(2, Name = @"outfit_color")]
        public uint OutfitColor
        {
            get => __pbn__OutfitColor.GetValueOrDefault();
            set => __pbn__OutfitColor = value;
        }
        public bool ShouldSerializeOutfitColor() => __pbn__OutfitColor != null;
        public void ResetOutfitColor() => __pbn__OutfitColor = null;
        private uint? __pbn__OutfitColor;

        [global::ProtoBuf.ProtoMember(3, Name = @"outfit_style")]
        public uint OutfitStyle
        {
            get => __pbn__OutfitStyle.GetValueOrDefault();
            set => __pbn__OutfitStyle = value;
        }
        public bool ShouldSerializeOutfitStyle() => __pbn__OutfitStyle != null;
        public void ResetOutfitStyle() => __pbn__OutfitStyle = null;
        private uint? __pbn__OutfitStyle;

        [global::ProtoBuf.ProtoMember(4, Name = @"outfit_category")]
        public uint OutfitCategory
        {
            get => __pbn__OutfitCategory.GetValueOrDefault();
            set => __pbn__OutfitCategory = value;
        }
        public bool ShouldSerializeOutfitCategory() => __pbn__OutfitCategory != null;
        public void ResetOutfitCategory() => __pbn__OutfitCategory = null;
        private uint? __pbn__OutfitCategory;

        [global::ProtoBuf.ProtoMember(5, Name = @"assignment_uniform_adult_male")]
        public global::EA.Sims4.Persistence.MannequinSimData AssignmentUniformAdultMale { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"assignment_uniform_adult_female")]
        public global::EA.Sims4.Persistence.MannequinSimData AssignmentUniformAdultFemale { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"assignment_uniform_child_male")]
        public global::EA.Sims4.Persistence.MannequinSimData AssignmentUniformChildMale { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"assignment_uniform_child_female")]
        public global::EA.Sims4.Persistence.MannequinSimData AssignmentUniformChildFemale { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"style_enabled")]
        public bool StyleEnabled
        {
            get => __pbn__StyleEnabled.GetValueOrDefault();
            set => __pbn__StyleEnabled = value;
        }
        public bool ShouldSerializeStyleEnabled() => __pbn__StyleEnabled != null;
        public void ResetStyleEnabled() => __pbn__StyleEnabled = null;
        private bool? __pbn__StyleEnabled;

        [global::ProtoBuf.ProtoMember(10, Name = @"color_enabled")]
        public bool ColorEnabled
        {
            get => __pbn__ColorEnabled.GetValueOrDefault();
            set => __pbn__ColorEnabled = value;
        }
        public bool ShouldSerializeColorEnabled() => __pbn__ColorEnabled != null;
        public void ResetColorEnabled() => __pbn__ColorEnabled = null;
        private bool? __pbn__ColorEnabled;

        [global::ProtoBuf.ProtoContract()]
        public enum ScheduleOutfitSetting
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NO_OUTFIT")]
            NoOutfit = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CATEGORY")]
            Category = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"STYLE_COLOR")]
            StyleColor = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"OUTFIT_OVERRIDE")]
            OutfitOverride = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScheduleAssignment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_count")]
        public uint SimCount
        {
            get => __pbn__SimCount.GetValueOrDefault();
            set => __pbn__SimCount = value;
        }
        public bool ShouldSerializeSimCount() => __pbn__SimCount != null;
        public void ResetSimCount() => __pbn__SimCount = null;
        private uint? __pbn__SimCount;

        [global::ProtoBuf.ProtoMember(3, Name = @"sim_criteria")]
        public global::System.Collections.Generic.List<ClubCriteria> SimCriterias { get; } = new global::System.Collections.Generic.List<ClubCriteria>();

        [global::ProtoBuf.ProtoMember(4, Name = @"assignment_behaviors")]
        public global::System.Collections.Generic.List<ResourceKey> AssignmentBehaviors { get; } = new global::System.Collections.Generic.List<ResourceKey>();

        [global::ProtoBuf.ProtoMember(5, Name = @"assignment_outfit")]
        public ScheduleAssignmentOutfit AssignmentOutfit { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"sim_ids")]
        public ulong[] SimIds { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"is_new")]
        public bool IsNew
        {
            get => __pbn__IsNew.GetValueOrDefault();
            set => __pbn__IsNew = value;
        }
        public bool ShouldSerializeIsNew() => __pbn__IsNew != null;
        public void ResetIsNew() => __pbn__IsNew = null;
        private bool? __pbn__IsNew;

        [global::ProtoBuf.ProtoMember(8, Name = @"is_immutable")]
        public bool IsImmutable
        {
            get => __pbn__IsImmutable.GetValueOrDefault();
            set => __pbn__IsImmutable = value;
        }
        public bool ShouldSerializeIsImmutable() => __pbn__IsImmutable != null;
        public void ResetIsImmutable() => __pbn__IsImmutable = null;
        private bool? __pbn__IsImmutable;

        [global::ProtoBuf.ProtoMember(9, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(10, Name = @"premade_name")]
        public LocalizedString PremadeName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScheduleTimeSlotAssignment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"assignment_id")]
        public uint AssignmentId
        {
            get => __pbn__AssignmentId.GetValueOrDefault();
            set => __pbn__AssignmentId = value;
        }
        public bool ShouldSerializeAssignmentId() => __pbn__AssignmentId != null;
        public void ResetAssignmentId() => __pbn__AssignmentId = null;
        private uint? __pbn__AssignmentId;

        [global::ProtoBuf.ProtoMember(2, Name = @"assignment_overrides")]
        public ScheduleAssignment AssignmentOverrides { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"has_behavior_override")]
        public bool HasBehaviorOverride
        {
            get => __pbn__HasBehaviorOverride.GetValueOrDefault();
            set => __pbn__HasBehaviorOverride = value;
        }
        public bool ShouldSerializeHasBehaviorOverride() => __pbn__HasBehaviorOverride != null;
        public void ResetHasBehaviorOverride() => __pbn__HasBehaviorOverride = null;
        private bool? __pbn__HasBehaviorOverride;

        [global::ProtoBuf.ProtoMember(4, Name = @"has_sim_overrides")]
        public bool HasSimOverrides
        {
            get => __pbn__HasSimOverrides.GetValueOrDefault();
            set => __pbn__HasSimOverrides = value;
        }
        public bool ShouldSerializeHasSimOverrides() => __pbn__HasSimOverrides != null;
        public void ResetHasSimOverrides() => __pbn__HasSimOverrides = null;
        private bool? __pbn__HasSimOverrides;

        [global::ProtoBuf.ProtoMember(5, Name = @"has_outfit_override")]
        public bool HasOutfitOverride
        {
            get => __pbn__HasOutfitOverride.GetValueOrDefault();
            set => __pbn__HasOutfitOverride = value;
        }
        public bool ShouldSerializeHasOutfitOverride() => __pbn__HasOutfitOverride != null;
        public void ResetHasOutfitOverride() => __pbn__HasOutfitOverride = null;
        private bool? __pbn__HasOutfitOverride;

        [global::ProtoBuf.ProtoMember(6, Name = @"has_count_override")]
        public bool HasCountOverride
        {
            get => __pbn__HasCountOverride.GetValueOrDefault();
            set => __pbn__HasCountOverride = value;
        }
        public bool ShouldSerializeHasCountOverride() => __pbn__HasCountOverride != null;
        public void ResetHasCountOverride() => __pbn__HasCountOverride = null;
        private bool? __pbn__HasCountOverride;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScheduleTimeSlot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_time")]
        public uint StartTime
        {
            get => __pbn__StartTime.GetValueOrDefault();
            set => __pbn__StartTime = value;
        }
        public bool ShouldSerializeStartTime() => __pbn__StartTime != null;
        public void ResetStartTime() => __pbn__StartTime = null;
        private uint? __pbn__StartTime;

        [global::ProtoBuf.ProtoMember(2, Name = @"default_behavior")]
        public ResourceKey DefaultBehavior { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"assignments")]
        public global::System.Collections.Generic.List<ScheduleTimeSlotAssignment> Assignments { get; } = new global::System.Collections.Generic.List<ScheduleTimeSlotAssignment>();

        [global::ProtoBuf.ProtoMember(4, Name = @"shuffled_behavior")]
        public ResourceKey ShuffledBehavior { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetawaySelectedRule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rule_guid64")]
        public ulong RuleGuid64
        {
            get => __pbn__RuleGuid64.GetValueOrDefault();
            set => __pbn__RuleGuid64 = value;
        }
        public bool ShouldSerializeRuleGuid64() => __pbn__RuleGuid64 != null;
        public void ResetRuleGuid64() => __pbn__RuleGuid64 = null;
        private ulong? __pbn__RuleGuid64;

        [global::ProtoBuf.ProtoMember(2, Name = @"groups")]
        public global::System.Collections.Generic.List<SelectedRuleGroup> Groups { get; } = new global::System.Collections.Generic.List<SelectedRuleGroup>();

        [global::ProtoBuf.ProtoMember(3, Name = @"use_current_track_values")]
        public bool UseCurrentTrackValues
        {
            get => __pbn__UseCurrentTrackValues.GetValueOrDefault();
            set => __pbn__UseCurrentTrackValues = value;
        }
        public bool ShouldSerializeUseCurrentTrackValues() => __pbn__UseCurrentTrackValues != null;
        public void ResetUseCurrentTrackValues() => __pbn__UseCurrentTrackValues = null;
        private bool? __pbn__UseCurrentTrackValues;

        [global::ProtoBuf.ProtoContract()]
        public partial class SelectedRuleGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
            public uint GroupId
            {
                get => __pbn__GroupId.GetValueOrDefault();
                set => __pbn__GroupId = value;
            }
            public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
            public void ResetGroupId() => __pbn__GroupId = null;
            private uint? __pbn__GroupId;

            [global::ProtoBuf.ProtoMember(2, Name = @"assignment_names")]
            public global::System.Collections.Generic.List<string> AssignmentNames { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(3, Name = @"assignment_ids")]
            public uint[] AssignmentIds { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomSchedule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"assignment_presets")]
        public global::System.Collections.Generic.List<ScheduleAssignment> AssignmentPresets { get; } = new global::System.Collections.Generic.List<ScheduleAssignment>();

        [global::ProtoBuf.ProtoMember(3, Name = @"time_slots")]
        public global::System.Collections.Generic.List<ScheduleTimeSlot> TimeSlots { get; } = new global::System.Collections.Generic.List<ScheduleTimeSlot>();

        [global::ProtoBuf.ProtoMember(4, Name = @"rules")]
        public global::System.Collections.Generic.List<GetawaySelectedRule> Rules { get; } = new global::System.Collections.Generic.List<GetawaySelectedRule>();

        [global::ProtoBuf.ProtoMember(5, Name = @"is_immutable")]
        public bool IsImmutable
        {
            get => __pbn__IsImmutable.GetValueOrDefault();
            set => __pbn__IsImmutable = value;
        }
        public bool ShouldSerializeIsImmutable() => __pbn__IsImmutable != null;
        public void ResetIsImmutable() => __pbn__IsImmutable = null;
        private bool? __pbn__IsImmutable;

        [global::ProtoBuf.ProtoMember(6, Name = @"premade_name")]
        public LocalizedString PremadeName { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"has_started")]
        public bool HasStarted
        {
            get => __pbn__HasStarted.GetValueOrDefault();
            set => __pbn__HasStarted = value;
        }
        public bool ShouldSerializeHasStarted() => __pbn__HasStarted != null;
        public void ResetHasStarted() => __pbn__HasStarted = null;
        private bool? __pbn__HasStarted;

        [global::ProtoBuf.ProtoMember(8, Name = @"use_current_track_values")]
        public bool UseCurrentTrackValues
        {
            get => __pbn__UseCurrentTrackValues.GetValueOrDefault();
            set => __pbn__UseCurrentTrackValues = value;
        }
        public bool ShouldSerializeUseCurrentTrackValues() => __pbn__UseCurrentTrackValues != null;
        public void ResetUseCurrentTrackValues() => __pbn__UseCurrentTrackValues = null;
        private bool? __pbn__UseCurrentTrackValues;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AssignmentListData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_immutable")]
        public bool IsImmutable
        {
            get => __pbn__IsImmutable.GetValueOrDefault();
            set => __pbn__IsImmutable = value;
        }
        public bool ShouldSerializeIsImmutable() => __pbn__IsImmutable != null;
        public void ResetIsImmutable() => __pbn__IsImmutable = null;
        private bool? __pbn__IsImmutable;

        [global::ProtoBuf.ProtoMember(3, Name = @"premade_name")]
        public LocalizedString PremadeName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AssignmentList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"assignments")]
        public global::System.Collections.Generic.List<AssignmentListData> Assignments { get; } = new global::System.Collections.Generic.List<AssignmentListData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScheduleListData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_immutable")]
        public bool IsImmutable
        {
            get => __pbn__IsImmutable.GetValueOrDefault();
            set => __pbn__IsImmutable = value;
        }
        public bool ShouldSerializeIsImmutable() => __pbn__IsImmutable != null;
        public void ResetIsImmutable() => __pbn__IsImmutable = null;
        private bool? __pbn__IsImmutable;

        [global::ProtoBuf.ProtoMember(3, Name = @"lot_current")]
        public bool LotCurrent
        {
            get => __pbn__LotCurrent.GetValueOrDefault();
            set => __pbn__LotCurrent = value;
        }
        public bool ShouldSerializeLotCurrent() => __pbn__LotCurrent != null;
        public void ResetLotCurrent() => __pbn__LotCurrent = null;
        private bool? __pbn__LotCurrent;

        [global::ProtoBuf.ProtoMember(4, Name = @"premade_name")]
        public LocalizedString PremadeName { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"has_rules")]
        public bool HasRules
        {
            get => __pbn__HasRules.GetValueOrDefault();
            set => __pbn__HasRules = value;
        }
        public bool ShouldSerializeHasRules() => __pbn__HasRules != null;
        public void ResetHasRules() => __pbn__HasRules = null;
        private bool? __pbn__HasRules;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScheduleList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"schedules")]
        public global::System.Collections.Generic.List<ScheduleListData> Schedules { get; } = new global::System.Collections.Generic.List<ScheduleListData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomScheduleSetCustomSchedule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"schedule")]
        public CustomSchedule Schedule { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomScheduleSetCustomAssignment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"assignment")]
        public ScheduleAssignment Assignment { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomScheduleSetScheduleList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"schedule_list")]
        public ScheduleList ScheduleList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomScheduleSetAssignmentList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"assignment_list")]
        public AssignmentList AssignmentList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomScheduleSetMannequinData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"assignment_uniform")]
        public global::EA.Sims4.Persistence.MannequinSimData AssignmentUniform { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomScheduleSetAvailableSims : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] SimIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"invalid_sim_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] InvalidSimIds { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
