// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: DebugVisualization.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract(Name = @"DebugViz_LineSet")]
    public partial class DebugVizLineSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lines")]
        public global::System.Collections.Generic.List<Line> Lines { get; } = new global::System.Collections.Generic.List<Line>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Line : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"begin", IsRequired = true)]
            public Vector3 Begin { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end", IsRequired = true)]
            public Vector3 End { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"color", IsRequired = true)]
            public uint Color { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"DebugViz_Text")]
    public partial class DebugVizText : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"position_2d")]
        public Vector2 Position2d { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"position_3d")]
        public Vector3 Position3d { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"color_fg")]
        public uint ColorFg
        {
            get => __pbn__ColorFg.GetValueOrDefault();
            set => __pbn__ColorFg = value;
        }
        public bool ShouldSerializeColorFg() => __pbn__ColorFg != null;
        public void ResetColorFg() => __pbn__ColorFg = null;
        private uint? __pbn__ColorFg;

        [global::ProtoBuf.ProtoMember(4, Name = @"color_bg")]
        public uint ColorBg
        {
            get => __pbn__ColorBg.GetValueOrDefault();
            set => __pbn__ColorBg = value;
        }
        public bool ShouldSerializeColorBg() => __pbn__ColorBg != null;
        public void ResetColorBg() => __pbn__ColorBg = null;
        private uint? __pbn__ColorBg;

        [global::ProtoBuf.ProtoMember(5, Name = @"text", IsRequired = true)]
        public string Text { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(Alignment.AlignLeft)]
        public Alignment alignment
        {
            get => __pbn__alignment ?? Alignment.AlignLeft;
            set => __pbn__alignment = value;
        }
        public bool ShouldSerializealignment() => __pbn__alignment != null;
        public void Resetalignment() => __pbn__alignment = null;
        private Alignment? __pbn__alignment;

        [global::ProtoBuf.ProtoMember(7, Name = @"vertalign")]
        [global::System.ComponentModel.DefaultValue(VertAlign.VertalignTop)]
        public VertAlign Vertalign
        {
            get => __pbn__Vertalign ?? VertAlign.VertalignTop;
            set => __pbn__Vertalign = value;
        }
        public bool ShouldSerializeVertalign() => __pbn__Vertalign != null;
        public void ResetVertalign() => __pbn__Vertalign = null;
        private VertAlign? __pbn__Vertalign;

        [global::ProtoBuf.ProtoMember(8, Name = @"object_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ObjectId
        {
            get => __pbn__ObjectId.GetValueOrDefault();
            set => __pbn__ObjectId = value;
        }
        public bool ShouldSerializeObjectId() => __pbn__ObjectId != null;
        public void ResetObjectId() => __pbn__ObjectId = null;
        private ulong? __pbn__ObjectId;

        [global::ProtoBuf.ProtoMember(9, Name = @"bone_index")]
        public int BoneIndex
        {
            get => __pbn__BoneIndex.GetValueOrDefault();
            set => __pbn__BoneIndex = value;
        }
        public bool ShouldSerializeBoneIndex() => __pbn__BoneIndex != null;
        public void ResetBoneIndex() => __pbn__BoneIndex = null;
        private int? __pbn__BoneIndex;

        [global::ProtoBuf.ProtoContract()]
        public enum Alignment
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ALIGN_LEFT")]
            AlignLeft = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"ALIGN_CENTER")]
            AlignCenter = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ALIGN_RIGHT")]
            AlignRight = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum VertAlign
        {
            [global::ProtoBuf.ProtoEnum(Name = @"VERTALIGN_TOP")]
            VertalignTop = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"VERTALIGN_MIDDLE")]
            VertalignMiddle = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"VERTALIGN_BOTTOM")]
            VertalignBottom = 2,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"DebugViz_Layer")]
    public partial class DebugVizLayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"lines_data")]
        public byte[] LinesData
        {
            get => __pbn__LinesData;
            set => __pbn__LinesData = value;
        }
        public bool ShouldSerializeLinesData() => __pbn__LinesData != null;
        public void ResetLinesData() => __pbn__LinesData = null;
        private byte[] __pbn__LinesData;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong zoneId
        {
            get => __pbn__zoneId.GetValueOrDefault();
            set => __pbn__zoneId = value;
        }
        public bool ShouldSerializezoneId() => __pbn__zoneId != null;
        public void ResetzoneId() => __pbn__zoneId = null;
        private ulong? __pbn__zoneId;

        [global::ProtoBuf.ProtoMember(4, Name = @"text_set")]
        public global::System.Collections.Generic.List<DebugVizText> TextSets { get; } = new global::System.Collections.Generic.List<DebugVizText>();

        [global::ProtoBuf.ProtoMember(5, Name = @"tris_data")]
        public byte[] TrisData
        {
            get => __pbn__TrisData;
            set => __pbn__TrisData = value;
        }
        public bool ShouldSerializeTrisData() => __pbn__TrisData != null;
        public void ResetTrisData() => __pbn__TrisData = null;
        private byte[] __pbn__TrisData;

    }

    [global::ProtoBuf.ProtoContract(Name = @"DebugViz_LayerUpdateNotification")]
    public partial class DebugVizLayerUpdateNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string layerName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong zoneId
        {
            get => __pbn__zoneId.GetValueOrDefault();
            set => __pbn__zoneId = value;
        }
        public bool ShouldSerializezoneId() => __pbn__zoneId != null;
        public void ResetzoneId() => __pbn__zoneId = null;
        private ulong? __pbn__zoneId;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
