// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: InteractionOps.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Interactable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_interactable", IsRequired = true)]
        public bool IsInteractable { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"object_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong ObjectId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong interactable_flags
        {
            get => __pbn__interactable_flags ?? 0ul;
            set => __pbn__interactable_flags = value;
        }
        public bool ShouldSerializeinteractable_flags() => __pbn__interactable_flags != null;
        public void Resetinteractable_flags() => __pbn__interactable_flags = null;
        private ulong? __pbn__interactable_flags;

        [global::ProtoBuf.ProtoContract()]
        public enum InteractableFlags
        {
            [global::ProtoBuf.ProtoEnum(Name = @"INTERACTABLE")]
            Interactable = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FORSALE")]
            Forsale = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PieMenuItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"loc_string", IsRequired = true)]
        public LocalizedString LocString { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"related_skills")]
        public ulong[] RelatedSkills { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"target_ids")]
        public ulong[] TargetIds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"icon")]
        public ResourceKey Icon { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"disabled_text")]
        public LocalizedString DisabledText { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"score_icon")]
        public ResourceKey ScoreIcon { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"category_key")]
        public ulong CategoryKey
        {
            get => __pbn__CategoryKey.GetValueOrDefault();
            set => __pbn__CategoryKey = value;
        }
        public bool ShouldSerializeCategoryKey() => __pbn__CategoryKey != null;
        public void ResetCategoryKey() => __pbn__CategoryKey = null;
        private ulong? __pbn__CategoryKey;

        [global::ProtoBuf.ProtoMember(10, Name = @"is_super")]
        public bool IsSuper
        {
            get => __pbn__IsSuper.GetValueOrDefault();
            set => __pbn__IsSuper = value;
        }
        public bool ShouldSerializeIsSuper() => __pbn__IsSuper != null;
        public void ResetIsSuper() => __pbn__IsSuper = null;
        private bool? __pbn__IsSuper;

        [global::ProtoBuf.ProtoMember(11, Name = @"score")]
        public float Score
        {
            get => __pbn__Score.GetValueOrDefault();
            set => __pbn__Score = value;
        }
        public bool ShouldSerializeScore() => __pbn__Score != null;
        public void ResetScore() => __pbn__Score = null;
        private float? __pbn__Score;

        [global::ProtoBuf.ProtoMember(12, Name = @"icons")]
        public global::System.Collections.Generic.List<ResourceKey> Icons { get; } = new global::System.Collections.Generic.List<ResourceKey>();

        [global::ProtoBuf.ProtoMember(13, Name = @"mood", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Mood
        {
            get => __pbn__Mood.GetValueOrDefault();
            set => __pbn__Mood = value;
        }
        public bool ShouldSerializeMood() => __pbn__Mood != null;
        public void ResetMood() => __pbn__Mood = null;
        private ulong? __pbn__Mood;

        [global::ProtoBuf.ProtoMember(14, Name = @"mood_intensity")]
        public uint MoodIntensity
        {
            get => __pbn__MoodIntensity.GetValueOrDefault();
            set => __pbn__MoodIntensity = value;
        }
        public bool ShouldSerializeMoodIntensity() => __pbn__MoodIntensity != null;
        public void ResetMoodIntensity() => __pbn__MoodIntensity = null;
        private uint? __pbn__MoodIntensity;

        [global::ProtoBuf.ProtoMember(15, Name = @"pie_menu_priority")]
        public uint PieMenuPriority
        {
            get => __pbn__PieMenuPriority.GetValueOrDefault();
            set => __pbn__PieMenuPriority = value;
        }
        public bool ShouldSerializePieMenuPriority() => __pbn__PieMenuPriority != null;
        public void ResetPieMenuPriority() => __pbn__PieMenuPriority = null;
        private uint? __pbn__PieMenuPriority;

        [global::ProtoBuf.ProtoMember(16, Name = @"success_tooltip")]
        public LocalizedString SuccessTooltip { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"icon_infos")]
        public global::System.Collections.Generic.List<IconInfo> IconInfos { get; } = new global::System.Collections.Generic.List<IconInfo>();

        [global::ProtoBuf.ProtoMember(18, Name = @"display_notification")]
        public bool DisplayNotification
        {
            get => __pbn__DisplayNotification.GetValueOrDefault();
            set => __pbn__DisplayNotification = value;
        }
        public bool ShouldSerializeDisplayNotification() => __pbn__DisplayNotification != null;
        public void ResetDisplayNotification() => __pbn__DisplayNotification = null;
        private bool? __pbn__DisplayNotification;

        [global::ProtoBuf.ProtoMember(19, Name = @"affordance_id")]
        public ulong AffordanceId
        {
            get => __pbn__AffordanceId.GetValueOrDefault();
            set => __pbn__AffordanceId = value;
        }
        public bool ShouldSerializeAffordanceId() => __pbn__AffordanceId != null;
        public void ResetAffordanceId() => __pbn__AffordanceId = null;
        private ulong? __pbn__AffordanceId;

        [global::ProtoBuf.ProtoMember(20, Name = @"phone_notification_control_override")]
        public bool PhoneNotificationControlOverride
        {
            get => __pbn__PhoneNotificationControlOverride.GetValueOrDefault();
            set => __pbn__PhoneNotificationControlOverride = value;
        }
        public bool ShouldSerializePhoneNotificationControlOverride() => __pbn__PhoneNotificationControlOverride != null;
        public void ResetPhoneNotificationControlOverride() => __pbn__PhoneNotificationControlOverride = null;
        private bool? __pbn__PhoneNotificationControlOverride;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PieMenuCreate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim", IsRequired = true)]
        public ulong Sim { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"items")]
        public global::System.Collections.Generic.List<PieMenuItem> Items { get; } = new global::System.Collections.Generic.List<PieMenuItem>();

        [global::ProtoBuf.ProtoMember(3, Name = @"client_reference_id")]
        public uint ClientReferenceId
        {
            get => __pbn__ClientReferenceId.GetValueOrDefault();
            set => __pbn__ClientReferenceId = value;
        }
        public bool ShouldSerializeClientReferenceId() => __pbn__ClientReferenceId != null;
        public void ResetClientReferenceId() => __pbn__ClientReferenceId = null;
        private uint? __pbn__ClientReferenceId;

        [global::ProtoBuf.ProtoMember(4, Name = @"server_reference_id")]
        public uint ServerReferenceId
        {
            get => __pbn__ServerReferenceId.GetValueOrDefault();
            set => __pbn__ServerReferenceId = value;
        }
        public bool ShouldSerializeServerReferenceId() => __pbn__ServerReferenceId != null;
        public void ResetServerReferenceId() => __pbn__ServerReferenceId = null;
        private uint? __pbn__ServerReferenceId;

        [global::ProtoBuf.ProtoMember(5, Name = @"category_tokens")]
        public global::System.Collections.Generic.List<LocalizedStringToken> CategoryTokens { get; } = new global::System.Collections.Generic.List<LocalizedStringToken>();

        [global::ProtoBuf.ProtoMember(6, Name = @"disabled_tooltip")]
        public LocalizedString DisabledTooltip { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"supress_social_front_page")]
        public bool SupressSocialFrontPage
        {
            get => __pbn__SupressSocialFrontPage.GetValueOrDefault();
            set => __pbn__SupressSocialFrontPage = value;
        }
        public bool ShouldSerializeSupressSocialFrontPage() => __pbn__SupressSocialFrontPage != null;
        public void ResetSupressSocialFrontPage() => __pbn__SupressSocialFrontPage = null;
        private bool? __pbn__SupressSocialFrontPage;

        [global::ProtoBuf.ProtoMember(8, Name = @"selected_affordance_id")]
        public ulong SelectedAffordanceId
        {
            get => __pbn__SelectedAffordanceId.GetValueOrDefault();
            set => __pbn__SelectedAffordanceId = value;
        }
        public bool ShouldSerializeSelectedAffordanceId() => __pbn__SelectedAffordanceId != null;
        public void ResetSelectedAffordanceId() => __pbn__SelectedAffordanceId = null;
        private ulong? __pbn__SelectedAffordanceId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelMenuCreate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", IsRequired = true)]
        public ulong SimId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"selected_lot_id")]
        public ulong SelectedLotId
        {
            get => __pbn__SelectedLotId.GetValueOrDefault();
            set => __pbn__SelectedLotId = value;
        }
        public bool ShouldSerializeSelectedLotId() => __pbn__SelectedLotId != null;
        public void ResetSelectedLotId() => __pbn__SelectedLotId = null;
        private ulong? __pbn__SelectedLotId;

        [global::ProtoBuf.ProtoMember(3, Name = @"selected_world_id")]
        public uint SelectedWorldId
        {
            get => __pbn__SelectedWorldId.GetValueOrDefault();
            set => __pbn__SelectedWorldId = value;
        }
        public bool ShouldSerializeSelectedWorldId() => __pbn__SelectedWorldId != null;
        public void ResetSelectedWorldId() => __pbn__SelectedWorldId = null;
        private uint? __pbn__SelectedWorldId;

        [global::ProtoBuf.ProtoMember(4, Name = @"selected_lot_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SelectedLotName
        {
            get => __pbn__SelectedLotName ?? "";
            set => __pbn__SelectedLotName = value;
        }
        public bool ShouldSerializeSelectedLotName() => __pbn__SelectedLotName != null;
        public void ResetSelectedLotName() => __pbn__SelectedLotName = null;
        private string __pbn__SelectedLotName;

        [global::ProtoBuf.ProtoMember(5, Name = @"friend_account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FriendAccount
        {
            get => __pbn__FriendAccount ?? "";
            set => __pbn__FriendAccount = value;
        }
        public bool ShouldSerializeFriendAccount() => __pbn__FriendAccount != null;
        public void ResetFriendAccount() => __pbn__FriendAccount = null;
        private string __pbn__FriendAccount;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelMenuInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_ids")]
        public ulong[] SimIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelMenuResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reserved", IsRequired = true)]
        public bool Reserved { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelInitiate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong zoneId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveInMoveOutInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"moving_family_id")]
        public ulong MovingFamilyId
        {
            get => __pbn__MovingFamilyId.GetValueOrDefault();
            set => __pbn__MovingFamilyId = value;
        }
        public bool ShouldSerializeMovingFamilyId() => __pbn__MovingFamilyId != null;
        public void ResetMovingFamilyId() => __pbn__MovingFamilyId = null;
        private ulong? __pbn__MovingFamilyId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_in_game_evict")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsInGameEvict
        {
            get => __pbn__IsInGameEvict ?? false;
            set => __pbn__IsInGameEvict = value;
        }
        public bool ShouldSerializeIsInGameEvict() => __pbn__IsInGameEvict != null;
        public void ResetIsInGameEvict() => __pbn__IsInGameEvict = null;
        private bool? __pbn__IsInGameEvict;

        [global::ProtoBuf.ProtoMember(3, Name = @"source_zone_id")]
        public ulong SourceZoneId
        {
            get => __pbn__SourceZoneId.GetValueOrDefault();
            set => __pbn__SourceZoneId = value;
        }
        public bool ShouldSerializeSourceZoneId() => __pbn__SourceZoneId != null;
        public void ResetSourceZoneId() => __pbn__SourceZoneId = null;
        private ulong? __pbn__SourceZoneId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SellRetailLot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retail_zone_id", IsRequired = true)]
        public ulong RetailZoneId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TravelSimsToZone : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"zone_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ZoneId
        {
            get => __pbn__ZoneId.GetValueOrDefault();
            set => __pbn__ZoneId = value;
        }
        public bool ShouldSerializeZoneId() => __pbn__ZoneId != null;
        public void ResetZoneId() => __pbn__ZoneId = null;
        private ulong? __pbn__ZoneId;

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] SimIds { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"active_sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ActiveSimId
        {
            get => __pbn__ActiveSimId.GetValueOrDefault();
            set => __pbn__ActiveSimId = value;
        }
        public bool ShouldSerializeActiveSimId() => __pbn__ActiveSimId != null;
        public void ResetActiveSimId() => __pbn__ActiveSimId = null;
        private ulong? __pbn__ActiveSimId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CASAvailableZonesInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"zones")]
        public global::System.Collections.Generic.List<WorldZonesInfo> Zones { get; } = new global::System.Collections.Generic.List<WorldZonesInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WorldZonesInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedString defaultName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"zones")]
        public global::System.Collections.Generic.List<ZoneInfo> Zones { get; } = new global::System.Collections.Generic.List<ZoneInfo>();

        [global::ProtoBuf.ProtoMember(4)]
        public uint worldId
        {
            get => __pbn__worldId.GetValueOrDefault();
            set => __pbn__worldId = value;
        }
        public bool ShouldSerializeworldId() => __pbn__worldId != null;
        public void ResetworldId() => __pbn__worldId = null;
        private uint? __pbn__worldId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ZoneInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public ulong Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4)]
        public LocalizedString defaultName { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"world_id")]
        public uint WorldId
        {
            get => __pbn__WorldId.GetValueOrDefault();
            set => __pbn__WorldId = value;
        }
        public bool ShouldSerializeWorldId() => __pbn__WorldId != null;
        public void ResetWorldId() => __pbn__WorldId = null;
        private uint? __pbn__WorldId;

        [global::ProtoBuf.ProtoMember(7, Name = @"lot_description_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong LotDescriptionId
        {
            get => __pbn__LotDescriptionId.GetValueOrDefault();
            set => __pbn__LotDescriptionId = value;
        }
        public bool ShouldSerializeLotDescriptionId() => __pbn__LotDescriptionId != null;
        public void ResetLotDescriptionId() => __pbn__LotDescriptionId = null;
        private ulong? __pbn__LotDescriptionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InteractionProgressUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SimId
        {
            get => __pbn__SimId.GetValueOrDefault();
            set => __pbn__SimId = value;
        }
        public bool ShouldSerializeSimId() => __pbn__SimId != null;
        public void ResetSimId() => __pbn__SimId = null;
        private ulong? __pbn__SimId;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        public LocalizedString Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"percent")]
        public float Percent
        {
            get => __pbn__Percent.GetValueOrDefault();
            set => __pbn__Percent = value;
        }
        public bool ShouldSerializePercent() => __pbn__Percent != null;
        public void ResetPercent() => __pbn__Percent = null;
        private float? __pbn__Percent;

        [global::ProtoBuf.ProtoMember(4, Name = @"rate_change")]
        public float RateChange
        {
            get => __pbn__RateChange.GetValueOrDefault();
            set => __pbn__RateChange = value;
        }
        public bool ShouldSerializeRateChange() => __pbn__RateChange != null;
        public void ResetRateChange() => __pbn__RateChange = null;
        private float? __pbn__RateChange;

        [global::ProtoBuf.ProtoMember(5, Name = @"interaction_id")]
        public ulong InteractionId
        {
            get => __pbn__InteractionId.GetValueOrDefault();
            set => __pbn__InteractionId = value;
        }
        public bool ShouldSerializeInteractionId() => __pbn__InteractionId != null;
        public void ResetInteractionId() => __pbn__InteractionId = null;
        private ulong? __pbn__InteractionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimTransferRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"source_household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SourceHouseholdId
        {
            get => __pbn__SourceHouseholdId.GetValueOrDefault();
            set => __pbn__SourceHouseholdId = value;
        }
        public bool ShouldSerializeSourceHouseholdId() => __pbn__SourceHouseholdId != null;
        public void ResetSourceHouseholdId() => __pbn__SourceHouseholdId = null;
        private ulong? __pbn__SourceHouseholdId;

        [global::ProtoBuf.ProtoMember(2, Name = @"target_household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TargetHouseholdId
        {
            get => __pbn__TargetHouseholdId.GetValueOrDefault();
            set => __pbn__TargetHouseholdId = value;
        }
        public bool ShouldSerializeTargetHouseholdId() => __pbn__TargetHouseholdId != null;
        public void ResetTargetHouseholdId() => __pbn__TargetHouseholdId = null;
        private ulong? __pbn__TargetHouseholdId;

        [global::ProtoBuf.ProtoMember(3, Name = @"active_sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ActiveSimId
        {
            get => __pbn__ActiveSimId.GetValueOrDefault();
            set => __pbn__ActiveSimId = value;
        }
        public bool ShouldSerializeActiveSimId() => __pbn__ActiveSimId != null;
        public void ResetActiveSimId() => __pbn__ActiveSimId = null;
        private ulong? __pbn__ActiveSimId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PhoneNotificationUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"interaction_ids")]
        public ulong[] InteractionIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_id", IsRequired = true)]
        public ulong SimId { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
