// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: MoveInMoveOut.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveInData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"furnished")]
        public bool Furnished
        {
            get => __pbn__Furnished.GetValueOrDefault();
            set => __pbn__Furnished = value;
        }
        public bool ShouldSerializeFurnished() => __pbn__Furnished != null;
        public void ResetFurnished() => __pbn__Furnished = null;
        private bool? __pbn__Furnished;

        [global::ProtoBuf.ProtoMember(2, Name = @"empty_lot")]
        public bool EmptyLot
        {
            get => __pbn__EmptyLot.GetValueOrDefault();
            set => __pbn__EmptyLot = value;
        }
        public bool ShouldSerializeEmptyLot() => __pbn__EmptyLot != null;
        public void ResetEmptyLot() => __pbn__EmptyLot = null;
        private bool? __pbn__EmptyLot;

        [global::ProtoBuf.ProtoMember(3, Name = @"household_id")]
        public ulong HouseholdId
        {
            get => __pbn__HouseholdId.GetValueOrDefault();
            set => __pbn__HouseholdId = value;
        }
        public bool ShouldSerializeHouseholdId() => __pbn__HouseholdId != null;
        public void ResetHouseholdId() => __pbn__HouseholdId = null;
        private ulong? __pbn__HouseholdId;

        [global::ProtoBuf.ProtoMember(6, Name = @"delta_funds")]
        public long DeltaFunds
        {
            get => __pbn__DeltaFunds.GetValueOrDefault();
            set => __pbn__DeltaFunds = value;
        }
        public bool ShouldSerializeDeltaFunds() => __pbn__DeltaFunds != null;
        public void ResetDeltaFunds() => __pbn__DeltaFunds = null;
        private long? __pbn__DeltaFunds;

        [global::ProtoBuf.ProtoMember(7, Name = @"zone_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ZoneName
        {
            get => __pbn__ZoneName ?? "";
            set => __pbn__ZoneName = value;
        }
        public bool ShouldSerializeZoneName() => __pbn__ZoneName != null;
        public void ResetZoneName() => __pbn__ZoneName = null;
        private string __pbn__ZoneName;

        [global::ProtoBuf.ProtoMember(8, Name = @"purchase_without_moving")]
        public bool PurchaseWithoutMoving
        {
            get => __pbn__PurchaseWithoutMoving.GetValueOrDefault();
            set => __pbn__PurchaseWithoutMoving = value;
        }
        public bool ShouldSerializePurchaseWithoutMoving() => __pbn__PurchaseWithoutMoving != null;
        public void ResetPurchaseWithoutMoving() => __pbn__PurchaseWithoutMoving = null;
        private bool? __pbn__PurchaseWithoutMoving;

        [global::ProtoBuf.ProtoMember(9, Name = @"new_venue_type", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong NewVenueType
        {
            get => __pbn__NewVenueType.GetValueOrDefault();
            set => __pbn__NewVenueType = value;
        }
        public bool ShouldSerializeNewVenueType() => __pbn__NewVenueType != null;
        public void ResetNewVenueType() => __pbn__NewVenueType = null;
        private ulong? __pbn__NewVenueType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveOutData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sell_furniture")]
        public bool SellFurniture
        {
            get => __pbn__SellFurniture.GetValueOrDefault();
            set => __pbn__SellFurniture = value;
        }
        public bool ShouldSerializeSellFurniture() => __pbn__SellFurniture != null;
        public void ResetSellFurniture() => __pbn__SellFurniture = null;
        private bool? __pbn__SellFurniture;

        [global::ProtoBuf.ProtoMember(2, Name = @"delta_funds")]
        public long DeltaFunds
        {
            get => __pbn__DeltaFunds.GetValueOrDefault();
            set => __pbn__DeltaFunds = value;
        }
        public bool ShouldSerializeDeltaFunds() => __pbn__DeltaFunds != null;
        public void ResetDeltaFunds() => __pbn__DeltaFunds = null;
        private long? __pbn__DeltaFunds;

        [global::ProtoBuf.ProtoMember(3, Name = @"sell_without_moving")]
        public bool SellWithoutMoving
        {
            get => __pbn__SellWithoutMoving.GetValueOrDefault();
            set => __pbn__SellWithoutMoving = value;
        }
        public bool ShouldSerializeSellWithoutMoving() => __pbn__SellWithoutMoving != null;
        public void ResetSellWithoutMoving() => __pbn__SellWithoutMoving = null;
        private bool? __pbn__SellWithoutMoving;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveInMoveOutData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"zone_src")]
        public ulong ZoneSrc
        {
            get => __pbn__ZoneSrc.GetValueOrDefault();
            set => __pbn__ZoneSrc = value;
        }
        public bool ShouldSerializeZoneSrc() => __pbn__ZoneSrc != null;
        public void ResetZoneSrc() => __pbn__ZoneSrc = null;
        private ulong? __pbn__ZoneSrc;

        [global::ProtoBuf.ProtoMember(2, Name = @"zone_dst")]
        public ulong ZoneDst
        {
            get => __pbn__ZoneDst.GetValueOrDefault();
            set => __pbn__ZoneDst = value;
        }
        public bool ShouldSerializeZoneDst() => __pbn__ZoneDst != null;
        public void ResetZoneDst() => __pbn__ZoneDst = null;
        private ulong? __pbn__ZoneDst;

        [global::ProtoBuf.ProtoMember(3, Name = @"move_in_data")]
        public MoveInData MoveInData { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"move_out_data_src")]
        public MoveOutData MoveOutDataSrc { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"move_out_data_dst")]
        public MoveOutData MoveOutDataDst { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"households_to_update", IsPacked = true)]
        public ulong[] HouseholdsToUpdates { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"travel_groups_to_update", IsPacked = true)]
        public ulong[] TravelGroupsToUpdates { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"retail_lots_to_update", IsPacked = true)]
        public ulong[] RetailLotsToUpdates { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"notify_gameplay")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool NotifyGameplay
        {
            get => __pbn__NotifyGameplay ?? false;
            set => __pbn__NotifyGameplay = value;
        }
        public bool ShouldSerializeNotifyGameplay() => __pbn__NotifyGameplay != null;
        public void ResetNotifyGameplay() => __pbn__NotifyGameplay = null;
        private bool? __pbn__NotifyGameplay;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
