// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: MTXCatalog.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Product : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"offerid", IsRequired = true)]
        public string Offerid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"children", IsPacked = true)]
        public ulong[] Childrens { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"instances")]
        public global::System.Collections.Generic.List<ResourceKey> Instances { get; } = new global::System.Collections.Generic.List<ResourceKey>();

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(6, Name = @"countries")]
        public global::System.Collections.Generic.List<Country> Countries { get; } = new global::System.Collections.Generic.List<Country>();

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public bool isBundle { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(BundleContainment.Loose)]
        public BundleContainment containmentType
        {
            get => __pbn__containmentType ?? BundleContainment.Loose;
            set => __pbn__containmentType = value;
        }
        public bool ShouldSerializecontainmentType() => __pbn__containmentType != null;
        public void ResetcontainmentType() => __pbn__containmentType = null;
        private BundleContainment? __pbn__containmentType;

        [global::ProtoBuf.ProtoMember(9, IsPacked = true)]
        public ulong[] childProductIds { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int bundlePriority
        {
            get => __pbn__bundlePriority.GetValueOrDefault();
            set => __pbn__bundlePriority = value;
        }
        public bool ShouldSerializebundlePriority() => __pbn__bundlePriority != null;
        public void ResetbundlePriority() => __pbn__bundlePriority = null;
        private int? __pbn__bundlePriority;

        [global::ProtoBuf.ProtoMember(11)]
        public uint keyNameHash
        {
            get => __pbn__keyNameHash.GetValueOrDefault();
            set => __pbn__keyNameHash = value;
        }
        public bool ShouldSerializekeyNameHash() => __pbn__keyNameHash != null;
        public void ResetkeyNameHash() => __pbn__keyNameHash = null;
        private uint? __pbn__keyNameHash;

        [global::ProtoBuf.ProtoMember(12)]
        public uint keyDescriptionHash
        {
            get => __pbn__keyDescriptionHash.GetValueOrDefault();
            set => __pbn__keyDescriptionHash = value;
        }
        public bool ShouldSerializekeyDescriptionHash() => __pbn__keyDescriptionHash != null;
        public void ResetkeyDescriptionHash() => __pbn__keyDescriptionHash = null;
        private uint? __pbn__keyDescriptionHash;

        [global::ProtoBuf.ProtoMember(13)]
        public uint keyUpsellDescriptionHash
        {
            get => __pbn__keyUpsellDescriptionHash.GetValueOrDefault();
            set => __pbn__keyUpsellDescriptionHash = value;
        }
        public bool ShouldSerializekeyUpsellDescriptionHash() => __pbn__keyUpsellDescriptionHash != null;
        public void ResetkeyUpsellDescriptionHash() => __pbn__keyUpsellDescriptionHash = null;
        private uint? __pbn__keyUpsellDescriptionHash;

        [global::ProtoBuf.ProtoMember(14)]
        public ulong thumbnailResourceInstanceIdHash
        {
            get => __pbn__thumbnailResourceInstanceIdHash.GetValueOrDefault();
            set => __pbn__thumbnailResourceInstanceIdHash = value;
        }
        public bool ShouldSerializethumbnailResourceInstanceIdHash() => __pbn__thumbnailResourceInstanceIdHash != null;
        public void ResetthumbnailResourceInstanceIdHash() => __pbn__thumbnailResourceInstanceIdHash = null;
        private ulong? __pbn__thumbnailResourceInstanceIdHash;

        [global::ProtoBuf.ProtoMember(15)]
        public bool hiddenInCatalog
        {
            get => __pbn__hiddenInCatalog.GetValueOrDefault();
            set => __pbn__hiddenInCatalog = value;
        }
        public bool ShouldSerializehiddenInCatalog() => __pbn__hiddenInCatalog != null;
        public void ResethiddenInCatalog() => __pbn__hiddenInCatalog = null;
        private bool? __pbn__hiddenInCatalog;

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool isPurchasable
        {
            get => __pbn__isPurchasable ?? true;
            set => __pbn__isPurchasable = value;
        }
        public bool ShouldSerializeisPurchasable() => __pbn__isPurchasable != null;
        public void ResetisPurchasable() => __pbn__isPurchasable = null;
        private bool? __pbn__isPurchasable;

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue(400u)]
        public uint celebrationPriority
        {
            get => __pbn__celebrationPriority ?? 400u;
            set => __pbn__celebrationPriority = value;
        }
        public bool ShouldSerializecelebrationPriority() => __pbn__celebrationPriority != null;
        public void ResetcelebrationPriority() => __pbn__celebrationPriority = null;
        private uint? __pbn__celebrationPriority;

        [global::ProtoBuf.ProtoMember(18)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool localizedImages
        {
            get => __pbn__localizedImages ?? false;
            set => __pbn__localizedImages = value;
        }
        public bool ShouldSerializelocalizedImages() => __pbn__localizedImages != null;
        public void ResetlocalizedImages() => __pbn__localizedImages = null;
        private bool? __pbn__localizedImages;

        [global::ProtoBuf.ProtoMember(19, Name = @"show_variants")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool ShowVariants
        {
            get => __pbn__ShowVariants ?? false;
            set => __pbn__ShowVariants = value;
        }
        public bool ShouldSerializeShowVariants() => __pbn__ShowVariants != null;
        public void ResetShowVariants() => __pbn__ShowVariants = null;
        private bool? __pbn__ShowVariants;

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong keyImage
        {
            get => __pbn__keyImage ?? 0ul;
            set => __pbn__keyImage = value;
        }
        public bool ShouldSerializekeyImage() => __pbn__keyImage != null;
        public void ResetkeyImage() => __pbn__keyImage = null;
        private ulong? __pbn__keyImage;

        [global::ProtoBuf.ProtoMember(21)]
        [global::System.ComponentModel.DefaultValue(ProductType.Cas)]
        public ProductType productType
        {
            get => __pbn__productType ?? ProductType.Cas;
            set => __pbn__productType = value;
        }
        public bool ShouldSerializeproductType() => __pbn__productType != null;
        public void ResetproductType() => __pbn__productType = null;
        private ProductType? __pbn__productType;

        [global::ProtoBuf.ProtoMember(22)]
        [global::System.ComponentModel.DefaultValue("")]
        public string productInfoURL
        {
            get => __pbn__productInfoURL ?? "";
            set => __pbn__productInfoURL = value;
        }
        public bool ShouldSerializeproductInfoURL() => __pbn__productInfoURL != null;
        public void ResetproductInfoURL() => __pbn__productInfoURL = null;
        private string __pbn__productInfoURL;

        [global::ProtoBuf.ProtoMember(23)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool isAvailable
        {
            get => __pbn__isAvailable ?? true;
            set => __pbn__isAvailable = value;
        }
        public bool ShouldSerializeisAvailable() => __pbn__isAvailable != null;
        public void ResetisAvailable() => __pbn__isAvailable = null;
        private bool? __pbn__isAvailable;

        [global::ProtoBuf.ProtoMember(24)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool showInPackDetail
        {
            get => __pbn__showInPackDetail ?? true;
            set => __pbn__showInPackDetail = value;
        }
        public bool ShouldSerializeshowInPackDetail() => __pbn__showInPackDetail != null;
        public void ResetshowInPackDetail() => __pbn__showInPackDetail = null;
        private bool? __pbn__showInPackDetail;

        [global::ProtoBuf.ProtoMember(25)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int packId
        {
            get => __pbn__packId ?? -1;
            set => __pbn__packId = value;
        }
        public bool ShouldSerializepackId() => __pbn__packId != null;
        public void ResetpackId() => __pbn__packId = null;
        private int? __pbn__packId;

        [global::ProtoBuf.ProtoContract()]
        public enum BundleContainment
        {
            [global::ProtoBuf.ProtoEnum(Name = @"LOOSE")]
            Loose = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TIGHT")]
            Tight = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum ProductType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CAS")]
            Cas = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BB")]
            Bb = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GAMEPLAY")]
            Gameplay = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GENERIC_MTX")]
            GenericMtx = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"INVALID_MTX")]
            InvalidMtx = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OfferList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"offer_id")]
        public global::System.Collections.Generic.List<string> OfferIds { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Catalog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
        public ulong Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"products")]
        public global::System.Collections.Generic.List<Product> Products { get; } = new global::System.Collections.Generic.List<Product>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Country : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string countryCode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"prices")]
        public global::System.Collections.Generic.List<Price> Prices { get; } = new global::System.Collections.Generic.List<Price>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Price : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float price { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"currency", IsRequired = true)]
        public string Currency { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string currencyType { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string priceType { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong startDate
        {
            get => __pbn__startDate.GetValueOrDefault();
            set => __pbn__startDate = value;
        }
        public bool ShouldSerializestartDate() => __pbn__startDate != null;
        public void ResetstartDate() => __pbn__startDate = null;
        private ulong? __pbn__startDate;

        [global::ProtoBuf.ProtoMember(6)]
        public ulong endDate
        {
            get => __pbn__endDate.GetValueOrDefault();
            set => __pbn__endDate = value;
        }
        public bool ShouldSerializeendDate() => __pbn__endDate != null;
        public void ResetendDate() => __pbn__endDate = null;
        private ulong? __pbn__endDate;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ViewedEntitlements : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<EntitlementNotification> viewed_entitlements { get; } = new global::System.Collections.Generic.List<EntitlementNotification>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntitlementNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(1u)]
        public uint viewed_state
        {
            get => __pbn__viewed_state ?? 1u;
            set => __pbn__viewed_state = value;
        }
        public bool ShouldSerializeviewed_state() => __pbn__viewed_state != null;
        public void Resetviewed_state() => __pbn__viewed_state = null;
        private uint? __pbn__viewed_state;

        [global::ProtoBuf.ProtoMember(3, Name = @"product_id")]
        public ulong ProductId
        {
            get => __pbn__ProductId.GetValueOrDefault();
            set => __pbn__ProductId = value;
        }
        public bool ShouldSerializeProductId() => __pbn__ProductId != null;
        public void ResetProductId() => __pbn__ProductId = null;
        private ulong? __pbn__ProductId;

        [global::ProtoBuf.ProtoMember(4)]
        public uint trial_viewed_state
        {
            get => __pbn__trial_viewed_state.GetValueOrDefault();
            set => __pbn__trial_viewed_state = value;
        }
        public bool ShouldSerializetrial_viewed_state() => __pbn__trial_viewed_state != null;
        public void Resettrial_viewed_state() => __pbn__trial_viewed_state = null;
        private uint? __pbn__trial_viewed_state;

        [global::ProtoBuf.ProtoMember(5, Name = @"entitlement_id_at_trial_expiration_or_conversion")]
        public ulong EntitlementIdAtTrialExpirationOrConversion
        {
            get => __pbn__EntitlementIdAtTrialExpirationOrConversion.GetValueOrDefault();
            set => __pbn__EntitlementIdAtTrialExpirationOrConversion = value;
        }
        public bool ShouldSerializeEntitlementIdAtTrialExpirationOrConversion() => __pbn__EntitlementIdAtTrialExpirationOrConversion != null;
        public void ResetEntitlementIdAtTrialExpirationOrConversion() => __pbn__EntitlementIdAtTrialExpirationOrConversion = null;
        private ulong? __pbn__EntitlementIdAtTrialExpirationOrConversion;

        [global::ProtoBuf.ProtoContract()]
        public enum ViewedState
        {
            [global::ProtoBuf.ProtoEnum(Name = @"VIEWED_INVALID")]
            ViewedInvalid = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"VIEWED_NEW")]
            ViewedNew = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"VIEWED_CELEBRATED")]
            ViewedCelebrated = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"VIEWED_USED")]
            ViewedUsed = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"VIEWED_ALL")]
            ViewedAll = 255,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum TrialViewedStateMask
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_VIEWED_MASK_EXPIRED_TRIAL_OR_CONVERTED")]
            TrialViewedMaskExpiredTrialOrConverted = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_VIEWED_MASK_TRIALS_NOT_SUPPORTED")]
            TrialViewedMaskTrialsNotSupported = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum TrialViewedState
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_VIEWED_EXPIRED_TRIAL_OR_CONVERTED")]
            TrialViewedExpiredTrialOrConverted = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_VIEWED_TRIALS_NOT_SUPPORTED")]
            TrialViewedTrialsNotSupported = 2,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
