// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Outfits.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Persistence
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BodyTypesList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_types")]
        public uint[] BodyTypes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ColorShiftList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color_shift")]
        public ulong[] ColorShifts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ObjectIdsList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id")]
        public ulong[] ObjectIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LayerIdsList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"layer_id")]
        public uint[] LayerIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OutfitData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"outfit_id", IsRequired = true)]
        public ulong OutfitId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"category")]
        public uint Category
        {
            get => __pbn__Category.GetValueOrDefault();
            set => __pbn__Category = value;
        }
        public bool ShouldSerializeCategory() => __pbn__Category != null;
        public void ResetCategory() => __pbn__Category = null;
        private uint? __pbn__Category;

        [global::ProtoBuf.ProtoMember(5, Name = @"parts")]
        public global::EA.Sims4.IdList Parts { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"created")]
        public ulong Created
        {
            get => __pbn__Created.GetValueOrDefault();
            set => __pbn__Created = value;
        }
        public bool ShouldSerializeCreated() => __pbn__Created != null;
        public void ResetCreated() => __pbn__Created = null;
        private ulong? __pbn__Created;

        [global::ProtoBuf.ProtoMember(7, Name = @"body_types_list")]
        public BodyTypesList BodyTypesList { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"match_hair_style")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool MatchHairStyle
        {
            get => __pbn__MatchHairStyle ?? false;
            set => __pbn__MatchHairStyle = value;
        }
        public bool ShouldSerializeMatchHairStyle() => __pbn__MatchHairStyle != null;
        public void ResetMatchHairStyle() => __pbn__MatchHairStyle = null;
        private bool? __pbn__MatchHairStyle;

        [global::ProtoBuf.ProtoMember(10, Name = @"outfit_flags")]
        public ulong OutfitFlags
        {
            get => __pbn__OutfitFlags.GetValueOrDefault();
            set => __pbn__OutfitFlags = value;
        }
        public bool ShouldSerializeOutfitFlags() => __pbn__OutfitFlags != null;
        public void ResetOutfitFlags() => __pbn__OutfitFlags = null;
        private ulong? __pbn__OutfitFlags;

        [global::ProtoBuf.ProtoMember(11, Name = @"outfit_flags_high")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong OutfitFlagsHigh
        {
            get => __pbn__OutfitFlagsHigh ?? 0ul;
            set => __pbn__OutfitFlagsHigh = value;
        }
        public bool ShouldSerializeOutfitFlagsHigh() => __pbn__OutfitFlagsHigh != null;
        public void ResetOutfitFlagsHigh() => __pbn__OutfitFlagsHigh = null;
        private ulong? __pbn__OutfitFlagsHigh;

        [global::ProtoBuf.ProtoMember(12, Name = @"part_shifts")]
        public ColorShiftList PartShifts { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title
        {
            get => __pbn__Title ?? "";
            set => __pbn__Title = value;
        }
        public bool ShouldSerializeTitle() => __pbn__Title != null;
        public void ResetTitle() => __pbn__Title = null;
        private string __pbn__Title;

        [global::ProtoBuf.ProtoMember(14, Name = @"object_ids")]
        public ObjectIdsList ObjectIds { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"layer_ids")]
        public LayerIdsList LayerIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OutfitList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"outfits")]
        public global::System.Collections.Generic.List<OutfitData> Outfits { get; } = new global::System.Collections.Generic.List<OutfitData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PartData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"body_type", IsRequired = true)]
        public uint BodyType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"color_shift")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "4611686018427387904")]
        public ulong ColorShift
        {
            get => __pbn__ColorShift ?? 4611686018427387904ul;
            set => __pbn__ColorShift = value;
        }
        public bool ShouldSerializeColorShift() => __pbn__ColorShift != null;
        public void ResetColorShift() => __pbn__ColorShift = null;
        private ulong? __pbn__ColorShift;

        [global::ProtoBuf.ProtoMember(4, Name = @"object_id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong ObjectId
        {
            get => __pbn__ObjectId ?? 0ul;
            set => __pbn__ObjectId = value;
        }
        public bool ShouldSerializeObjectId() => __pbn__ObjectId != null;
        public void ResetObjectId() => __pbn__ObjectId = null;
        private ulong? __pbn__ObjectId;

        [global::ProtoBuf.ProtoMember(5, Name = @"layer_id")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint LayerId
        {
            get => __pbn__LayerId ?? 0u;
            set => __pbn__LayerId = value;
        }
        public bool ShouldSerializeLayerId() => __pbn__LayerId != null;
        public void ResetLayerId() => __pbn__LayerId = null;
        private uint? __pbn__LayerId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PartDataList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"parts")]
        public global::System.Collections.Generic.List<PartData> Parts { get; } = new global::System.Collections.Generic.List<PartData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GeneticData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sculpts_and_mods_attr")]
        public byte[] SculptsAndModsAttr
        {
            get => __pbn__SculptsAndModsAttr;
            set => __pbn__SculptsAndModsAttr = value;
        }
        public bool ShouldSerializeSculptsAndModsAttr() => __pbn__SculptsAndModsAttr != null;
        public void ResetSculptsAndModsAttr() => __pbn__SculptsAndModsAttr = null;
        private byte[] __pbn__SculptsAndModsAttr;

        [global::ProtoBuf.ProtoMember(2, Name = @"physique")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Physique
        {
            get => __pbn__Physique ?? "";
            set => __pbn__Physique = value;
        }
        public bool ShouldSerializePhysique() => __pbn__Physique != null;
        public void ResetPhysique() => __pbn__Physique = null;
        private string __pbn__Physique;

        [global::ProtoBuf.ProtoMember(3, Name = @"voice_pitch")]
        public float VoicePitch
        {
            get => __pbn__VoicePitch.GetValueOrDefault();
            set => __pbn__VoicePitch = value;
        }
        public bool ShouldSerializeVoicePitch() => __pbn__VoicePitch != null;
        public void ResetVoicePitch() => __pbn__VoicePitch = null;
        private float? __pbn__VoicePitch;

        [global::ProtoBuf.ProtoMember(4, Name = @"voice_actor")]
        public uint VoiceActor
        {
            get => __pbn__VoiceActor.GetValueOrDefault();
            set => __pbn__VoiceActor = value;
        }
        public bool ShouldSerializeVoiceActor() => __pbn__VoiceActor != null;
        public void ResetVoiceActor() => __pbn__VoiceActor = null;
        private uint? __pbn__VoiceActor;

        [global::ProtoBuf.ProtoMember(5, Name = @"parts_list")]
        public PartDataList PartsList { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"growth_parts_list")]
        public PartDataList GrowthPartsList { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeltLayerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"layer_id")]
        public ulong LayerId
        {
            get => __pbn__LayerId.GetValueOrDefault();
            set => __pbn__LayerId = value;
        }
        public bool ShouldSerializeLayerId() => __pbn__LayerId != null;
        public void ResetLayerId() => __pbn__LayerId = null;
        private ulong? __pbn__LayerId;

        [global::ProtoBuf.ProtoMember(2, Name = @"color")]
        public uint Color
        {
            get => __pbn__Color.GetValueOrDefault();
            set => __pbn__Color = value;
        }
        public bool ShouldSerializeColor() => __pbn__Color != null;
        public void ResetColor() => __pbn__Color = null;
        private uint? __pbn__Color;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeltLayerDataList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"layers")]
        public global::System.Collections.Generic.List<PeltLayerData> Layers { get; } = new global::System.Collections.Generic.List<PeltLayerData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimPartCustomTattooData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_type", IsRequired = true)]
        public uint BodyType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"texture_id", IsRequired = true)]
        public ulong TextureId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimPartCreatorData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_type")]
        public uint BodyType
        {
            get => __pbn__BodyType.GetValueOrDefault();
            set => __pbn__BodyType = value;
        }
        public bool ShouldSerializeBodyType() => __pbn__BodyType != null;
        public void ResetBodyType() => __pbn__BodyType = null;
        private uint? __pbn__BodyType;

        [global::ProtoBuf.ProtoMember(2, Name = @"creator_uuid")]
        public byte[] CreatorUuid
        {
            get => __pbn__CreatorUuid;
            set => __pbn__CreatorUuid = value;
        }
        public bool ShouldSerializeCreatorUuid() => __pbn__CreatorUuid != null;
        public void ResetCreatorUuid() => __pbn__CreatorUuid = null;
        private byte[] __pbn__CreatorUuid;

        [global::ProtoBuf.ProtoMember(3, Name = @"creator_id")]
        public ulong CreatorId
        {
            get => __pbn__CreatorId.GetValueOrDefault();
            set => __pbn__CreatorId = value;
        }
        public bool ShouldSerializeCreatorId() => __pbn__CreatorId != null;
        public void ResetCreatorId() => __pbn__CreatorId = null;
        private ulong? __pbn__CreatorId;

        [global::ProtoBuf.ProtoMember(4, Name = @"creator_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CreatorName
        {
            get => __pbn__CreatorName ?? "";
            set => __pbn__CreatorName = value;
        }
        public bool ShouldSerializeCreatorName() => __pbn__CreatorName != null;
        public void ResetCreatorName() => __pbn__CreatorName = null;
        private string __pbn__CreatorName;

        [global::ProtoBuf.ProtoMember(5, Name = @"creator_platform")]
        [global::System.ComponentModel.DefaultValue(global::EA.Sims4.Network.ExchangeItemPlatform.ExchangePlatformUnknown)]
        public global::EA.Sims4.Network.ExchangeItemPlatform CreatorPlatform
        {
            get => __pbn__CreatorPlatform ?? global::EA.Sims4.Network.ExchangeItemPlatform.ExchangePlatformUnknown;
            set => __pbn__CreatorPlatform = value;
        }
        public bool ShouldSerializeCreatorPlatform() => __pbn__CreatorPlatform != null;
        public void ResetCreatorPlatform() => __pbn__CreatorPlatform = null;
        private global::EA.Sims4.Network.ExchangeItemPlatform? __pbn__CreatorPlatform;

        [global::ProtoBuf.ProtoMember(6, Name = @"creator_platform_id")]
        public ulong CreatorPlatformId
        {
            get => __pbn__CreatorPlatformId.GetValueOrDefault();
            set => __pbn__CreatorPlatformId = value;
        }
        public bool ShouldSerializeCreatorPlatformId() => __pbn__CreatorPlatformId != null;
        public void ResetCreatorPlatformId() => __pbn__CreatorPlatformId = null;
        private ulong? __pbn__CreatorPlatformId;

        [global::ProtoBuf.ProtoMember(7, Name = @"creator_platform_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CreatorPlatformName
        {
            get => __pbn__CreatorPlatformName ?? "";
            set => __pbn__CreatorPlatformName = value;
        }
        public bool ShouldSerializeCreatorPlatformName() => __pbn__CreatorPlatformName != null;
        public void ResetCreatorPlatformName() => __pbn__CreatorPlatformName = null;
        private string __pbn__CreatorPlatformName;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
