// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PersistenceControl.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistenceControlMessageData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot_meta_data")]
        public global::System.Collections.Generic.List<global::EA.Sims4.Persistence.SaveGameSlotMetaData> SlotMetaDatas { get; } = new global::System.Collections.Generic.List<global::EA.Sims4.Persistence.SaveGameSlotMetaData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"save_data")]
        public global::EA.Sims4.Persistence.SaveGameData SaveData { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"zone_object_data")]
        public global::System.Collections.Generic.List<global::EA.Sims4.Persistence.ZoneObjectData> ZoneObjectDatas { get; } = new global::System.Collections.Generic.List<global::EA.Sims4.Persistence.ZoneObjectData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"errors")]
        public global::EA.Sims4.Persistence.FeedbackContext Errors { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"scratch_path")]
        public global::System.Collections.Generic.List<global::EA.Sims4.Persistence.ZoneObjectDataScratchPair> ScratchPaths { get; } = new global::System.Collections.Generic.List<global::EA.Sims4.Persistence.ZoneObjectDataScratchPair>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistenceControlMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"callback")]
        public ulong Callback
        {
            get => __pbn__Callback.GetValueOrDefault();
            set => __pbn__Callback = value;
        }
        public bool ShouldSerializeCallback() => __pbn__Callback != null;
        public void ResetCallback() => __pbn__Callback = null;
        private ulong? __pbn__Callback;

        [global::ProtoBuf.ProtoMember(2, Name = @"userdata")]
        public ulong Userdata
        {
            get => __pbn__Userdata.GetValueOrDefault();
            set => __pbn__Userdata = value;
        }
        public bool ShouldSerializeUserdata() => __pbn__Userdata != null;
        public void ResetUserdata() => __pbn__Userdata = null;
        private ulong? __pbn__Userdata;

        [global::ProtoBuf.ProtoMember(4, Name = @"opcode")]
        [global::System.ComponentModel.DefaultValue(PersistenceOpTypes.PersistenceOpLoadSlots)]
        public PersistenceOpTypes Opcode
        {
            get => __pbn__Opcode ?? PersistenceOpTypes.PersistenceOpLoadSlots;
            set => __pbn__Opcode = value;
        }
        public bool ShouldSerializeOpcode() => __pbn__Opcode != null;
        public void ResetOpcode() => __pbn__Opcode = null;
        private PersistenceOpTypes? __pbn__Opcode;

        [global::ProtoBuf.ProtoMember(5, Name = @"data")]
        public PersistenceControlMessageData Data { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
