// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ResourceKey.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public uint Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private uint? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"group")]
        public uint Group
        {
            get => __pbn__Group.GetValueOrDefault();
            set => __pbn__Group = value;
        }
        public bool ShouldSerializeGroup() => __pbn__Group != null;
        public void ResetGroup() => __pbn__Group = null;
        private uint? __pbn__Group;

        [global::ProtoBuf.ProtoMember(3, Name = @"instance")]
        public ulong Instance
        {
            get => __pbn__Instance.GetValueOrDefault();
            set => __pbn__Instance = value;
        }
        public bool ShouldSerializeInstance() => __pbn__Instance != null;
        public void ResetInstance() => __pbn__Instance = null;
        private ulong? __pbn__Instance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceKeyList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resource_keys")]
        public global::System.Collections.Generic.List<ResourceKey> ResourceKeys { get; } = new global::System.Collections.Generic.List<ResourceKey>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
