// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Restaurant.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RecipeItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"recipe_id", IsRequired = true)]
        public ulong RecipeId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(ItemType.Normal)]
        public ItemType item_type
        {
            get => __pbn__item_type ?? ItemType.Normal;
            set => __pbn__item_type = value;
        }
        public bool ShouldSerializeitem_type() => __pbn__item_type != null;
        public void Resetitem_type() => __pbn__item_type = null;
        private ItemType? __pbn__item_type;

        [global::ProtoBuf.ProtoMember(3, Name = @"price_override")]
        public int PriceOverride
        {
            get => __pbn__PriceOverride.GetValueOrDefault();
            set => __pbn__PriceOverride = value;
        }
        public bool ShouldSerializePriceOverride() => __pbn__PriceOverride != null;
        public void ResetPriceOverride() => __pbn__PriceOverride = null;
        private int? __pbn__PriceOverride;

        [global::ProtoBuf.ProtoContract()]
        public enum ItemType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
            Normal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SPECIAL")]
            Special = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Course : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"items")]
        public global::System.Collections.Generic.List<RecipeItem> Items { get; } = new global::System.Collections.Generic.List<RecipeItem>();

        [global::ProtoBuf.ProtoMember(2, Name = @"course_tag")]
        public uint CourseTag
        {
            get => __pbn__CourseTag.GetValueOrDefault();
            set => __pbn__CourseTag = value;
        }
        public bool ShouldSerializeCourseTag() => __pbn__CourseTag != null;
        public void ResetCourseTag() => __pbn__CourseTag = null;
        private uint? __pbn__CourseTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Menu : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"courses")]
        public global::System.Collections.Generic.List<Course> Courses { get; } = new global::System.Collections.Generic.List<Course>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimOrders : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SimOrder> sim_orders { get; } = new global::System.Collections.Generic.List<SimOrder>();

        [global::ProtoBuf.ProtoMember(2, Name = @"meal_cost")]
        public uint MealCost
        {
            get => __pbn__MealCost.GetValueOrDefault();
            set => __pbn__MealCost = value;
        }
        public bool ShouldSerializeMealCost() => __pbn__MealCost != null;
        public void ResetMealCost() => __pbn__MealCost = null;
        private uint? __pbn__MealCost;

        [global::ProtoBuf.ProtoMember(3, Name = @"is_recommendation")]
        public bool IsRecommendation
        {
            get => __pbn__IsRecommendation.GetValueOrDefault();
            set => __pbn__IsRecommendation = value;
        }
        public bool ShouldSerializeIsRecommendation() => __pbn__IsRecommendation != null;
        public void ResetIsRecommendation() => __pbn__IsRecommendation = null;
        private bool? __pbn__IsRecommendation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimOrder : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", IsRequired = true)]
        public ulong SimId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"recipe_id")]
        public ulong RecipeId
        {
            get => __pbn__RecipeId.GetValueOrDefault();
            set => __pbn__RecipeId = value;
        }
        public bool ShouldSerializeRecipeId() => __pbn__RecipeId != null;
        public void ResetRecipeId() => __pbn__RecipeId = null;
        private ulong? __pbn__RecipeId;

        [global::ProtoBuf.ProtoMember(3, Name = @"locked")]
        public bool Locked
        {
            get => __pbn__Locked.GetValueOrDefault();
            set => __pbn__Locked = value;
        }
        public bool ShouldSerializeLocked() => __pbn__Locked != null;
        public void ResetLocked() => __pbn__Locked = null;
        private bool? __pbn__Locked;

        [global::ProtoBuf.ProtoMember(4, Name = @"course_tag")]
        public uint CourseTag
        {
            get => __pbn__CourseTag.GetValueOrDefault();
            set => __pbn__CourseTag = value;
        }
        public bool ShouldSerializeCourseTag() => __pbn__CourseTag != null;
        public void ResetCourseTag() => __pbn__CourseTag = null;
        private uint? __pbn__CourseTag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ShowMenu : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"menu", IsRequired = true)]
        public Menu Menu { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_orders")]
        public global::System.Collections.Generic.List<SimOrder> SimOrders { get; } = new global::System.Collections.Generic.List<SimOrder>();

        [global::ProtoBuf.ProtoMember(3, Name = @"sim_ids", IsPacked = true)]
        public ulong[] SimIds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"chef_order")]
        public bool ChefOrder
        {
            get => __pbn__ChefOrder.GetValueOrDefault();
            set => __pbn__ChefOrder = value;
        }
        public bool ShouldSerializeChefOrder() => __pbn__ChefOrder != null;
        public void ResetChefOrder() => __pbn__ChefOrder = null;
        private bool? __pbn__ChefOrder;

        [global::ProtoBuf.ProtoMember(5, Name = @"running_bill_total")]
        public uint RunningBillTotal
        {
            get => __pbn__RunningBillTotal.GetValueOrDefault();
            set => __pbn__RunningBillTotal = value;
        }
        public bool ShouldSerializeRunningBillTotal() => __pbn__RunningBillTotal != null;
        public void ResetRunningBillTotal() => __pbn__RunningBillTotal = null;
        private uint? __pbn__RunningBillTotal;

        [global::ProtoBuf.ProtoMember(6, Name = @"recommend_order")]
        public bool RecommendOrder
        {
            get => __pbn__RecommendOrder.GetValueOrDefault();
            set => __pbn__RecommendOrder = value;
        }
        public bool ShouldSerializeRecommendOrder() => __pbn__RecommendOrder != null;
        public void ResetRecommendOrder() => __pbn__RecommendOrder = null;
        private bool? __pbn__RecommendOrder;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Order : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_orders")]
        public global::System.Collections.Generic.List<SimOrder> SimOrders { get; } = new global::System.Collections.Generic.List<SimOrder>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RestaurantConfiguration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attire_id")]
        public uint AttireId
        {
            get => __pbn__AttireId.GetValueOrDefault();
            set => __pbn__AttireId = value;
        }
        public bool ShouldSerializeAttireId() => __pbn__AttireId != null;
        public void ResetAttireId() => __pbn__AttireId = null;
        private uint? __pbn__AttireId;

        [global::ProtoBuf.ProtoMember(2, Name = @"preset_id")]
        public ulong PresetId
        {
            get => __pbn__PresetId.GetValueOrDefault();
            set => __pbn__PresetId = value;
        }
        public bool ShouldSerializePresetId() => __pbn__PresetId != null;
        public void ResetPresetId() => __pbn__PresetId = null;
        private ulong? __pbn__PresetId;

        [global::ProtoBuf.ProtoMember(3, Name = @"custom_menu")]
        public Menu CustomMenu { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"outfits")]
        public global::System.Collections.Generic.List<CareerOutfit> Outfits { get; } = new global::System.Collections.Generic.List<CareerOutfit>();

        [global::ProtoBuf.ProtoContract()]
        public enum RestaurantOutfitType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MALE_CHEF")]
            MaleChef = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FEMALE_CHEF")]
            FemaleChef = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MALE_WAITER")]
            MaleWaiter = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"FEMALE_WAITER")]
            FemaleWaiter = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MALE_HOST")]
            MaleHost = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"FEMALE_HOST")]
            FemaleHost = 5,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
