// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: RestApi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RestControlMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nucleus_id")]
        public ulong NucleusId
        {
            get => __pbn__NucleusId.GetValueOrDefault();
            set => __pbn__NucleusId = value;
        }
        public bool ShouldSerializeNucleusId() => __pbn__NucleusId != null;
        public void ResetNucleusId() => __pbn__NucleusId = null;
        private ulong? __pbn__NucleusId;

        [global::ProtoBuf.ProtoMember(2, Name = @"ref")]
        public ulong Ref
        {
            get => __pbn__Ref.GetValueOrDefault();
            set => __pbn__Ref = value;
        }
        public bool ShouldSerializeRef() => __pbn__Ref != null;
        public void ResetRef() => __pbn__Ref = null;
        private ulong? __pbn__Ref;

        [global::ProtoBuf.ProtoMember(3, Name = @"persona")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Persona
        {
            get => __pbn__Persona ?? "";
            set => __pbn__Persona = value;
        }
        public bool ShouldSerializePersona() => __pbn__Persona != null;
        public void ResetPersona() => __pbn__Persona = null;
        private string __pbn__Persona;

        [global::ProtoBuf.ProtoMember(4, Name = @"social")]
        public SocialControlMessage Social { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"exchange")]
        public ExchangeControlMessage Exchange { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"error_message")]
        [global::System.ComponentModel.DefaultValue(RestApiErrorMessages.RestApiErrorSuccess)]
        public RestApiErrorMessages ErrorMessage
        {
            get => __pbn__ErrorMessage ?? RestApiErrorMessages.RestApiErrorSuccess;
            set => __pbn__ErrorMessage = value;
        }
        public bool ShouldSerializeErrorMessage() => __pbn__ErrorMessage != null;
        public void ResetErrorMessage() => __pbn__ErrorMessage = null;
        private RestApiErrorMessages? __pbn__ErrorMessage;

        [global::ProtoBuf.ProtoMember(7, Name = @"access_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccessToken
        {
            get => __pbn__AccessToken ?? "";
            set => __pbn__AccessToken = value;
        }
        public bool ShouldSerializeAccessToken() => __pbn__AccessToken != null;
        public void ResetAccessToken() => __pbn__AccessToken = null;
        private string __pbn__AccessToken;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
