// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Roommates.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Persistence
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RoommateLeaveReasonInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reason")]
        public ulong Reason
        {
            get => __pbn__Reason.GetValueOrDefault();
            set => __pbn__Reason = value;
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private ulong? __pbn__Reason;

        [global::ProtoBuf.ProtoMember(2, Name = @"total_time")]
        public ulong TotalTime
        {
            get => __pbn__TotalTime.GetValueOrDefault();
            set => __pbn__TotalTime = value;
        }
        public bool ShouldSerializeTotalTime() => __pbn__TotalTime != null;
        public void ResetTotalTime() => __pbn__TotalTime = null;
        private ulong? __pbn__TotalTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"been_warned")]
        public bool BeenWarned
        {
            get => __pbn__BeenWarned.GetValueOrDefault();
            set => __pbn__BeenWarned = value;
        }
        public bool ShouldSerializeBeenWarned() => __pbn__BeenWarned != null;
        public void ResetBeenWarned() => __pbn__BeenWarned = null;
        private bool? __pbn__BeenWarned;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoommateInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SimId
        {
            get => __pbn__SimId.GetValueOrDefault();
            set => __pbn__SimId = value;
        }
        public bool ShouldSerializeSimId() => __pbn__SimId != null;
        public void ResetSimId() => __pbn__SimId = null;
        private ulong? __pbn__SimId;

        [global::ProtoBuf.ProtoMember(2, Name = @"bed_id")]
        public ulong BedId
        {
            get => __pbn__BedId.GetValueOrDefault();
            set => __pbn__BedId = value;
        }
        public bool ShouldSerializeBedId() => __pbn__BedId != null;
        public void ResetBedId() => __pbn__BedId = null;
        private ulong? __pbn__BedId;

        [global::ProtoBuf.ProtoMember(3, Name = @"decoration_ids", IsPacked = true)]
        public ulong[] DecorationIds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"leave_reason_infos")]
        public global::System.Collections.Generic.List<RoommateLeaveReasonInfo> LeaveReasonInfos { get; } = new global::System.Collections.Generic.List<RoommateLeaveReasonInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoommateBlacklistSimInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SimId
        {
            get => __pbn__SimId.GetValueOrDefault();
            set => __pbn__SimId = value;
        }
        public bool ShouldSerializeSimId() => __pbn__SimId != null;
        public void ResetSimId() => __pbn__SimId = null;
        private ulong? __pbn__SimId;

        [global::ProtoBuf.ProtoMember(2, Name = @"time_left")]
        public ulong TimeLeft
        {
            get => __pbn__TimeLeft.GetValueOrDefault();
            set => __pbn__TimeLeft = value;
        }
        public bool ShouldSerializeTimeLeft() => __pbn__TimeLeft != null;
        public void ResetTimeLeft() => __pbn__TimeLeft = null;
        private ulong? __pbn__TimeLeft;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoommateAdInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong HouseholdId
        {
            get => __pbn__HouseholdId.GetValueOrDefault();
            set => __pbn__HouseholdId = value;
        }
        public bool ShouldSerializeHouseholdId() => __pbn__HouseholdId != null;
        public void ResetHouseholdId() => __pbn__HouseholdId = null;
        private ulong? __pbn__HouseholdId;

        [global::ProtoBuf.ProtoMember(2, Name = @"pending_interview_alarms", IsPacked = true)]
        public ulong[] PendingInterviewAlarms { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"interviewee_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsPacked = true)]
        public ulong[] IntervieweeIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoommateData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"zone_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ZoneId
        {
            get => __pbn__ZoneId.GetValueOrDefault();
            set => __pbn__ZoneId = value;
        }
        public bool ShouldSerializeZoneId() => __pbn__ZoneId != null;
        public void ResetZoneId() => __pbn__ZoneId = null;
        private ulong? __pbn__ZoneId;

        [global::ProtoBuf.ProtoMember(2, Name = @"household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong HouseholdId
        {
            get => __pbn__HouseholdId.GetValueOrDefault();
            set => __pbn__HouseholdId = value;
        }
        public bool ShouldSerializeHouseholdId() => __pbn__HouseholdId != null;
        public void ResetHouseholdId() => __pbn__HouseholdId = null;
        private ulong? __pbn__HouseholdId;

        [global::ProtoBuf.ProtoMember(4, Name = @"roommate_infos")]
        public global::System.Collections.Generic.List<RoommateInfo> RoommateInfos { get; } = new global::System.Collections.Generic.List<RoommateInfo>();

        [global::ProtoBuf.ProtoMember(5, Name = @"blacklist_infos")]
        public global::System.Collections.Generic.List<RoommateBlacklistSimInfo> BlacklistInfos { get; } = new global::System.Collections.Generic.List<RoommateBlacklistSimInfo>();

        [global::ProtoBuf.ProtoMember(7, Name = @"pending_destroy_decoration_ids", IsPacked = true)]
        public ulong[] PendingDestroyDecorationIds { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"locked_out_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong LockedOutId
        {
            get => __pbn__LockedOutId.GetValueOrDefault();
            set => __pbn__LockedOutId = value;
        }
        public bool ShouldSerializeLockedOutId() => __pbn__LockedOutId != null;
        public void ResetLockedOutId() => __pbn__LockedOutId = null;
        private ulong? __pbn__LockedOutId;

        [global::ProtoBuf.ProtoMember(9, Name = @"available_beds")]
        public int AvailableBeds
        {
            get => __pbn__AvailableBeds.GetValueOrDefault();
            set => __pbn__AvailableBeds = value;
        }
        public bool ShouldSerializeAvailableBeds() => __pbn__AvailableBeds != null;
        public void ResetAvailableBeds() => __pbn__AvailableBeds = null;
        private int? __pbn__AvailableBeds;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistableRoommateService : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"roommate_datas")]
        public global::System.Collections.Generic.List<RoommateData> RoommateDatas { get; } = new global::System.Collections.Generic.List<RoommateData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ad_info")]
        public RoommateAdInfo AdInfo { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
