// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Routing.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SurfaceId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"primary_id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong PrimaryId
        {
            get => __pbn__PrimaryId ?? 0ul;
            set => __pbn__PrimaryId = value;
        }
        public bool ShouldSerializePrimaryId() => __pbn__PrimaryId != null;
        public void ResetPrimaryId() => __pbn__PrimaryId = null;
        private ulong? __pbn__PrimaryId;

        [global::ProtoBuf.ProtoMember(2, Name = @"secondary_id")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int SecondaryId
        {
            get => __pbn__SecondaryId ?? 0;
            set => __pbn__SecondaryId = value;
        }
        public bool ShouldSerializeSecondaryId() => __pbn__SecondaryId != null;
        public void ResetSecondaryId() => __pbn__SecondaryId = null;
        private int? __pbn__SecondaryId;

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(1u)]
        public uint Type
        {
            get => __pbn__Type ?? 1u;
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private uint? __pbn__Type;

        [global::ProtoBuf.ProtoMember(4, Name = @"routable_surface_height")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int RoutableSurfaceHeight
        {
            get => __pbn__RoutableSurfaceHeight ?? 0;
            set => __pbn__RoutableSurfaceHeight = value;
        }
        public bool ShouldSerializeRoutableSurfaceHeight() => __pbn__RoutableSurfaceHeight != null;
        public void ResetRoutableSurfaceHeight() => __pbn__RoutableSurfaceHeight = null;
        private int? __pbn__RoutableSurfaceHeight;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouteNodeData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public DataType Type { get; set; } = DataType.DataStairs;

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

        [global::ProtoBuf.ProtoMember(3, Name = @"do_stop_transition")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool DoStopTransition
        {
            get => __pbn__DoStopTransition ?? false;
            set => __pbn__DoStopTransition = value;
        }
        public bool ShouldSerializeDoStopTransition() => __pbn__DoStopTransition != null;
        public void ResetDoStopTransition() => __pbn__DoStopTransition = null;
        private bool? __pbn__DoStopTransition;

        [global::ProtoBuf.ProtoMember(4, Name = @"do_start_transition")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool DoStartTransition
        {
            get => __pbn__DoStartTransition ?? false;
            set => __pbn__DoStartTransition = value;
        }
        public bool ShouldSerializeDoStartTransition() => __pbn__DoStartTransition != null;
        public void ResetDoStartTransition() => __pbn__DoStartTransition = null;
        private bool? __pbn__DoStartTransition;

        [global::ProtoBuf.ProtoContract()]
        public enum DataType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DATA_STAIRS")]
            DataStairs = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"DATA_ANIMATE")]
            DataAnimate = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"DATA_LADDER")]
            DataLadder = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouteStairsData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"traversing_up", IsRequired = true)]
        public bool TraversingUp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stair_count", IsRequired = true)]
        public uint StairCount { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"walkstyle")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Walkstyle
        {
            get => __pbn__Walkstyle ?? 0u;
            set => __pbn__Walkstyle = value;
        }
        public bool ShouldSerializeWalkstyle() => __pbn__Walkstyle != null;
        public void ResetWalkstyle() => __pbn__Walkstyle = null;
        private uint? __pbn__Walkstyle;

        [global::ProtoBuf.ProtoMember(4, Name = @"stairs_per_cycle")]
        [global::System.ComponentModel.DefaultValue(1u)]
        public uint StairsPerCycle
        {
            get => __pbn__StairsPerCycle ?? 1u;
            set => __pbn__StairsPerCycle = value;
        }
        public bool ShouldSerializeStairsPerCycle() => __pbn__StairsPerCycle != null;
        public void ResetStairsPerCycle() => __pbn__StairsPerCycle = null;
        private uint? __pbn__StairsPerCycle;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouteLadderData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"traversing_up", IsRequired = true)]
        public bool TraversingUp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"step_count", IsRequired = true)]
        public uint StepCount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(LadderType.LadderOcean)]
        public LadderType ladder_type
        {
            get => __pbn__ladder_type ?? LadderType.LadderOcean;
            set => __pbn__ladder_type = value;
        }
        public bool ShouldSerializeladder_type() => __pbn__ladder_type != null;
        public void Resetladder_type() => __pbn__ladder_type = null;
        private LadderType? __pbn__ladder_type;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(PortalAlignment.PaFront)]
        public PortalAlignment portal_alignment
        {
            get => __pbn__portal_alignment ?? PortalAlignment.PaFront;
            set => __pbn__portal_alignment = value;
        }
        public bool ShouldSerializeportal_alignment() => __pbn__portal_alignment != null;
        public void Resetportal_alignment() => __pbn__portal_alignment = null;
        private PortalAlignment? __pbn__portal_alignment;

        [global::ProtoBuf.ProtoContract()]
        public enum LadderType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"LADDER_OCEAN")]
            LadderOcean = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"LADDER_BUILD")]
            LadderBuild = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum PortalAlignment
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PA_FRONT")]
            PaFront = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PA_LEFT")]
            PaLeft = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PA_RIGHT")]
            PaRight = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouteAnimateData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"arb_data", IsRequired = true)]
        public byte[] ArbData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouteNode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"location", IsRequired = true)]
        public Transform Location { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public float Time { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"action")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Action
        {
            get => __pbn__Action ?? 0u;
            set => __pbn__Action = value;
        }
        public bool ShouldSerializeAction() => __pbn__Action != null;
        public void ResetAction() => __pbn__Action = null;
        private uint? __pbn__Action;

        [global::ProtoBuf.ProtoMember(4, Name = @"walkstyle")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Walkstyle
        {
            get => __pbn__Walkstyle ?? 0u;
            set => __pbn__Walkstyle = value;
        }
        public bool ShouldSerializeWalkstyle() => __pbn__Walkstyle != null;
        public void ResetWalkstyle() => __pbn__Walkstyle = null;
        private uint? __pbn__Walkstyle;

        [global::ProtoBuf.ProtoMember(5, Name = @"routing_surface_id")]
        public SurfaceId RoutingSurfaceId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"portal_object_id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong PortalObjectId
        {
            get => __pbn__PortalObjectId ?? 0ul;
            set => __pbn__PortalObjectId = value;
        }
        public bool ShouldSerializePortalObjectId() => __pbn__PortalObjectId != null;
        public void ResetPortalObjectId() => __pbn__PortalObjectId = null;
        private ulong? __pbn__PortalObjectId;

        [global::ProtoBuf.ProtoMember(7, Name = @"node_data")]
        public RouteNodeData NodeData { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"surface_object_id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong SurfaceObjectId
        {
            get => __pbn__SurfaceObjectId ?? 0ul;
            set => __pbn__SurfaceObjectId = value;
        }
        public bool ShouldSerializeSurfaceObjectId() => __pbn__SurfaceObjectId != null;
        public void ResetSurfaceObjectId() => __pbn__SurfaceObjectId = null;
        private ulong? __pbn__SurfaceObjectId;

        [global::ProtoBuf.ProtoMember(9, Name = @"is_procedural")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsProcedural
        {
            get => __pbn__IsProcedural ?? false;
            set => __pbn__IsProcedural = value;
        }
        public bool ShouldSerializeIsProcedural() => __pbn__IsProcedural != null;
        public void ResetIsProcedural() => __pbn__IsProcedural = null;
        private bool? __pbn__IsProcedural;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Location : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"transform")]
        public Transform Transform { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public int Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private int? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"parent_id")]
        public ulong ParentId
        {
            get => __pbn__ParentId.GetValueOrDefault();
            set => __pbn__ParentId = value;
        }
        public bool ShouldSerializeParentId() => __pbn__ParentId != null;
        public void ResetParentId() => __pbn__ParentId = null;
        private ulong? __pbn__ParentId;

        [global::ProtoBuf.ProtoMember(4, Name = @"joint_name_hash")]
        public uint JointNameHash
        {
            get => __pbn__JointNameHash.GetValueOrDefault();
            set => __pbn__JointNameHash = value;
        }
        public bool ShouldSerializeJointNameHash() => __pbn__JointNameHash != null;
        public void ResetJointNameHash() => __pbn__JointNameHash = null;
        private uint? __pbn__JointNameHash;

        [global::ProtoBuf.ProtoMember(5, Name = @"slot_hash")]
        public uint SlotHash
        {
            get => __pbn__SlotHash.GetValueOrDefault();
            set => __pbn__SlotHash = value;
        }
        public bool ShouldSerializeSlotHash() => __pbn__SlotHash != null;
        public void ResetSlotHash() => __pbn__SlotHash = null;
        private uint? __pbn__SlotHash;

        [global::ProtoBuf.ProtoMember(6, Name = @"surface_id")]
        public SurfaceId SurfaceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GoalPoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"location", IsRequired = true)]
        public Transform Location { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"weight")]
        [global::System.ComponentModel.DefaultValue(1f)]
        public float Weight
        {
            get => __pbn__Weight ?? 1f;
            set => __pbn__Weight = value;
        }
        public bool ShouldSerializeWeight() => __pbn__Weight != null;
        public void ResetWeight() => __pbn__Weight = null;
        private float? __pbn__Weight;

        [global::ProtoBuf.ProtoMember(3, Name = @"radius")]
        [global::System.ComponentModel.DefaultValue(0.123f)]
        public float Radius
        {
            get => __pbn__Radius ?? 0.123f;
            set => __pbn__Radius = value;
        }
        public bool ShouldSerializeRadius() => __pbn__Radius != null;
        public void ResetRadius() => __pbn__Radius = null;
        private float? __pbn__Radius;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoutePoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public Vector2 Pos { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoutePolygon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"points")]
        public global::System.Collections.Generic.List<RoutePoint> Points { get; } = new global::System.Collections.Generic.List<RoutePoint>();

        [global::ProtoBuf.ProtoMember(2, Name = @"routing_surface_id")]
        public SurfaceId RoutingSurfaceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoutePolygons : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"polygons")]
        public global::System.Collections.Generic.List<RoutePolygon> Polygons { get; } = new global::System.Collections.Generic.List<RoutePolygon>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouteEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong Id
        {
            get => __pbn__Id ?? 0ul;
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private ulong? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time", IsRequired = true)]
        public float Time { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float Duration
        {
            get => __pbn__Duration ?? 0f;
            set => __pbn__Duration = value;
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private float? __pbn__Duration;

        [global::ProtoBuf.ProtoMember(5, Name = @"tag")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong Tag
        {
            get => __pbn__Tag ?? 0ul;
            set => __pbn__Tag = value;
        }
        public bool ShouldSerializeTag() => __pbn__Tag != null;
        public void ResetTag() => __pbn__Tag = null;
        private ulong? __pbn__Tag;

        [global::ProtoBuf.ProtoMember(6, Name = @"skippable")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool Skippable
        {
            get => __pbn__Skippable ?? true;
            set => __pbn__Skippable = value;
        }
        public bool ShouldSerializeSkippable() => __pbn__Skippable != null;
        public void ResetSkippable() => __pbn__Skippable = null;
        private bool? __pbn__Skippable;

        [global::ProtoBuf.ProtoMember(7, Name = @"data")]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PORTAL_ENTER")]
            PortalEnter = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PORTAL_EXIT")]
            PortalExit = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PORTAL_CHANGE_OPACITY")]
            PortalChangeOpacity = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CONTROLLER_EVENT")]
            ControllerEvent = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"BARRIER_EVENT")]
            BarrierEvent = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PortalEnterEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"portal_object_id", IsRequired = true)]
        public ulong PortalObjectId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entering_front")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool EnteringFront
        {
            get => __pbn__EnteringFront ?? true;
            set => __pbn__EnteringFront = value;
        }
        public bool ShouldSerializeEnteringFront() => __pbn__EnteringFront != null;
        public void ResetEnteringFront() => __pbn__EnteringFront = null;
        private bool? __pbn__EnteringFront;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PortalExitEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"portal_object_id", IsRequired = true)]
        public ulong PortalObjectId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PortalChangeOpacityEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ObjectId
        {
            get => __pbn__ObjectId.GetValueOrDefault();
            set => __pbn__ObjectId = value;
        }
        public bool ShouldSerializeObjectId() => __pbn__ObjectId != null;
        public void ResetObjectId() => __pbn__ObjectId = null;
        private ulong? __pbn__ObjectId;

        [global::ProtoBuf.ProtoMember(2, Name = @"opacity")]
        public float Opacity
        {
            get => __pbn__Opacity.GetValueOrDefault();
            set => __pbn__Opacity = value;
        }
        public bool ShouldSerializeOpacity() => __pbn__Opacity != null;
        public void ResetOpacity() => __pbn__Opacity = null;
        private float? __pbn__Opacity;

        [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
        public float Duration
        {
            get => __pbn__Duration.GetValueOrDefault();
            set => __pbn__Duration = value;
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private float? __pbn__Duration;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControllerEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"object_id", IsRequired = true)]
        public ulong ObjectId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_id", IsRequired = true)]
        public uint EventId { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint data_type { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"data")]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

        [global::ProtoBuf.ProtoContract()]
        public enum DataType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UINT32")]
            Uint32 = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
            Float = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ARB")]
            Arb = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControllerEventUInt32 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Data
        {
            get => __pbn__Data ?? 0u;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private uint? __pbn__Data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControllerEventFloat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float Data
        {
            get => __pbn__Data ?? 0f;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private float? __pbn__Data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControllerEventARB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data", IsRequired = true)]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NoiseParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"octave_count")]
        public uint OctaveCount
        {
            get => __pbn__OctaveCount.GetValueOrDefault();
            set => __pbn__OctaveCount = value;
        }
        public bool ShouldSerializeOctaveCount() => __pbn__OctaveCount != null;
        public void ResetOctaveCount() => __pbn__OctaveCount = null;
        private uint? __pbn__OctaveCount;

        [global::ProtoBuf.ProtoMember(2, Name = @"frequency")]
        public float Frequency
        {
            get => __pbn__Frequency.GetValueOrDefault();
            set => __pbn__Frequency = value;
        }
        public bool ShouldSerializeFrequency() => __pbn__Frequency != null;
        public void ResetFrequency() => __pbn__Frequency = null;
        private float? __pbn__Frequency;

        [global::ProtoBuf.ProtoMember(3, Name = @"max_x_distance")]
        public float MaxXDistance
        {
            get => __pbn__MaxXDistance.GetValueOrDefault();
            set => __pbn__MaxXDistance = value;
        }
        public bool ShouldSerializeMaxXDistance() => __pbn__MaxXDistance != null;
        public void ResetMaxXDistance() => __pbn__MaxXDistance = null;
        private float? __pbn__MaxXDistance;

        [global::ProtoBuf.ProtoMember(4, Name = @"max_z_distance")]
        public float MaxZDistance
        {
            get => __pbn__MaxZDistance.GetValueOrDefault();
            set => __pbn__MaxZDistance = value;
        }
        public bool ShouldSerializeMaxZDistance() => __pbn__MaxZDistance != null;
        public void ResetMaxZDistance() => __pbn__MaxZDistance = null;
        private float? __pbn__MaxZDistance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpringParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tension")]
        public float Tension
        {
            get => __pbn__Tension.GetValueOrDefault();
            set => __pbn__Tension = value;
        }
        public bool ShouldSerializeTension() => __pbn__Tension != null;
        public void ResetTension() => __pbn__Tension = null;
        private float? __pbn__Tension;

        [global::ProtoBuf.ProtoMember(2, Name = @"damping")]
        public float Damping
        {
            get => __pbn__Damping.GetValueOrDefault();
            set => __pbn__Damping = value;
        }
        public bool ShouldSerializeDamping() => __pbn__Damping != null;
        public void ResetDamping() => __pbn__Damping = null;
        private float? __pbn__Damping;

        [global::ProtoBuf.ProtoMember(3, Name = @"velocity_scale")]
        public float VelocityScale
        {
            get => __pbn__VelocityScale.GetValueOrDefault();
            set => __pbn__VelocityScale = value;
        }
        public bool ShouldSerializeVelocityScale() => __pbn__VelocityScale != null;
        public void ResetVelocityScale() => __pbn__VelocityScale = null;
        private float? __pbn__VelocityScale;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FishtailParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"noise_behavior")]
        public NoiseParameters NoiseBehavior { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"spring_behavior")]
        public SpringParameters SpringBehavior { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttachmentInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"parent_offset")]
        public Vector2 ParentOffset { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"offset")]
        public Vector2 Offset { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"angle_constraint")]
        [global::System.ComponentModel.DefaultValue(3.1415f)]
        public float AngleConstraint
        {
            get => __pbn__AngleConstraint ?? 3.1415f;
            set => __pbn__AngleConstraint = value;
        }
        public bool ShouldSerializeAngleConstraint() => __pbn__AngleConstraint != null;
        public void ResetAngleConstraint() => __pbn__AngleConstraint = null;
        private float? __pbn__AngleConstraint;

        [global::ProtoBuf.ProtoMember(4, Name = @"radius")]
        [global::System.ComponentModel.DefaultValue(0.25f)]
        public float Radius
        {
            get => __pbn__Radius ?? 0.25f;
            set => __pbn__Radius = value;
        }
        public bool ShouldSerializeRadius() => __pbn__Radius != null;
        public void ResetRadius() => __pbn__Radius = null;
        private float? __pbn__Radius;

        [global::ProtoBuf.ProtoMember(5, Name = @"flags")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint Flags
        {
            get => __pbn__Flags ?? 0u;
            set => __pbn__Flags = value;
        }
        public bool ShouldSerializeFlags() => __pbn__Flags != null;
        public void ResetFlags() => __pbn__Flags = null;
        private uint? __pbn__Flags;

        [global::ProtoBuf.ProtoMember(6, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(RoutingFormationFollowType.NodeTypeFollowLeader)]
        public RoutingFormationFollowType Type
        {
            get => __pbn__Type ?? RoutingFormationFollowType.NodeTypeFollowLeader;
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private RoutingFormationFollowType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(7, Name = @"fishtail_behavior")]
        public FishtailParameters FishtailBehavior { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum RoutingFormationFollowType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NODE_TYPE_FOLLOW_LEADER")]
            NodeTypeFollowLeader = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NODE_TYPE_CHAIN")]
            NodeTypeChain = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"NODE_TYPE_FISHTAIL")]
            NodeTypeFishtail = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WalkstyleOverride : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"from_walkstyle")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint FromWalkstyle
        {
            get => __pbn__FromWalkstyle ?? 0u;
            set => __pbn__FromWalkstyle = value;
        }
        public bool ShouldSerializeFromWalkstyle() => __pbn__FromWalkstyle != null;
        public void ResetFromWalkstyle() => __pbn__FromWalkstyle = null;
        private uint? __pbn__FromWalkstyle;

        [global::ProtoBuf.ProtoMember(2, Name = @"to_walkstyle")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint ToWalkstyle
        {
            get => __pbn__ToWalkstyle ?? 0u;
            set => __pbn__ToWalkstyle = value;
        }
        public bool ShouldSerializeToWalkstyle() => __pbn__ToWalkstyle != null;
        public void ResetToWalkstyle() => __pbn__ToWalkstyle = null;
        private uint? __pbn__ToWalkstyle;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SlaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(Type.SlaveNone)]
        public Type type
        {
            get => __pbn__type ?? Type.SlaveNone;
            set => __pbn__type = value;
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(3, Name = @"offset")]
        public global::System.Collections.Generic.List<AttachmentInfo> Offsets { get; } = new global::System.Collections.Generic.List<AttachmentInfo>();

        [global::ProtoBuf.ProtoMember(4, Name = @"walkstyle_overrides")]
        public global::System.Collections.Generic.List<WalkstyleOverride> WalkstyleOverrides { get; } = new global::System.Collections.Generic.List<WalkstyleOverride>();

        [global::ProtoBuf.ProtoMember(10, Name = @"slaves")]
        public global::System.Collections.Generic.List<SlaveData> Slaves { get; } = new global::System.Collections.Generic.List<SlaveData>();

        [global::ProtoBuf.ProtoMember(11, Name = @"final_location_override")]
        public Transform FinalLocationOverride { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SLAVE_NONE")]
            SlaveNone = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SLAVE_FOLLOW_ATTACHMENT")]
            SlaveFollowAttachment = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SLAVE_PAIRED_CHILD")]
            SlavePairedChild = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Route : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nodes")]
        public global::System.Collections.Generic.List<RouteNode> Nodes { get; } = new global::System.Collections.Generic.List<RouteNode>();

        [global::ProtoBuf.ProtoMember(3, Name = @"time")]
        public float Time
        {
            get => __pbn__Time.GetValueOrDefault();
            set => __pbn__Time = value;
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private float? __pbn__Time;

        [global::ProtoBuf.ProtoMember(4, Name = @"absolute_time_ms")]
        public ulong AbsoluteTimeMs
        {
            get => __pbn__AbsoluteTimeMs.GetValueOrDefault();
            set => __pbn__AbsoluteTimeMs = value;
        }
        public bool ShouldSerializeAbsoluteTimeMs() => __pbn__AbsoluteTimeMs != null;
        public void ResetAbsoluteTimeMs() => __pbn__AbsoluteTimeMs = null;
        private ulong? __pbn__AbsoluteTimeMs;

        [global::ProtoBuf.ProtoMember(5, Name = @"goals")]
        public global::System.Collections.Generic.List<GoalPoint> Goals { get; } = new global::System.Collections.Generic.List<GoalPoint>();

        [global::ProtoBuf.ProtoMember(6, Name = @"events")]
        public global::System.Collections.Generic.List<RouteEvent> Events { get; } = new global::System.Collections.Generic.List<RouteEvent>();

        [global::ProtoBuf.ProtoMember(7, Name = @"bounds_polygons")]
        public global::System.Collections.Generic.List<RoutePolygon> BoundsPolygons { get; } = new global::System.Collections.Generic.List<RoutePolygon>();

        [global::ProtoBuf.ProtoMember(8, Name = @"track")]
        [global::System.ComponentModel.DefaultValue(10000u)]
        public uint Track
        {
            get => __pbn__Track ?? 10000u;
            set => __pbn__Track = value;
        }
        public bool ShouldSerializeTrack() => __pbn__Track != null;
        public void ResetTrack() => __pbn__Track = null;
        private uint? __pbn__Track;

        [global::ProtoBuf.ProtoMember(9, Name = @"obstacle_polygons")]
        public global::System.Collections.Generic.List<RoutePolygons> ObstaclePolygons { get; } = new global::System.Collections.Generic.List<RoutePolygons>();

        [global::ProtoBuf.ProtoMember(10, Name = @"slaves")]
        public global::System.Collections.Generic.List<SlaveData> Slaves { get; } = new global::System.Collections.Generic.List<SlaveData>();

        [global::ProtoBuf.ProtoMember(11, Name = @"mask")]
        [global::System.ComponentModel.DefaultValue(4294967295u)]
        public uint Mask
        {
            get => __pbn__Mask ?? 4294967295u;
            set => __pbn__Mask = value;
        }
        public bool ShouldSerializeMask() => __pbn__Mask != null;
        public void ResetMask() => __pbn__Mask = null;
        private uint? __pbn__Mask;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
