// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: S4Common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4
{

    [global::ProtoBuf.ProtoContract()]
    public partial class IdList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsPacked = true)]
        public ulong[] Ids { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameInstanceInfoPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"zone_id", IsRequired = true)]
        public ulong ZoneId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"world_id")]
        public uint WorldId
        {
            get => __pbn__WorldId.GetValueOrDefault();
            set => __pbn__WorldId = value;
        }
        public bool ShouldSerializeWorldId() => __pbn__WorldId != null;
        public void ResetWorldId() => __pbn__WorldId = null;
        private uint? __pbn__WorldId;

        [global::ProtoBuf.ProtoMember(3, Name = @"neighborhood_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NeighborhoodName
        {
            get => __pbn__NeighborhoodName ?? "";
            set => __pbn__NeighborhoodName = value;
        }
        public bool ShouldSerializeNeighborhoodName() => __pbn__NeighborhoodName != null;
        public void ResetNeighborhoodName() => __pbn__NeighborhoodName = null;
        private string __pbn__NeighborhoodName;

        [global::ProtoBuf.ProtoMember(4, Name = @"zone_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ZoneName
        {
            get => __pbn__ZoneName ?? "";
            set => __pbn__ZoneName = value;
        }
        public bool ShouldSerializeZoneName() => __pbn__ZoneName != null;
        public void ResetZoneName() => __pbn__ZoneName = null;
        private string __pbn__ZoneName;

        [global::ProtoBuf.ProtoMember(5, Name = @"zone_session_id")]
        public ulong ZoneSessionId
        {
            get => __pbn__ZoneSessionId.GetValueOrDefault();
            set => __pbn__ZoneSessionId = value;
        }
        public bool ShouldSerializeZoneSessionId() => __pbn__ZoneSessionId != null;
        public void ResetZoneSessionId() => __pbn__ZoneSessionId = null;
        private ulong? __pbn__ZoneSessionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserEntitlement : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entitlement_id")]
        public ulong EntitlementId
        {
            get => __pbn__EntitlementId.GetValueOrDefault();
            set => __pbn__EntitlementId = value;
        }
        public bool ShouldSerializeEntitlementId() => __pbn__EntitlementId != null;
        public void ResetEntitlementId() => __pbn__EntitlementId = null;
        private ulong? __pbn__EntitlementId;

        [global::ProtoBuf.ProtoMember(2, Name = @"version")]
        public uint Version
        {
            get => __pbn__Version.GetValueOrDefault();
            set => __pbn__Version = value;
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private uint? __pbn__Version;

        [global::ProtoBuf.ProtoMember(3, Name = @"product_id")]
        public ulong ProductId
        {
            get => __pbn__ProductId.GetValueOrDefault();
            set => __pbn__ProductId = value;
        }
        public bool ShouldSerializeProductId() => __pbn__ProductId != null;
        public void ResetProductId() => __pbn__ProductId = null;
        private ulong? __pbn__ProductId;

        [global::ProtoBuf.ProtoMember(4, Name = @"last_modified_date")]
        public ulong LastModifiedDate
        {
            get => __pbn__LastModifiedDate.GetValueOrDefault();
            set => __pbn__LastModifiedDate = value;
        }
        public bool ShouldSerializeLastModifiedDate() => __pbn__LastModifiedDate != null;
        public void ResetLastModifiedDate() => __pbn__LastModifiedDate = null;
        private ulong? __pbn__LastModifiedDate;

        [global::ProtoBuf.ProtoMember(5, Name = @"product_sku")]
        public ulong ProductSku
        {
            get => __pbn__ProductSku.GetValueOrDefault();
            set => __pbn__ProductSku = value;
        }
        public bool ShouldSerializeProductSku() => __pbn__ProductSku != null;
        public void ResetProductSku() => __pbn__ProductSku = null;
        private ulong? __pbn__ProductSku;

        [global::ProtoBuf.ProtoMember(6, Name = @"view_state")]
        [global::System.ComponentModel.DefaultValue(0u)]
        public uint ViewState
        {
            get => __pbn__ViewState ?? 0u;
            set => __pbn__ViewState = value;
        }
        public bool ShouldSerializeViewState() => __pbn__ViewState != null;
        public void ResetViewState() => __pbn__ViewState = null;
        private uint? __pbn__ViewState;

        [global::ProtoBuf.ProtoMember(7, Name = @"install_state")]
        [global::System.ComponentModel.DefaultValue(100u)]
        public uint InstallState
        {
            get => __pbn__InstallState ?? 100u;
            set => __pbn__InstallState = value;
        }
        public bool ShouldSerializeInstallState() => __pbn__InstallState != null;
        public void ResetInstallState() => __pbn__InstallState = null;
        private uint? __pbn__InstallState;

        [global::ProtoBuf.ProtoMember(9, Name = @"terminate_date")]
        public ulong TerminateDate
        {
            get => __pbn__TerminateDate.GetValueOrDefault();
            set => __pbn__TerminateDate = value;
        }
        public bool ShouldSerializeTerminateDate() => __pbn__TerminateDate != null;
        public void ResetTerminateDate() => __pbn__TerminateDate = null;
        private ulong? __pbn__TerminateDate;

        [global::ProtoBuf.ProtoMember(10)]
        public uint trial_state
        {
            get => __pbn__trial_state.GetValueOrDefault();
            set => __pbn__trial_state = value;
        }
        public bool ShouldSerializetrial_state() => __pbn__trial_state != null;
        public void Resettrial_state() => __pbn__trial_state = null;
        private uint? __pbn__trial_state;

        [global::ProtoBuf.ProtoMember(11, Name = @"grant_date")]
        public ulong GrantDate
        {
            get => __pbn__GrantDate.GetValueOrDefault();
            set => __pbn__GrantDate = value;
        }
        public bool ShouldSerializeGrantDate() => __pbn__GrantDate != null;
        public void ResetGrantDate() => __pbn__GrantDate = null;
        private ulong? __pbn__GrantDate;

        [global::ProtoBuf.ProtoMember(12, Name = @"trial_view_state")]
        public uint TrialViewState
        {
            get => __pbn__TrialViewState.GetValueOrDefault();
            set => __pbn__TrialViewState = value;
        }
        public bool ShouldSerializeTrialViewState() => __pbn__TrialViewState != null;
        public void ResetTrialViewState() => __pbn__TrialViewState = null;
        private uint? __pbn__TrialViewState;

        [global::ProtoBuf.ProtoContract()]
        public enum TrialStateMask
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MASK_TRIAL_ENTITLEMENT")]
            MaskTrialEntitlement = 16,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum TrialState
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_STATE_NONE")]
            TrialStateNone = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_STATE_CONVERTED")]
            TrialStateConverted = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_STATE_TRIAL_ACTIVE")]
            TrialStateTrialActive = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"TRIAL_STATE_TRIAL_EXPIRED")]
            TrialStateTrialExpired = 17,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserEntitlementMap : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entitlements")]
        public global::System.Collections.Generic.List<UserEntitlement> Entitlements { get; } = new global::System.Collections.Generic.List<UserEntitlement>();

        [global::ProtoBuf.ProtoMember(2, Name = @"last_modified_date")]
        public ulong LastModifiedDate
        {
            get => __pbn__LastModifiedDate.GetValueOrDefault();
            set => __pbn__LastModifiedDate = value;
        }
        public bool ShouldSerializeLastModifiedDate() => __pbn__LastModifiedDate != null;
        public void ResetLastModifiedDate() => __pbn__LastModifiedDate = null;
        private ulong? __pbn__LastModifiedDate;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AchievementItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"progress")]
        public uint Progress
        {
            get => __pbn__Progress.GetValueOrDefault();
            set => __pbn__Progress = value;
        }
        public bool ShouldSerializeProgress() => __pbn__Progress != null;
        public void ResetProgress() => __pbn__Progress = null;
        private uint? __pbn__Progress;

        [global::ProtoBuf.ProtoMember(3, Name = @"totalpoints")]
        public uint Totalpoints
        {
            get => __pbn__Totalpoints.GetValueOrDefault();
            set => __pbn__Totalpoints = value;
        }
        public bool ShouldSerializeTotalpoints() => __pbn__Totalpoints != null;
        public void ResetTotalpoints() => __pbn__Totalpoints = null;
        private uint? __pbn__Totalpoints;

        [global::ProtoBuf.ProtoMember(4, Name = @"repeatcount")]
        public uint Repeatcount
        {
            get => __pbn__Repeatcount.GetValueOrDefault();
            set => __pbn__Repeatcount = value;
        }
        public bool ShouldSerializeRepeatcount() => __pbn__Repeatcount != null;
        public void ResetRepeatcount() => __pbn__Repeatcount = null;
        private uint? __pbn__Repeatcount;

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(6, Name = @"desc")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Desc
        {
            get => __pbn__Desc ?? "";
            set => __pbn__Desc = value;
        }
        public bool ShouldSerializeDesc() => __pbn__Desc != null;
        public void ResetDesc() => __pbn__Desc = null;
        private string __pbn__Desc;

        [global::ProtoBuf.ProtoMember(7, Name = @"howto")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Howto
        {
            get => __pbn__Howto ?? "";
            set => __pbn__Howto = value;
        }
        public bool ShouldSerializeHowto() => __pbn__Howto != null;
        public void ResetHowto() => __pbn__Howto = null;
        private string __pbn__Howto;

        [global::ProtoBuf.ProtoMember(8, Name = @"imageid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Imageid
        {
            get => __pbn__Imageid ?? "";
            set => __pbn__Imageid = value;
        }
        public bool ShouldSerializeImageid() => __pbn__Imageid != null;
        public void ResetImageid() => __pbn__Imageid = null;
        private string __pbn__Imageid;

        [global::ProtoBuf.ProtoMember(9, Name = @"grantdate")]
        public ulong Grantdate
        {
            get => __pbn__Grantdate.GetValueOrDefault();
            set => __pbn__Grantdate = value;
        }
        public bool ShouldSerializeGrantdate() => __pbn__Grantdate != null;
        public void ResetGrantdate() => __pbn__Grantdate = null;
        private ulong? __pbn__Grantdate;

        [global::ProtoBuf.ProtoMember(10, Name = @"expiredate")]
        public ulong Expiredate
        {
            get => __pbn__Expiredate.GetValueOrDefault();
            set => __pbn__Expiredate = value;
        }
        public bool ShouldSerializeExpiredate() => __pbn__Expiredate != null;
        public void ResetExpiredate() => __pbn__Expiredate = null;
        private ulong? __pbn__Expiredate;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AchievementList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"gamename")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Gamename
        {
            get => __pbn__Gamename ?? "";
            set => __pbn__Gamename = value;
        }
        public bool ShouldSerializeGamename() => __pbn__Gamename != null;
        public void ResetGamename() => __pbn__Gamename = null;
        private string __pbn__Gamename;

        [global::ProtoBuf.ProtoMember(3, Name = @"achievements")]
        public global::System.Collections.Generic.List<AchievementItem> Achievements { get; } = new global::System.Collections.Generic.List<AchievementItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AchievementMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resultcode")]
        public int Resultcode
        {
            get => __pbn__Resultcode.GetValueOrDefault();
            set => __pbn__Resultcode = value;
        }
        public bool ShouldSerializeResultcode() => __pbn__Resultcode != null;
        public void ResetResultcode() => __pbn__Resultcode = null;
        private int? __pbn__Resultcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"mode")]
        public uint Mode
        {
            get => __pbn__Mode.GetValueOrDefault();
            set => __pbn__Mode = value;
        }
        public bool ShouldSerializeMode() => __pbn__Mode != null;
        public void ResetMode() => __pbn__Mode = null;
        private uint? __pbn__Mode;

        [global::ProtoBuf.ProtoMember(3, Name = @"lists")]
        public global::System.Collections.Generic.List<AchievementList> Lists { get; } = new global::System.Collections.Generic.List<AchievementList>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserShoppingCartItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entitlement_tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EntitlementTag
        {
            get => __pbn__EntitlementTag ?? "";
            set => __pbn__EntitlementTag = value;
        }
        public bool ShouldSerializeEntitlementTag() => __pbn__EntitlementTag != null;
        public void ResetEntitlementTag() => __pbn__EntitlementTag = null;
        private string __pbn__EntitlementTag;

        [global::ProtoBuf.ProtoMember(2, Name = @"offer_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OfferId
        {
            get => __pbn__OfferId ?? "";
            set => __pbn__OfferId = value;
        }
        public bool ShouldSerializeOfferId() => __pbn__OfferId != null;
        public void ResetOfferId() => __pbn__OfferId = null;
        private string __pbn__OfferId;

        [global::ProtoBuf.ProtoMember(3, Name = @"quantity")]
        public uint Quantity
        {
            get => __pbn__Quantity.GetValueOrDefault();
            set => __pbn__Quantity = value;
        }
        public bool ShouldSerializeQuantity() => __pbn__Quantity != null;
        public void ResetQuantity() => __pbn__Quantity = null;
        private uint? __pbn__Quantity;

        [global::ProtoBuf.ProtoMember(4, Name = @"override_price")]
        public double OverridePrice
        {
            get => __pbn__OverridePrice.GetValueOrDefault();
            set => __pbn__OverridePrice = value;
        }
        public bool ShouldSerializeOverridePrice() => __pbn__OverridePrice != null;
        public void ResetOverridePrice() => __pbn__OverridePrice = null;
        private double? __pbn__OverridePrice;

        [global::ProtoBuf.ProtoMember(5, Name = @"unit_price")]
        public double UnitPrice
        {
            get => __pbn__UnitPrice.GetValueOrDefault();
            set => __pbn__UnitPrice = value;
        }
        public bool ShouldSerializeUnitPrice() => __pbn__UnitPrice != null;
        public void ResetUnitPrice() => __pbn__UnitPrice = null;
        private double? __pbn__UnitPrice;

        [global::ProtoBuf.ProtoMember(6, Name = @"ientitlement_tag")]
        public ulong IentitlementTag
        {
            get => __pbn__IentitlementTag.GetValueOrDefault();
            set => __pbn__IentitlementTag = value;
        }
        public bool ShouldSerializeIentitlementTag() => __pbn__IentitlementTag != null;
        public void ResetIentitlementTag() => __pbn__IentitlementTag = null;
        private ulong? __pbn__IentitlementTag;

        [global::ProtoBuf.ProtoMember(7, Name = @"entry_id")]
        public ulong EntryId
        {
            get => __pbn__EntryId.GetValueOrDefault();
            set => __pbn__EntryId = value;
        }
        public bool ShouldSerializeEntryId() => __pbn__EntryId != null;
        public void ResetEntryId() => __pbn__EntryId = null;
        private ulong? __pbn__EntryId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserShoppingCart : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"items")]
        public global::System.Collections.Generic.List<UserShoppingCartItem> Items { get; } = new global::System.Collections.Generic.List<UserShoppingCartItem>();

        [global::ProtoBuf.ProtoMember(2, Name = @"last_modified_date")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LastModifiedDate
        {
            get => __pbn__LastModifiedDate ?? "";
            set => __pbn__LastModifiedDate = value;
        }
        public bool ShouldSerializeLastModifiedDate() => __pbn__LastModifiedDate != null;
        public void ResetLastModifiedDate() => __pbn__LastModifiedDate = null;
        private string __pbn__LastModifiedDate;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Uint64Value : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
        public ulong Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Uint64List : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"values")]
        public global::System.Collections.Generic.List<Uint64Value> Values { get; } = new global::System.Collections.Generic.List<Uint64Value>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BoolValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
        public bool Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HouseholdSimIds : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong HouseholdId
        {
            get => __pbn__HouseholdId.GetValueOrDefault();
            set => __pbn__HouseholdId = value;
        }
        public bool ShouldSerializeHouseholdId() => __pbn__HouseholdId != null;
        public void ResetHouseholdId() => __pbn__HouseholdId = null;
        private ulong? __pbn__HouseholdId;

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsPacked = true)]
        public ulong[] SimIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Schedule : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"schedule_entries")]
        public global::System.Collections.Generic.List<ScheduleEntry> ScheduleEntries { get; } = new global::System.Collections.Generic.List<ScheduleEntry>();

        [global::ProtoBuf.ProtoContract()]
        public partial class ScheduleEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"days", IsPacked = true)]
            public global::System.Collections.Generic.List<ScheduleDay> Days { get; } = new global::System.Collections.Generic.List<ScheduleDay>();

            [global::ProtoBuf.ProtoMember(2, Name = @"start_hour")]
            public uint StartHour
            {
                get => __pbn__StartHour.GetValueOrDefault();
                set => __pbn__StartHour = value;
            }
            public bool ShouldSerializeStartHour() => __pbn__StartHour != null;
            public void ResetStartHour() => __pbn__StartHour = null;
            private uint? __pbn__StartHour;

            [global::ProtoBuf.ProtoMember(3, Name = @"start_minute")]
            public uint StartMinute
            {
                get => __pbn__StartMinute.GetValueOrDefault();
                set => __pbn__StartMinute = value;
            }
            public bool ShouldSerializeStartMinute() => __pbn__StartMinute != null;
            public void ResetStartMinute() => __pbn__StartMinute = null;
            private uint? __pbn__StartMinute;

            [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
            public float Duration
            {
                get => __pbn__Duration.GetValueOrDefault();
                set => __pbn__Duration = value;
            }
            public bool ShouldSerializeDuration() => __pbn__Duration != null;
            public void ResetDuration() => __pbn__Duration = null;
            private float? __pbn__Duration;

            [global::ProtoBuf.ProtoMember(5)]
            [global::System.ComponentModel.DefaultValue(ScheduleShiftType.AllDay)]
            public ScheduleShiftType schedule_shift_type
            {
                get => __pbn__schedule_shift_type ?? ScheduleShiftType.AllDay;
                set => __pbn__schedule_shift_type = value;
            }
            public bool ShouldSerializeschedule_shift_type() => __pbn__schedule_shift_type != null;
            public void Resetschedule_shift_type() => __pbn__schedule_shift_type = null;
            private ScheduleShiftType? __pbn__schedule_shift_type;

            [global::ProtoBuf.ProtoContract()]
            public enum ScheduleDay
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SUNDAY")]
                Sunday = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"MONDAY")]
                Monday = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"TUESDAY")]
                Tuesday = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"WEDNESDAY")]
                Wednesday = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"THURSDAY")]
                Thursday = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"FRIDAY")]
                Friday = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"SATURDAY")]
                Saturday = 6,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ScheduleShiftType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"ALL_DAY")]
                AllDay = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"MORNING")]
                Morning = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"EVENING")]
                Evening = 2,
            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimPronoun : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"case")]
        [global::System.ComponentModel.DefaultValue(GrammaticalCase.Unknown)]
        public GrammaticalCase Case
        {
            get => __pbn__Case ?? GrammaticalCase.Unknown;
            set => __pbn__Case = value;
        }
        public bool ShouldSerializeCase() => __pbn__Case != null;
        public void ResetCase() => __pbn__Case = null;
        private GrammaticalCase? __pbn__Case;

        [global::ProtoBuf.ProtoMember(2, Name = @"pronoun")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pronoun
        {
            get => __pbn__Pronoun ?? "";
            set => __pbn__Pronoun = value;
        }
        public bool ShouldSerializePronoun() => __pbn__Pronoun != null;
        public void ResetPronoun() => __pbn__Pronoun = null;
        private string __pbn__Pronoun;

        [global::ProtoBuf.ProtoContract()]
        public enum GrammaticalCase
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SUBJECTIVE")]
            Subjective = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"OBJECTIVE")]
            Objective = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"POSSESSIVE_DEPENDENT")]
            PossessiveDependent = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"POSSESSIVE_INDEPENDENT")]
            PossessiveIndependent = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"REFLEXIVE")]
            Reflexive = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimPronounList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pronouns")]
        public global::System.Collections.Generic.List<SimPronoun> Pronouns { get; } = new global::System.Collections.Generic.List<SimPronoun>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum UserState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"userstate_pending")]
        UserstatePending = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"userstate_logged_in")]
        UserstateLoggedIn = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"userstate_logged_out")]
        UserstateLoggedOut = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"userstate_timedout_out")]
        UserstateTimedoutOut = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"userstate_bad_login")]
        UserstateBadLogin = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"connected_to_mtx_server")]
        ConnectedToMtxServer = 100,
        [global::ProtoBuf.ProtoEnum(Name = @"connected_to_exchange_server")]
        ConnectedToExchangeServer = 200,
        [global::ProtoBuf.ProtoEnum(Name = @"connected_to_social_server")]
        ConnectedToSocialServer = 300,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
