// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SituationPersistence.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Persistence
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"goal_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong GoalTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"actor_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ActorId
        {
            get => __pbn__ActorId.GetValueOrDefault();
            set => __pbn__ActorId = value;
        }
        public bool ShouldSerializeActorId() => __pbn__ActorId != null;
        public void ResetActorId() => __pbn__ActorId = null;
        private ulong? __pbn__ActorId;

        [global::ProtoBuf.ProtoMember(3, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

        [global::ProtoBuf.ProtoMember(4, Name = @"completed")]
        public bool Completed
        {
            get => __pbn__Completed.GetValueOrDefault();
            set => __pbn__Completed = value;
        }
        public bool ShouldSerializeCompleted() => __pbn__Completed != null;
        public void ResetCompleted() => __pbn__Completed = null;
        private bool? __pbn__Completed;

        [global::ProtoBuf.ProtoMember(5, Name = @"chain_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ChainId
        {
            get => __pbn__ChainId.GetValueOrDefault();
            set => __pbn__ChainId = value;
        }
        public bool ShouldSerializeChainId() => __pbn__ChainId != null;
        public void ResetChainId() => __pbn__ChainId = null;
        private ulong? __pbn__ChainId;

        [global::ProtoBuf.ProtoMember(6, Name = @"custom_data")]
        public byte[] CustomData
        {
            get => __pbn__CustomData;
            set => __pbn__CustomData = value;
        }
        public bool ShouldSerializeCustomData() => __pbn__CustomData != null;
        public void ResetCustomData() => __pbn__CustomData = null;
        private byte[] __pbn__CustomData;

        [global::ProtoBuf.ProtoMember(7, Name = @"locked")]
        public bool Locked
        {
            get => __pbn__Locked.GetValueOrDefault();
            set => __pbn__Locked = value;
        }
        public bool ShouldSerializeLocked() => __pbn__Locked != null;
        public void ResetLocked() => __pbn__Locked = null;
        private bool? __pbn__Locked;

        [global::ProtoBuf.ProtoMember(8, Name = @"completed_time")]
        public ulong CompletedTime
        {
            get => __pbn__CompletedTime.GetValueOrDefault();
            set => __pbn__CompletedTime = value;
        }
        public bool ShouldSerializeCompletedTime() => __pbn__CompletedTime != null;
        public void ResetCompletedTime() => __pbn__CompletedTime = null;
        private ulong? __pbn__CompletedTime;

        [global::ProtoBuf.ProtoMember(9, Name = @"target_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong TargetId
        {
            get => __pbn__TargetId.GetValueOrDefault();
            set => __pbn__TargetId = value;
        }
        public bool ShouldSerializeTargetId() => __pbn__TargetId != null;
        public void ResetTargetId() => __pbn__TargetId = null;
        private ulong? __pbn__TargetId;

        [global::ProtoBuf.ProtoMember(10, Name = @"secondary_target_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SecondaryTargetId
        {
            get => __pbn__SecondaryTargetId.GetValueOrDefault();
            set => __pbn__SecondaryTargetId = value;
        }
        public bool ShouldSerializeSecondaryTargetId() => __pbn__SecondaryTargetId != null;
        public void ResetSecondaryTargetId() => __pbn__SecondaryTargetId = null;
        private ulong? __pbn__SecondaryTargetId;

        [global::ProtoBuf.ProtoMember(11, Name = @"sub_goals")]
        public global::System.Collections.Generic.List<SituationGoalData> SubGoals { get; } = new global::System.Collections.Generic.List<SituationGoalData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CompletedSituationGoalData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"situation_goal")]
        public SituationGoalData SituationGoal { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"chosen_goal_set_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ChosenGoalSetTypeId
        {
            get => __pbn__ChosenGoalSetTypeId.GetValueOrDefault();
            set => __pbn__ChosenGoalSetTypeId = value;
        }
        public bool ShouldSerializeChosenGoalSetTypeId() => __pbn__ChosenGoalSetTypeId != null;
        public void ResetChosenGoalSetTypeId() => __pbn__ChosenGoalSetTypeId = null;
        private ulong? __pbn__ChosenGoalSetTypeId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalChainData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"starting_goal_set_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartingGoalSetTypeId
        {
            get => __pbn__StartingGoalSetTypeId.GetValueOrDefault();
            set => __pbn__StartingGoalSetTypeId = value;
        }
        public bool ShouldSerializeStartingGoalSetTypeId() => __pbn__StartingGoalSetTypeId != null;
        public void ResetStartingGoalSetTypeId() => __pbn__StartingGoalSetTypeId = null;
        private ulong? __pbn__StartingGoalSetTypeId;

        [global::ProtoBuf.ProtoMember(2, Name = @"chosen_goal_set_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ChosenGoalSetTypeId
        {
            get => __pbn__ChosenGoalSetTypeId.GetValueOrDefault();
            set => __pbn__ChosenGoalSetTypeId = value;
        }
        public bool ShouldSerializeChosenGoalSetTypeId() => __pbn__ChosenGoalSetTypeId != null;
        public void ResetChosenGoalSetTypeId() => __pbn__ChosenGoalSetTypeId = null;
        private ulong? __pbn__ChosenGoalSetTypeId;

        [global::ProtoBuf.ProtoMember(3, Name = @"chain_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ChainId
        {
            get => __pbn__ChainId.GetValueOrDefault();
            set => __pbn__ChainId = value;
        }
        public bool ShouldSerializeChainId() => __pbn__ChainId != null;
        public void ResetChainId() => __pbn__ChainId = null;
        private ulong? __pbn__ChainId;

        [global::ProtoBuf.ProtoMember(4, Name = @"display_position")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int DisplayPosition
        {
            get => __pbn__DisplayPosition ?? -1;
            set => __pbn__DisplayPosition = value;
        }
        public bool ShouldSerializeDisplayPosition() => __pbn__DisplayPosition != null;
        public void ResetDisplayPosition() => __pbn__DisplayPosition = null;
        private int? __pbn__DisplayPosition;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalTrackerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"has_offered_goals")]
        public bool HasOfferedGoals
        {
            get => __pbn__HasOfferedGoals.GetValueOrDefault();
            set => __pbn__HasOfferedGoals = value;
        }
        public bool ShouldSerializeHasOfferedGoals() => __pbn__HasOfferedGoals != null;
        public void ResetHasOfferedGoals() => __pbn__HasOfferedGoals = null;
        private bool? __pbn__HasOfferedGoals;

        [global::ProtoBuf.ProtoMember(2, Name = @"inherited_target_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong InheritedTargetId
        {
            get => __pbn__InheritedTargetId.GetValueOrDefault();
            set => __pbn__InheritedTargetId = value;
        }
        public bool ShouldSerializeInheritedTargetId() => __pbn__InheritedTargetId != null;
        public void ResetInheritedTargetId() => __pbn__InheritedTargetId = null;
        private ulong? __pbn__InheritedTargetId;

        [global::ProtoBuf.ProtoMember(3, Name = @"chains")]
        public global::System.Collections.Generic.List<SituationGoalChainData> Chains { get; } = new global::System.Collections.Generic.List<SituationGoalChainData>();

        [global::ProtoBuf.ProtoMember(4, Name = @"minor_goals")]
        public global::System.Collections.Generic.List<SituationGoalData> MinorGoals { get; } = new global::System.Collections.Generic.List<SituationGoalData>();

        [global::ProtoBuf.ProtoMember(5, Name = @"main_goal")]
        public SituationGoalData MainGoal { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"completed_goals")]
        public global::System.Collections.Generic.List<CompletedSituationGoalData> CompletedGoals { get; } = new global::System.Collections.Generic.List<CompletedSituationGoalData>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(GoalTrackerType.StandardGoalTracker)]
        public GoalTrackerType goal_tracker_type
        {
            get => __pbn__goal_tracker_type ?? GoalTrackerType.StandardGoalTracker;
            set => __pbn__goal_tracker_type = value;
        }
        public bool ShouldSerializegoal_tracker_type() => __pbn__goal_tracker_type != null;
        public void Resetgoal_tracker_type() => __pbn__goal_tracker_type = null;
        private GoalTrackerType? __pbn__goal_tracker_type;

        [global::ProtoBuf.ProtoMember(8, Name = @"graphed_goal_tracker_data")]
        public SituationGraphedGoalTrackerData GraphedGoalTrackerData { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum GoalTrackerType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STANDARD_GOAL_TRACKER")]
            StandardGoalTracker = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DYNAMIC_GOAL_TRACKER")]
            DynamicGoalTracker = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SIMPLE_GOAL_TRACKER")]
            SimpleGoalTracker = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTIVITY_GOAL_TRACKER")]
            ActivityGoalTracker = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"STANDARD_GRAPHED_GOAL_TRACKER")]
            StandardGraphedGoalTracker = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGraphedGoalTrackerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"completed_goals_ids")]
        public ulong[] CompletedGoalsIds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"unlocked_goals_ids")]
        public ulong[] UnlockedGoalsIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationAssignmentData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong SimId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"job_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong JobTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"purpose")]
        public uint Purpose
        {
            get => __pbn__Purpose.GetValueOrDefault();
            set => __pbn__Purpose = value;
        }
        public bool ShouldSerializePurpose() => __pbn__Purpose != null;
        public void ResetPurpose() => __pbn__Purpose = null;
        private uint? __pbn__Purpose;

        [global::ProtoBuf.ProtoMember(4, Name = @"role_state_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong RoleStateTypeId
        {
            get => __pbn__RoleStateTypeId.GetValueOrDefault();
            set => __pbn__RoleStateTypeId = value;
        }
        public bool ShouldSerializeRoleStateTypeId() => __pbn__RoleStateTypeId != null;
        public void ResetRoleStateTypeId() => __pbn__RoleStateTypeId = null;
        private ulong? __pbn__RoleStateTypeId;

        [global::ProtoBuf.ProtoMember(5, Name = @"spawning_option")]
        public uint SpawningOption
        {
            get => __pbn__SpawningOption.GetValueOrDefault();
            set => __pbn__SpawningOption = value;
        }
        public bool ShouldSerializeSpawningOption() => __pbn__SpawningOption != null;
        public void ResetSpawningOption() => __pbn__SpawningOption = null;
        private uint? __pbn__SpawningOption;

        [global::ProtoBuf.ProtoMember(6, Name = @"request_priority")]
        public uint RequestPriority
        {
            get => __pbn__RequestPriority.GetValueOrDefault();
            set => __pbn__RequestPriority = value;
        }
        public bool ShouldSerializeRequestPriority() => __pbn__RequestPriority != null;
        public void ResetRequestPriority() => __pbn__RequestPriority = null;
        private uint? __pbn__RequestPriority;

        [global::ProtoBuf.ProtoMember(7, Name = @"expectation_preference")]
        public bool ExpectationPreference
        {
            get => __pbn__ExpectationPreference.GetValueOrDefault();
            set => __pbn__ExpectationPreference = value;
        }
        public bool ShouldSerializeExpectationPreference() => __pbn__ExpectationPreference != null;
        public void ResetExpectationPreference() => __pbn__ExpectationPreference = null;
        private bool? __pbn__ExpectationPreference;

        [global::ProtoBuf.ProtoMember(8, Name = @"accept_alternate_sim")]
        public bool AcceptAlternateSim
        {
            get => __pbn__AcceptAlternateSim.GetValueOrDefault();
            set => __pbn__AcceptAlternateSim = value;
        }
        public bool ShouldSerializeAcceptAlternateSim() => __pbn__AcceptAlternateSim != null;
        public void ResetAcceptAlternateSim() => __pbn__AcceptAlternateSim = null;
        private bool? __pbn__AcceptAlternateSim;

        [global::ProtoBuf.ProtoMember(9, Name = @"common_blacklist_categories")]
        public uint CommonBlacklistCategories
        {
            get => __pbn__CommonBlacklistCategories.GetValueOrDefault();
            set => __pbn__CommonBlacklistCategories = value;
        }
        public bool ShouldSerializeCommonBlacklistCategories() => __pbn__CommonBlacklistCategories != null;
        public void ResetCommonBlacklistCategories() => __pbn__CommonBlacklistCategories = null;
        private uint? __pbn__CommonBlacklistCategories;

        [global::ProtoBuf.ProtoMember(10, Name = @"elevated_importance_override")]
        public bool ElevatedImportanceOverride
        {
            get => __pbn__ElevatedImportanceOverride.GetValueOrDefault();
            set => __pbn__ElevatedImportanceOverride = value;
        }
        public bool ShouldSerializeElevatedImportanceOverride() => __pbn__ElevatedImportanceOverride != null;
        public void ResetElevatedImportanceOverride() => __pbn__ElevatedImportanceOverride = null;
        private bool? __pbn__ElevatedImportanceOverride;

        [global::ProtoBuf.ProtoMember(11, Name = @"reservation")]
        public bool Reservation
        {
            get => __pbn__Reservation.GetValueOrDefault();
            set => __pbn__Reservation = value;
        }
        public bool ShouldSerializeReservation() => __pbn__Reservation != null;
        public void ResetReservation() => __pbn__Reservation = null;
        private bool? __pbn__Reservation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSimpleSeedlingData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"phase_index")]
        public uint PhaseIndex
        {
            get => __pbn__PhaseIndex.GetValueOrDefault();
            set => __pbn__PhaseIndex = value;
        }
        public bool ShouldSerializePhaseIndex() => __pbn__PhaseIndex != null;
        public void ResetPhaseIndex() => __pbn__PhaseIndex = null;
        private uint? __pbn__PhaseIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"remaining_phase_time")]
        public float RemainingPhaseTime
        {
            get => __pbn__RemainingPhaseTime.GetValueOrDefault();
            set => __pbn__RemainingPhaseTime = value;
        }
        public bool ShouldSerializeRemainingPhaseTime() => __pbn__RemainingPhaseTime != null;
        public void ResetRemainingPhaseTime() => __pbn__RemainingPhaseTime = null;
        private float? __pbn__RemainingPhaseTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationComplexSeedlingData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"situation_custom_data")]
        public byte[] SituationCustomData
        {
            get => __pbn__SituationCustomData;
            set => __pbn__SituationCustomData = value;
        }
        public bool ShouldSerializeSituationCustomData() => __pbn__SituationCustomData != null;
        public void ResetSituationCustomData() => __pbn__SituationCustomData = null;
        private byte[] __pbn__SituationCustomData;

        [global::ProtoBuf.ProtoMember(2, Name = @"state_custom_data")]
        public byte[] StateCustomData
        {
            get => __pbn__StateCustomData;
            set => __pbn__StateCustomData = value;
        }
        public bool ShouldSerializeStateCustomData() => __pbn__StateCustomData != null;
        public void ResetStateCustomData() => __pbn__StateCustomData = null;
        private byte[] __pbn__StateCustomData;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationJobAndRoleState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"job_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong JobTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"role_state_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong RoleStateTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"emotional_loot_actions_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong EmotionalLootActionsTypeId
        {
            get => __pbn__EmotionalLootActionsTypeId.GetValueOrDefault();
            set => __pbn__EmotionalLootActionsTypeId = value;
        }
        public bool ShouldSerializeEmotionalLootActionsTypeId() => __pbn__EmotionalLootActionsTypeId != null;
        public void ResetEmotionalLootActionsTypeId() => __pbn__EmotionalLootActionsTypeId = null;
        private ulong? __pbn__EmotionalLootActionsTypeId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSpecialObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"definition_id", IsRequired = true)]
        public ulong DefinitionId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        public global::EA.Sims4.Network.LocalizedString Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSeedData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"situation_type_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong SituationTypeId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"situation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong SituationId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"seed_purpose")]
        public uint SeedPurpose
        {
            get => __pbn__SeedPurpose.GetValueOrDefault();
            set => __pbn__SeedPurpose = value;
        }
        public bool ShouldSerializeSeedPurpose() => __pbn__SeedPurpose != null;
        public void ResetSeedPurpose() => __pbn__SeedPurpose = null;
        private uint? __pbn__SeedPurpose;

        [global::ProtoBuf.ProtoMember(4, Name = @"invite_only")]
        public bool InviteOnly
        {
            get => __pbn__InviteOnly.GetValueOrDefault();
            set => __pbn__InviteOnly = value;
        }
        public bool ShouldSerializeInviteOnly() => __pbn__InviteOnly != null;
        public void ResetInviteOnly() => __pbn__InviteOnly = null;
        private bool? __pbn__InviteOnly;

        [global::ProtoBuf.ProtoMember(5, Name = @"host_sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong HostSimId
        {
            get => __pbn__HostSimId.GetValueOrDefault();
            set => __pbn__HostSimId = value;
        }
        public bool ShouldSerializeHostSimId() => __pbn__HostSimId != null;
        public void ResetHostSimId() => __pbn__HostSimId = null;
        private ulong? __pbn__HostSimId;

        [global::ProtoBuf.ProtoMember(6, Name = @"assignments")]
        public global::System.Collections.Generic.List<SituationAssignmentData> Assignments { get; } = new global::System.Collections.Generic.List<SituationAssignmentData>();

        [global::ProtoBuf.ProtoMember(7, Name = @"user_facing")]
        public bool UserFacing
        {
            get => __pbn__UserFacing.GetValueOrDefault();
            set => __pbn__UserFacing = value;
        }
        public bool ShouldSerializeUserFacing() => __pbn__UserFacing != null;
        public void ResetUserFacing() => __pbn__UserFacing = null;
        private bool? __pbn__UserFacing;

        [global::ProtoBuf.ProtoMember(8, Name = @"duration")]
        public float Duration
        {
            get => __pbn__Duration.GetValueOrDefault();
            set => __pbn__Duration = value;
        }
        public bool ShouldSerializeDuration() => __pbn__Duration != null;
        public void ResetDuration() => __pbn__Duration = null;
        private float? __pbn__Duration;

        [global::ProtoBuf.ProtoMember(9, Name = @"zone_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ZoneId
        {
            get => __pbn__ZoneId.GetValueOrDefault();
            set => __pbn__ZoneId = value;
        }
        public bool ShouldSerializeZoneId() => __pbn__ZoneId != null;
        public void ResetZoneId() => __pbn__ZoneId = null;
        private ulong? __pbn__ZoneId;

        [global::ProtoBuf.ProtoMember(10, Name = @"jobs_and_role_states")]
        public global::System.Collections.Generic.List<SituationJobAndRoleState> JobsAndRoleStates { get; } = new global::System.Collections.Generic.List<SituationJobAndRoleState>();

        [global::ProtoBuf.ProtoMember(11, Name = @"create_time")]
        public ulong CreateTime
        {
            get => __pbn__CreateTime.GetValueOrDefault();
            set => __pbn__CreateTime = value;
        }
        public bool ShouldSerializeCreateTime() => __pbn__CreateTime != null;
        public void ResetCreateTime() => __pbn__CreateTime = null;
        private ulong? __pbn__CreateTime;

        [global::ProtoBuf.ProtoMember(12, Name = @"score")]
        public float Score
        {
            get => __pbn__Score.GetValueOrDefault();
            set => __pbn__Score = value;
        }
        public bool ShouldSerializeScore() => __pbn__Score != null;
        public void ResetScore() => __pbn__Score = null;
        private float? __pbn__Score;

        [global::ProtoBuf.ProtoMember(13, Name = @"simple_data")]
        public SituationSimpleSeedlingData SimpleData { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"complex_data")]
        public SituationComplexSeedlingData ComplexData { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"filter_requesting_sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong FilterRequestingSimId
        {
            get => __pbn__FilterRequestingSimId.GetValueOrDefault();
            set => __pbn__FilterRequestingSimId = value;
        }
        public bool ShouldSerializeFilterRequestingSimId() => __pbn__FilterRequestingSimId != null;
        public void ResetFilterRequestingSimId() => __pbn__FilterRequestingSimId = null;
        private ulong? __pbn__FilterRequestingSimId;

        [global::ProtoBuf.ProtoMember(16, Name = @"goal_tracker_data")]
        public SituationGoalTrackerData GoalTrackerData { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"start_time")]
        public ulong StartTime
        {
            get => __pbn__StartTime.GetValueOrDefault();
            set => __pbn__StartTime = value;
        }
        public bool ShouldSerializeStartTime() => __pbn__StartTime != null;
        public void ResetStartTime() => __pbn__StartTime = null;
        private ulong? __pbn__StartTime;

        [global::ProtoBuf.ProtoMember(18, Name = @"active_household_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong ActiveHouseholdId
        {
            get => __pbn__ActiveHouseholdId.GetValueOrDefault();
            set => __pbn__ActiveHouseholdId = value;
        }
        public bool ShouldSerializeActiveHouseholdId() => __pbn__ActiveHouseholdId != null;
        public void ResetActiveHouseholdId() => __pbn__ActiveHouseholdId = null;
        private ulong? __pbn__ActiveHouseholdId;

        [global::ProtoBuf.ProtoMember(19, Name = @"scoring_enabled")]
        public bool ScoringEnabled
        {
            get => __pbn__ScoringEnabled.GetValueOrDefault();
            set => __pbn__ScoringEnabled = value;
        }
        public bool ShouldSerializeScoringEnabled() => __pbn__ScoringEnabled != null;
        public void ResetScoringEnabled() => __pbn__ScoringEnabled = null;
        private bool? __pbn__ScoringEnabled;

        [global::ProtoBuf.ProtoMember(20, Name = @"main_goal_visibility")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool MainGoalVisibility
        {
            get => __pbn__MainGoalVisibility ?? true;
            set => __pbn__MainGoalVisibility = value;
        }
        public bool ShouldSerializeMainGoalVisibility() => __pbn__MainGoalVisibility != null;
        public void ResetMainGoalVisibility() => __pbn__MainGoalVisibility = null;
        private bool? __pbn__MainGoalVisibility;

        [global::ProtoBuf.ProtoMember(21, Name = @"linked_sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong LinkedSimId
        {
            get => __pbn__LinkedSimId.GetValueOrDefault();
            set => __pbn__LinkedSimId = value;
        }
        public bool ShouldSerializeLinkedSimId() => __pbn__LinkedSimId != null;
        public void ResetLinkedSimId() => __pbn__LinkedSimId = null;
        private ulong? __pbn__LinkedSimId;

        [global::ProtoBuf.ProtoMember(22, Name = @"special_object_icon")]
        public global::EA.Sims4.Network.IconInfo SpecialObjectIcon { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"situation_activity_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] SituationActivityIds { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"special_object")]
        public SituationSpecialObject SpecialObject { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"guest_attire_color")]
        public ulong GuestAttireColor
        {
            get => __pbn__GuestAttireColor.GetValueOrDefault();
            set => __pbn__GuestAttireColor = value;
        }
        public bool ShouldSerializeGuestAttireColor() => __pbn__GuestAttireColor != null;
        public void ResetGuestAttireColor() => __pbn__GuestAttireColor = null;
        private ulong? __pbn__GuestAttireColor;

        [global::ProtoBuf.ProtoMember(26, Name = @"guest_attire_style")]
        public ulong GuestAttireStyle
        {
            get => __pbn__GuestAttireStyle.GetValueOrDefault();
            set => __pbn__GuestAttireStyle = value;
        }
        public bool ShouldSerializeGuestAttireStyle() => __pbn__GuestAttireStyle != null;
        public void ResetGuestAttireStyle() => __pbn__GuestAttireStyle = null;
        private ulong? __pbn__GuestAttireStyle;

        [global::ProtoBuf.ProtoMember(27, Name = @"spawn_sims_during_zone_spin_up")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool SpawnSimsDuringZoneSpinUp
        {
            get => __pbn__SpawnSimsDuringZoneSpinUp ?? false;
            set => __pbn__SpawnSimsDuringZoneSpinUp = value;
        }
        public bool ShouldSerializeSpawnSimsDuringZoneSpinUp() => __pbn__SpawnSimsDuringZoneSpinUp != null;
        public void ResetSpawnSimsDuringZoneSpinUp() => __pbn__SpawnSimsDuringZoneSpinUp = null;
        private bool? __pbn__SpawnSimsDuringZoneSpinUp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationBlacklistTagData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tag", IsRequired = true)]
        public ulong Tag { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time", IsRequired = true)]
        public ulong Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationBlacklistData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sim_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong SimId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tag_data")]
        public global::System.Collections.Generic.List<SituationBlacklistTagData> TagDatas { get; } = new global::System.Collections.Generic.List<SituationBlacklistTagData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AllSituationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"seeds")]
        public global::System.Collections.Generic.List<SituationSeedData> Seeds { get; } = new global::System.Collections.Generic.List<SituationSeedData>();

        [global::ProtoBuf.ProtoMember(2, Name = @"leave_situation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong LeaveSituationId
        {
            get => __pbn__LeaveSituationId.GetValueOrDefault();
            set => __pbn__LeaveSituationId = value;
        }
        public bool ShouldSerializeLeaveSituationId() => __pbn__LeaveSituationId != null;
        public void ResetLeaveSituationId() => __pbn__LeaveSituationId = null;
        private ulong? __pbn__LeaveSituationId;

        [global::ProtoBuf.ProtoMember(3, Name = @"leave_now_situation_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong LeaveNowSituationId
        {
            get => __pbn__LeaveNowSituationId.GetValueOrDefault();
            set => __pbn__LeaveNowSituationId = value;
        }
        public bool ShouldSerializeLeaveNowSituationId() => __pbn__LeaveNowSituationId != null;
        public void ResetLeaveNowSituationId() => __pbn__LeaveNowSituationId = null;
        private ulong? __pbn__LeaveNowSituationId;

        [global::ProtoBuf.ProtoMember(4, Name = @"blacklist_data")]
        public global::System.Collections.Generic.List<SituationBlacklistData> BlacklistDatas { get; } = new global::System.Collections.Generic.List<SituationBlacklistData>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
