// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Social.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFriendMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong simId
        {
            get => __pbn__simId.GetValueOrDefault();
            set => __pbn__simId = value;
        }
        public bool ShouldSerializesimId() => __pbn__simId != null;
        public void ResetsimId() => __pbn__simId = null;
        private ulong? __pbn__simId;

        [global::ProtoBuf.ProtoMember(2, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(3, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(4, Name = @"prefix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Prefix
        {
            get => __pbn__Prefix ?? "";
            set => __pbn__Prefix = value;
        }
        public bool ShouldSerializePrefix() => __pbn__Prefix != null;
        public void ResetPrefix() => __pbn__Prefix = null;
        private string __pbn__Prefix;

        [global::ProtoBuf.ProtoMember(5, Name = @"persona")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Persona
        {
            get => __pbn__Persona ?? "";
            set => __pbn__Persona = value;
        }
        public bool ShouldSerializePersona() => __pbn__Persona != null;
        public void ResetPersona() => __pbn__Persona = null;
        private string __pbn__Persona;

        [global::ProtoBuf.ProtoMember(6)]
        public bool cheatForce
        {
            get => __pbn__cheatForce.GetValueOrDefault();
            set => __pbn__cheatForce = value;
        }
        public bool ShouldSerializecheatForce() => __pbn__cheatForce != null;
        public void ResetcheatForce() => __pbn__cheatForce = null;
        private bool? __pbn__cheatForce;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialPersonaResponseMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"personas")]
        public global::System.Collections.Generic.List<string> Personas { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialGenericResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public uint Error
        {
            get => __pbn__Error.GetValueOrDefault();
            set => __pbn__Error = value;
        }
        public bool ShouldSerializeError() => __pbn__Error != null;
        public void ResetError() => __pbn__Error = null;
        private uint? __pbn__Error;

        [global::ProtoBuf.ProtoMember(2, Name = @"msg_type")]
        [global::System.ComponentModel.DefaultValue(SocialOpTypes.SopPublicMin)]
        public SocialOpTypes MsgType
        {
            get => __pbn__MsgType ?? SocialOpTypes.SopPublicMin;
            set => __pbn__MsgType = value;
        }
        public bool ShouldSerializeMsgType() => __pbn__MsgType != null;
        public void ResetMsgType() => __pbn__MsgType = null;
        private SocialOpTypes? __pbn__MsgType;

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] postId
        {
            get => __pbn__postId;
            set => __pbn__postId = value;
        }
        public bool ShouldSerializepostId() => __pbn__postId != null;
        public void ResetpostId() => __pbn__postId = null;
        private byte[] __pbn__postId;

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] postParentId
        {
            get => __pbn__postParentId;
            set => __pbn__postParentId = value;
        }
        public bool ShouldSerializepostParentId() => __pbn__postParentId != null;
        public void ResetpostParentId() => __pbn__postParentId = null;
        private byte[] __pbn__postParentId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialPlayerInfoList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"players")]
        public global::System.Collections.Generic.List<PlayerInfo> Players { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayerInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string AccountName
            {
                get => __pbn__AccountName ?? "";
                set => __pbn__AccountName = value;
            }
            public bool ShouldSerializeAccountName() => __pbn__AccountName != null;
            public void ResetAccountName() => __pbn__AccountName = null;
            private string __pbn__AccountName;

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string AccountNotes
            {
                get => __pbn__AccountNotes ?? "";
                set => __pbn__AccountNotes = value;
            }
            public bool ShouldSerializeAccountNotes() => __pbn__AccountNotes != null;
            public void ResetAccountNotes() => __pbn__AccountNotes = null;
            private string __pbn__AccountNotes;

            [global::ProtoBuf.ProtoMember(3, Name = @"presence")]
            [global::System.ComponentModel.DefaultValue(OnlinePresenceStatus.PresenceUnavailable)]
            public OnlinePresenceStatus Presence
            {
                get => __pbn__Presence ?? OnlinePresenceStatus.PresenceUnavailable;
                set => __pbn__Presence = value;
            }
            public bool ShouldSerializePresence() => __pbn__Presence != null;
            public void ResetPresence() => __pbn__Presence = null;
            private OnlinePresenceStatus? __pbn__Presence;

            [global::ProtoBuf.ProtoMember(4)]
            [global::System.ComponentModel.DefaultValue("")]
            public string OnlineStatus2
            {
                get => __pbn__OnlineStatus2 ?? "";
                set => __pbn__OnlineStatus2 = value;
            }
            public bool ShouldSerializeOnlineStatus2() => __pbn__OnlineStatus2 != null;
            public void ResetOnlineStatus2() => __pbn__OnlineStatus2 = null;
            private string __pbn__OnlineStatus2;

            [global::ProtoBuf.ProtoMember(9)]
            public ulong NucleusId
            {
                get => __pbn__NucleusId.GetValueOrDefault();
                set => __pbn__NucleusId = value;
            }
            public bool ShouldSerializeNucleusId() => __pbn__NucleusId != null;
            public void ResetNucleusId() => __pbn__NucleusId = null;
            private ulong? __pbn__NucleusId;

            [global::ProtoBuf.ProtoMember(10)]
            [global::System.ComponentModel.DefaultValue("")]
            public string PlayerBio
            {
                get => __pbn__PlayerBio ?? "";
                set => __pbn__PlayerBio = value;
            }
            public bool ShouldSerializePlayerBio() => __pbn__PlayerBio != null;
            public void ResetPlayerBio() => __pbn__PlayerBio = null;
            private string __pbn__PlayerBio;

            [global::ProtoBuf.ProtoMember(11, Name = @"exclude_reported")]
            public bool ExcludeReported
            {
                get => __pbn__ExcludeReported.GetValueOrDefault();
                set => __pbn__ExcludeReported = value;
            }
            public bool ShouldSerializeExcludeReported() => __pbn__ExcludeReported != null;
            public void ResetExcludeReported() => __pbn__ExcludeReported = null;
            private bool? __pbn__ExcludeReported;

            [global::ProtoBuf.ProtoMember(12)]
            public bool IsUserBlocked
            {
                get => __pbn__IsUserBlocked.GetValueOrDefault();
                set => __pbn__IsUserBlocked = value;
            }
            public bool ShouldSerializeIsUserBlocked() => __pbn__IsUserBlocked != null;
            public void ResetIsUserBlocked() => __pbn__IsUserBlocked = null;
            private bool? __pbn__IsUserBlocked;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialSearchMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"prefix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Prefix
        {
            get => __pbn__Prefix ?? "";
            set => __pbn__Prefix = value;
        }
        public bool ShouldSerializePrefix() => __pbn__Prefix != null;
        public void ResetPrefix() => __pbn__Prefix = null;
        private string __pbn__Prefix;

        [global::ProtoBuf.ProtoMember(2, Name = @"search_results")]
        public global::System.Collections.Generic.List<LocalizedStringToken> SearchResults { get; } = new global::System.Collections.Generic.List<LocalizedStringToken>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OriginErrorMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"errorcode")]
        public uint Errorcode
        {
            get => __pbn__Errorcode.GetValueOrDefault();
            set => __pbn__Errorcode = value;
        }
        public bool ShouldSerializeErrorcode() => __pbn__Errorcode != null;
        public void ResetErrorcode() => __pbn__Errorcode = null;
        private uint? __pbn__Errorcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"errormessage")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormessage
        {
            get => __pbn__Errormessage ?? "";
            set => __pbn__Errormessage = value;
        }
        public bool ShouldSerializeErrormessage() => __pbn__Errormessage != null;
        public void ResetErrormessage() => __pbn__Errormessage = null;
        private string __pbn__Errormessage;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialInviteResponseMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"invitationid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Invitationid
        {
            get => __pbn__Invitationid ?? "";
            set => __pbn__Invitationid = value;
        }
        public bool ShouldSerializeInvitationid() => __pbn__Invitationid != null;
        public void ResetInvitationid() => __pbn__Invitationid = null;
        private string __pbn__Invitationid;

        [global::ProtoBuf.ProtoMember(2, Name = @"invitationtype")]
        public uint Invitationtype
        {
            get => __pbn__Invitationtype.GetValueOrDefault();
            set => __pbn__Invitationtype = value;
        }
        public bool ShouldSerializeInvitationtype() => __pbn__Invitationtype != null;
        public void ResetInvitationtype() => __pbn__Invitationtype = null;
        private uint? __pbn__Invitationtype;

        [global::ProtoBuf.ProtoMember(3, Name = @"inviternucleusid")]
        public ulong Inviternucleusid
        {
            get => __pbn__Inviternucleusid.GetValueOrDefault();
            set => __pbn__Inviternucleusid = value;
        }
        public bool ShouldSerializeInviternucleusid() => __pbn__Inviternucleusid != null;
        public void ResetInviternucleusid() => __pbn__Inviternucleusid = null;
        private ulong? __pbn__Inviternucleusid;

        [global::ProtoBuf.ProtoMember(4, Name = @"accepternucleusid")]
        public ulong Accepternucleusid
        {
            get => __pbn__Accepternucleusid.GetValueOrDefault();
            set => __pbn__Accepternucleusid = value;
        }
        public bool ShouldSerializeAccepternucleusid() => __pbn__Accepternucleusid != null;
        public void ResetAccepternucleusid() => __pbn__Accepternucleusid = null;
        private ulong? __pbn__Accepternucleusid;

        [global::ProtoBuf.ProtoMember(5)]
        public bool actionSuccess
        {
            get => __pbn__actionSuccess.GetValueOrDefault();
            set => __pbn__actionSuccess = value;
        }
        public bool ShouldSerializeactionSuccess() => __pbn__actionSuccess != null;
        public void ResetactionSuccess() => __pbn__actionSuccess = null;
        private bool? __pbn__actionSuccess;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialCassandraTest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opcode")]
        [global::System.ComponentModel.DefaultValue(CassandraTestCode.CassandraCloseSocket)]
        public CassandraTestCode Opcode
        {
            get => __pbn__Opcode ?? CassandraTestCode.CassandraCloseSocket;
            set => __pbn__Opcode = value;
        }
        public bool ShouldSerializeOpcode() => __pbn__Opcode != null;
        public void ResetOpcode() => __pbn__Opcode = null;
        private CassandraTestCode? __pbn__Opcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFriendListRequestMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account_id")]
        public ulong AccountId
        {
            get => __pbn__AccountId.GetValueOrDefault();
            set => __pbn__AccountId = value;
        }
        public bool ShouldSerializeAccountId() => __pbn__AccountId != null;
        public void ResetAccountId() => __pbn__AccountId = null;
        private ulong? __pbn__AccountId;

        [global::ProtoBuf.ProtoMember(2, Name = @"friend_id")]
        public ulong FriendId
        {
            get => __pbn__FriendId.GetValueOrDefault();
            set => __pbn__FriendId = value;
        }
        public bool ShouldSerializeFriendId() => __pbn__FriendId != null;
        public void ResetFriendId() => __pbn__FriendId = null;
        private ulong? __pbn__FriendId;

        [global::ProtoBuf.ProtoMember(3, Name = @"address_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AddressStr
        {
            get => __pbn__AddressStr ?? "";
            set => __pbn__AddressStr = value;
        }
        public bool ShouldSerializeAddressStr() => __pbn__AddressStr != null;
        public void ResetAddressStr() => __pbn__AddressStr = null;
        private string __pbn__AddressStr;

        [global::ProtoBuf.ProtoMember(4, Name = @"object_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ObjectStr
        {
            get => __pbn__ObjectStr ?? "";
            set => __pbn__ObjectStr = value;
        }
        public bool ShouldSerializeObjectStr() => __pbn__ObjectStr != null;
        public void ResetObjectStr() => __pbn__ObjectStr = null;
        private string __pbn__ObjectStr;

        [global::ProtoBuf.ProtoMember(5, Name = @"reply_proxy_id")]
        public ulong ReplyProxyId
        {
            get => __pbn__ReplyProxyId.GetValueOrDefault();
            set => __pbn__ReplyProxyId = value;
        }
        public bool ShouldSerializeReplyProxyId() => __pbn__ReplyProxyId != null;
        public void ResetReplyProxyId() => __pbn__ReplyProxyId = null;
        private ulong? __pbn__ReplyProxyId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialRequestNucleusIdFromPersona : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"requestid")]
        public ulong Requestid
        {
            get => __pbn__Requestid.GetValueOrDefault();
            set => __pbn__Requestid = value;
        }
        public bool ShouldSerializeRequestid() => __pbn__Requestid != null;
        public void ResetRequestid() => __pbn__Requestid = null;
        private ulong? __pbn__Requestid;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string personaName
        {
            get => __pbn__personaName ?? "";
            set => __pbn__personaName = value;
        }
        public bool ShouldSerializepersonaName() => __pbn__personaName != null;
        public void ResetpersonaName() => __pbn__personaName = null;
        private string __pbn__personaName;

        [global::ProtoBuf.ProtoMember(3, Name = @"message_id")]
        public uint MessageId
        {
            get => __pbn__MessageId.GetValueOrDefault();
            set => __pbn__MessageId = value;
        }
        public bool ShouldSerializeMessageId() => __pbn__MessageId != null;
        public void ResetMessageId() => __pbn__MessageId = null;
        private uint? __pbn__MessageId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialNucleusIdFromPersonaResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"requestid")]
        public ulong Requestid
        {
            get => __pbn__Requestid.GetValueOrDefault();
            set => __pbn__Requestid = value;
        }
        public bool ShouldSerializeRequestid() => __pbn__Requestid != null;
        public void ResetRequestid() => __pbn__Requestid = null;
        private ulong? __pbn__Requestid;

        [global::ProtoBuf.ProtoMember(2, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(3, Name = @"message_id")]
        public uint MessageId
        {
            get => __pbn__MessageId.GetValueOrDefault();
            set => __pbn__MessageId = value;
        }
        public bool ShouldSerializeMessageId() => __pbn__MessageId != null;
        public void ResetMessageId() => __pbn__MessageId = null;
        private uint? __pbn__MessageId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialExchangeMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"envelope")]
        public ExchangeSocialEnvelope Envelope { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFollowersMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sfim_blob")]
        public global::System.Collections.Generic.List<byte[]> SfimBlobs { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFeedItemMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"feed_id")]
        public byte[] FeedId
        {
            get => __pbn__FeedId;
            set => __pbn__FeedId = value;
        }
        public bool ShouldSerializeFeedId() => __pbn__FeedId != null;
        public void ResetFeedId() => __pbn__FeedId = null;
        private byte[] __pbn__FeedId;

        [global::ProtoBuf.ProtoMember(2, Name = @"feed_type")]
        [global::System.ComponentModel.DefaultValue(SocialFeedItemType.SfiItemDownloaded)]
        public SocialFeedItemType FeedType
        {
            get => __pbn__FeedType ?? SocialFeedItemType.SfiItemDownloaded;
            set => __pbn__FeedType = value;
        }
        public bool ShouldSerializeFeedType() => __pbn__FeedType != null;
        public void ResetFeedType() => __pbn__FeedType = null;
        private SocialFeedItemType? __pbn__FeedType;

        [global::ProtoBuf.ProtoMember(3, Name = @"metadata")]
        public TrayMetadata Metadata { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(5, Name = @"persona")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Persona
        {
            get => __pbn__Persona ?? "";
            set => __pbn__Persona = value;
        }
        public bool ShouldSerializePersona() => __pbn__Persona != null;
        public void ResetPersona() => __pbn__Persona = null;
        private string __pbn__Persona;

        [global::ProtoBuf.ProtoMember(6, Name = @"quantity")]
        public ulong Quantity
        {
            get => __pbn__Quantity.GetValueOrDefault();
            set => __pbn__Quantity = value;
        }
        public bool ShouldSerializeQuantity() => __pbn__Quantity != null;
        public void ResetQuantity() => __pbn__Quantity = null;
        private ulong? __pbn__Quantity;

        [global::ProtoBuf.ProtoMember(7, Name = @"follower_nucleusid")]
        public ulong FollowerNucleusid
        {
            get => __pbn__FollowerNucleusid.GetValueOrDefault();
            set => __pbn__FollowerNucleusid = value;
        }
        public bool ShouldSerializeFollowerNucleusid() => __pbn__FollowerNucleusid != null;
        public void ResetFollowerNucleusid() => __pbn__FollowerNucleusid = null;
        private ulong? __pbn__FollowerNucleusid;

        [global::ProtoBuf.ProtoMember(8, Name = @"follower_persona")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FollowerPersona
        {
            get => __pbn__FollowerPersona ?? "";
            set => __pbn__FollowerPersona = value;
        }
        public bool ShouldSerializeFollowerPersona() => __pbn__FollowerPersona != null;
        public void ResetFollowerPersona() => __pbn__FollowerPersona = null;
        private string __pbn__FollowerPersona;

        [global::ProtoBuf.ProtoMember(9, Name = @"followers_blob")]
        public SocialFollowersMessage FollowersBlob { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"is_maxis_curated")]
        public bool IsMaxisCurated
        {
            get => __pbn__IsMaxisCurated.GetValueOrDefault();
            set => __pbn__IsMaxisCurated = value;
        }
        public bool ShouldSerializeIsMaxisCurated() => __pbn__IsMaxisCurated != null;
        public void ResetIsMaxisCurated() => __pbn__IsMaxisCurated = null;
        private bool? __pbn__IsMaxisCurated;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFeedItemUnserializedMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"feed_id")]
        public byte[] FeedId
        {
            get => __pbn__FeedId;
            set => __pbn__FeedId = value;
        }
        public bool ShouldSerializeFeedId() => __pbn__FeedId != null;
        public void ResetFeedId() => __pbn__FeedId = null;
        private byte[] __pbn__FeedId;

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public byte[] Data
        {
            get => __pbn__Data;
            set => __pbn__Data = value;
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private byte[] __pbn__Data;

        [global::ProtoBuf.ProtoMember(3, Name = @"count_override")]
        public ulong CountOverride
        {
            get => __pbn__CountOverride.GetValueOrDefault();
            set => __pbn__CountOverride = value;
        }
        public bool ShouldSerializeCountOverride() => __pbn__CountOverride != null;
        public void ResetCountOverride() => __pbn__CountOverride = null;
        private ulong? __pbn__CountOverride;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialWallCommentMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public byte[] Uuid
        {
            get => __pbn__Uuid;
            set => __pbn__Uuid = value;
        }
        public bool ShouldSerializeUuid() => __pbn__Uuid != null;
        public void ResetUuid() => __pbn__Uuid = null;
        private byte[] __pbn__Uuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"author_id")]
        public ulong AuthorId
        {
            get => __pbn__AuthorId.GetValueOrDefault();
            set => __pbn__AuthorId = value;
        }
        public bool ShouldSerializeAuthorId() => __pbn__AuthorId != null;
        public void ResetAuthorId() => __pbn__AuthorId = null;
        private ulong? __pbn__AuthorId;

        [global::ProtoBuf.ProtoMember(3, Name = @"author_persona")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AuthorPersona
        {
            get => __pbn__AuthorPersona ?? "";
            set => __pbn__AuthorPersona = value;
        }
        public bool ShouldSerializeAuthorPersona() => __pbn__AuthorPersona != null;
        public void ResetAuthorPersona() => __pbn__AuthorPersona = null;
        private string __pbn__AuthorPersona;

        [global::ProtoBuf.ProtoMember(4, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message
        {
            get => __pbn__Message ?? "";
            set => __pbn__Message = value;
        }
        public bool ShouldSerializeMessage() => __pbn__Message != null;
        public void ResetMessage() => __pbn__Message = null;
        private string __pbn__Message;

        [global::ProtoBuf.ProtoMember(5, Name = @"created_timestamp")]
        public ulong CreatedTimestamp
        {
            get => __pbn__CreatedTimestamp.GetValueOrDefault();
            set => __pbn__CreatedTimestamp = value;
        }
        public bool ShouldSerializeCreatedTimestamp() => __pbn__CreatedTimestamp != null;
        public void ResetCreatedTimestamp() => __pbn__CreatedTimestamp = null;
        private ulong? __pbn__CreatedTimestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialGetWallCommentsMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(2, Name = @"gallery_id")]
        public byte[] GalleryId
        {
            get => __pbn__GalleryId;
            set => __pbn__GalleryId = value;
        }
        public bool ShouldSerializeGalleryId() => __pbn__GalleryId != null;
        public void ResetGalleryId() => __pbn__GalleryId = null;
        private byte[] __pbn__GalleryId;

        [global::ProtoBuf.ProtoMember(3, Name = @"starting_uuid")]
        public byte[] StartingUuid
        {
            get => __pbn__StartingUuid;
            set => __pbn__StartingUuid = value;
        }
        public bool ShouldSerializeStartingUuid() => __pbn__StartingUuid != null;
        public void ResetStartingUuid() => __pbn__StartingUuid = null;
        private byte[] __pbn__StartingUuid;

        [global::ProtoBuf.ProtoMember(4, Name = @"num_results")]
        public uint NumResults
        {
            get => __pbn__NumResults.GetValueOrDefault();
            set => __pbn__NumResults = value;
        }
        public bool ShouldSerializeNumResults() => __pbn__NumResults != null;
        public void ResetNumResults() => __pbn__NumResults = null;
        private uint? __pbn__NumResults;

        [global::ProtoBuf.ProtoMember(5, Name = @"messages")]
        public global::System.Collections.Generic.List<SocialWallCommentMessage> Messages { get; } = new global::System.Collections.Generic.List<SocialWallCommentMessage>();

        [global::ProtoBuf.ProtoMember(6, Name = @"hidden")]
        public bool Hidden
        {
            get => __pbn__Hidden.GetValueOrDefault();
            set => __pbn__Hidden = value;
        }
        public bool ShouldSerializeHidden() => __pbn__Hidden != null;
        public void ResetHidden() => __pbn__Hidden = null;
        private bool? __pbn__Hidden;

        [global::ProtoBuf.ProtoMember(7, Name = @"exclude_reported")]
        public bool ExcludeReported
        {
            get => __pbn__ExcludeReported.GetValueOrDefault();
            set => __pbn__ExcludeReported = value;
        }
        public bool ShouldSerializeExcludeReported() => __pbn__ExcludeReported != null;
        public void ResetExcludeReported() => __pbn__ExcludeReported = null;
        private bool? __pbn__ExcludeReported;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nextToken
        {
            get => __pbn__nextToken ?? "";
            set => __pbn__nextToken = value;
        }
        public bool ShouldSerializenextToken() => __pbn__nextToken != null;
        public void ResetnextToken() => __pbn__nextToken = null;
        private string __pbn__nextToken;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialPostWallCommentMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(2, Name = @"gallery_id")]
        public byte[] GalleryId
        {
            get => __pbn__GalleryId;
            set => __pbn__GalleryId = value;
        }
        public bool ShouldSerializeGalleryId() => __pbn__GalleryId != null;
        public void ResetGalleryId() => __pbn__GalleryId = null;
        private byte[] __pbn__GalleryId;

        [global::ProtoBuf.ProtoMember(3, Name = @"message")]
        public SocialWallCommentMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialDeleteWallCommentMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(2, Name = @"gallery_id")]
        public byte[] GalleryId
        {
            get => __pbn__GalleryId;
            set => __pbn__GalleryId = value;
        }
        public bool ShouldSerializeGalleryId() => __pbn__GalleryId != null;
        public void ResetGalleryId() => __pbn__GalleryId = null;
        private byte[] __pbn__GalleryId;

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        public byte[] Uuid
        {
            get => __pbn__Uuid;
            set => __pbn__Uuid = value;
        }
        public bool ShouldSerializeUuid() => __pbn__Uuid != null;
        public void ResetUuid() => __pbn__Uuid = null;
        private byte[] __pbn__Uuid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialRequestFeedWallMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ending_uuid")]
        public byte[] EndingUuid
        {
            get => __pbn__EndingUuid;
            set => __pbn__EndingUuid = value;
        }
        public bool ShouldSerializeEndingUuid() => __pbn__EndingUuid != null;
        public void ResetEndingUuid() => __pbn__EndingUuid = null;
        private byte[] __pbn__EndingUuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"messages")]
        public global::System.Collections.Generic.List<SocialFeedItemMessage> Messages { get; } = new global::System.Collections.Generic.List<SocialFeedItemMessage>();

        [global::ProtoBuf.ProtoMember(3, Name = @"unserialized_messages")]
        public global::System.Collections.Generic.List<SocialFeedItemUnserializedMessage> UnserializedMessages { get; } = new global::System.Collections.Generic.List<SocialFeedItemUnserializedMessage>();

        [global::ProtoBuf.ProtoMember(4, Name = @"num_items")]
        public uint NumItems
        {
            get => __pbn__NumItems.GetValueOrDefault();
            set => __pbn__NumItems = value;
        }
        public bool ShouldSerializeNumItems() => __pbn__NumItems != null;
        public void ResetNumItems() => __pbn__NumItems = null;
        private uint? __pbn__NumItems;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialRequestFollowersMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"playerid")]
        public ulong Playerid
        {
            get => __pbn__Playerid.GetValueOrDefault();
            set => __pbn__Playerid = value;
        }
        public bool ShouldSerializePlayerid() => __pbn__Playerid != null;
        public void ResetPlayerid() => __pbn__Playerid = null;
        private ulong? __pbn__Playerid;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id
        {
            get => __pbn__Id ?? "";
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private string __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"prev_last_persona")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PrevLastPersona
        {
            get => __pbn__PrevLastPersona ?? "";
            set => __pbn__PrevLastPersona = value;
        }
        public bool ShouldSerializePrevLastPersona() => __pbn__PrevLastPersona != null;
        public void ResetPrevLastPersona() => __pbn__PrevLastPersona = null;
        private string __pbn__PrevLastPersona;

        [global::ProtoBuf.ProtoMember(4, Name = @"num_request")]
        public uint NumRequest
        {
            get => __pbn__NumRequest.GetValueOrDefault();
            set => __pbn__NumRequest = value;
        }
        public bool ShouldSerializeNumRequest() => __pbn__NumRequest != null;
        public void ResetNumRequest() => __pbn__NumRequest = null;
        private uint? __pbn__NumRequest;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialRequestIgnoreListMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_nucleus_id")]
        public ulong PlayerNucleusId
        {
            get => __pbn__PlayerNucleusId.GetValueOrDefault();
            set => __pbn__PlayerNucleusId = value;
        }
        public bool ShouldSerializePlayerNucleusId() => __pbn__PlayerNucleusId != null;
        public void ResetPlayerNucleusId() => __pbn__PlayerNucleusId = null;
        private ulong? __pbn__PlayerNucleusId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialGetPlayerInfoListMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_nucleus_id")]
        public ulong PlayerNucleusId
        {
            get => __pbn__PlayerNucleusId.GetValueOrDefault();
            set => __pbn__PlayerNucleusId = value;
        }
        public bool ShouldSerializePlayerNucleusId() => __pbn__PlayerNucleusId != null;
        public void ResetPlayerNucleusId() => __pbn__PlayerNucleusId = null;
        private ulong? __pbn__PlayerNucleusId;

        [global::ProtoBuf.ProtoMember(2, Name = @"player_info_list")]
        public global::System.Collections.Generic.List<PlayerInfo> PlayerInfoLists { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayerInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"nucleus_id")]
            public ulong NucleusId
            {
                get => __pbn__NucleusId.GetValueOrDefault();
                set => __pbn__NucleusId = value;
            }
            public bool ShouldSerializeNucleusId() => __pbn__NucleusId != null;
            public void ResetNucleusId() => __pbn__NucleusId = null;
            private ulong? __pbn__NucleusId;

            [global::ProtoBuf.ProtoMember(2, Name = @"origin_persona")]
            [global::System.ComponentModel.DefaultValue("")]
            public string OriginPersona
            {
                get => __pbn__OriginPersona ?? "";
                set => __pbn__OriginPersona = value;
            }
            public bool ShouldSerializeOriginPersona() => __pbn__OriginPersona != null;
            public void ResetOriginPersona() => __pbn__OriginPersona = null;
            private string __pbn__OriginPersona;

            [global::ProtoBuf.ProtoMember(3, Name = @"first_party_persona")]
            [global::System.ComponentModel.DefaultValue("")]
            public string FirstPartyPersona
            {
                get => __pbn__FirstPartyPersona ?? "";
                set => __pbn__FirstPartyPersona = value;
            }
            public bool ShouldSerializeFirstPartyPersona() => __pbn__FirstPartyPersona != null;
            public void ResetFirstPartyPersona() => __pbn__FirstPartyPersona = null;
            private string __pbn__FirstPartyPersona;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialCommentPetitionMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(2, Name = @"commentid")]
        public byte[] Commentid
        {
            get => __pbn__Commentid;
            set => __pbn__Commentid = value;
        }
        public bool ShouldSerializeCommentid() => __pbn__Commentid != null;
        public void ResetCommentid() => __pbn__Commentid = null;
        private byte[] __pbn__Commentid;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string commentKey
        {
            get => __pbn__commentKey ?? "";
            set => __pbn__commentKey = value;
        }
        public bool ShouldSerializecommentKey() => __pbn__commentKey != null;
        public void ResetcommentKey() => __pbn__commentKey = null;
        private string __pbn__commentKey;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialBioPetitionMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nucleusid")]
        public ulong Nucleusid
        {
            get => __pbn__Nucleusid.GetValueOrDefault();
            set => __pbn__Nucleusid = value;
        }
        public bool ShouldSerializeNucleusid() => __pbn__Nucleusid != null;
        public void ResetNucleusid() => __pbn__Nucleusid = null;
        private ulong? __pbn__Nucleusid;

        [global::ProtoBuf.ProtoMember(2, Name = @"bio_nucleusid")]
        public ulong BioNucleusid
        {
            get => __pbn__BioNucleusid.GetValueOrDefault();
            set => __pbn__BioNucleusid = value;
        }
        public bool ShouldSerializeBioNucleusid() => __pbn__BioNucleusid != null;
        public void ResetBioNucleusid() => __pbn__BioNucleusid = null;
        private ulong? __pbn__BioNucleusid;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFeedRemovalMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"feed_id")]
        public byte[] FeedId
        {
            get => __pbn__FeedId;
            set => __pbn__FeedId = value;
        }
        public bool ShouldSerializeFeedId() => __pbn__FeedId != null;
        public void ResetFeedId() => __pbn__FeedId = null;
        private byte[] __pbn__FeedId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialControlMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opcode", IsRequired = true)]
        public SocialOpTypes Opcode { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"subop")]
        [global::System.ComponentModel.DefaultValue(SocialOpTypes.SopPublicMin)]
        public SocialOpTypes Subop
        {
            get => __pbn__Subop ?? SocialOpTypes.SopPublicMin;
            set => __pbn__Subop = value;
        }
        public bool ShouldSerializeSubop() => __pbn__Subop != null;
        public void ResetSubop() => __pbn__Subop = null;
        private SocialOpTypes? __pbn__Subop;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong transactionId
        {
            get => __pbn__transactionId.GetValueOrDefault();
            set => __pbn__transactionId = value;
        }
        public bool ShouldSerializetransactionId() => __pbn__transactionId != null;
        public void ResettransactionId() => __pbn__transactionId = null;
        private ulong? __pbn__transactionId;

        [global::ProtoBuf.ProtoMember(100, Name = @"result")]
        public uint Result
        {
            get => __pbn__Result.GetValueOrDefault();
            set => __pbn__Result = value;
        }
        public bool ShouldSerializeResult() => __pbn__Result != null;
        public void ResetResult() => __pbn__Result = null;
        private uint? __pbn__Result;

        [global::ProtoBuf.ProtoMember(4, Name = @"getwallcommentsmsg")]
        public SocialGetWallCommentsMessage Getwallcommentsmsg { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"postwallcommentmsg")]
        public SocialPostWallCommentMessage Postwallcommentmsg { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"deletewallcommentmsg")]
        public SocialDeleteWallCommentMessage Deletewallcommentmsg { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"friendmsg")]
        public SocialFriendMsg Friendmsg { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"genericresponse")]
        public SocialGenericResponse Genericresponse { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"playerinfo")]
        public SocialPlayerInfoList Playerinfo { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"feedsubmsg")]
        public SocialFeedSubMessage Feedsubmsg { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"searchresultmsg")]
        public SocialSearchMsg Searchresultmsg { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"inviteresponsemsg")]
        public SocialInviteResponseMessage Inviteresponsemsg { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"originerror")]
        public OriginErrorMessage Originerror { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"socialcassandratest")]
        public SocialCassandraTest Socialcassandratest { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"socialfriendlistrequestmsg")]
        public SocialFriendListRequestMessage Socialfriendlistrequestmsg { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"socialrequestnucleusidfrompersona")]
        public SocialRequestNucleusIdFromPersona Socialrequestnucleusidfrompersona { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"socialnucleusidfrompersonaresponse")]
        public SocialNucleusIdFromPersonaResponse Socialnucleusidfrompersonaresponse { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"socialexchangemessage")]
        public SocialExchangeMessage Socialexchangemessage { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"socialrequestfeedwallmessage")]
        public SocialRequestFeedWallMessage Socialrequestfeedwallmessage { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"stat_tickers")]
        public ExchangeStatTickerMessage StatTickers { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"comment_petition_msg")]
        public SocialCommentPetitionMessage CommentPetitionMsg { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"feedremovalmsg")]
        public SocialFeedRemovalMessage Feedremovalmsg { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"bio_petition_msg")]
        public SocialBioPetitionMessage BioPetitionMsg { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"fb_event_msg")]
        public SocialFacebookEventMessage FbEventMsg { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"requestfollowers_msg")]
        public SocialRequestFollowersMessage RequestfollowersMsg { get; set; }

        [global::ProtoBuf.ProtoMember(27, Name = @"responsefollowers_msg")]
        public SocialResponseFollowersMessage ResponsefollowersMsg { get; set; }

        [global::ProtoBuf.ProtoMember(28, Name = @"requestignorelist_msg")]
        public SocialRequestIgnoreListMessage RequestignorelistMsg { get; set; }

        [global::ProtoBuf.ProtoMember(29, Name = @"response_player_info_list_msg")]
        public SocialGetPlayerInfoListMessage ResponsePlayerInfoListMsg { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"player_identification_list_msg")]
        public ServerPlayerIdentificationListMessage PlayerIdentificationListMsg { get; set; }

        [global::ProtoBuf.ProtoMember(31, Name = @"candidate_msg")]
        public SocialCandidatesMessage CandidateMsg { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"evaluation_results_msg")]
        public SocialEvaluationResultsMessage EvaluationResultsMsg { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"cg_update_msg")]
        public SocialCGUpdateMessage CgUpdateMsg { get; set; }

        [global::ProtoBuf.ProtoMember(34, Name = @"ugc_share_msg")]
        public UGCShare UgcShareMsg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialInvalidateMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cache_index")]
        public uint CacheIndex
        {
            get => __pbn__CacheIndex.GetValueOrDefault();
            set => __pbn__CacheIndex = value;
        }
        public bool ShouldSerializeCacheIndex() => __pbn__CacheIndex != null;
        public void ResetCacheIndex() => __pbn__CacheIndex = null;
        private uint? __pbn__CacheIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        public byte[] Key
        {
            get => __pbn__Key;
            set => __pbn__Key = value;
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private byte[] __pbn__Key;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialControlQueueBroadcastMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"control")]
        public SocialControlMessage Control { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] friendIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LifeEventMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public uint Type
        {
            get => __pbn__Type.GetValueOrDefault();
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private uint? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_ids", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] SimIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialFacebookEventMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string objectId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string accessToken { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"guid", IsRequired = true)]
        public string Guid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialCandidateStatisticSubmessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"remote_id")]
        public byte[] RemoteId
        {
            get => __pbn__RemoteId;
            set => __pbn__RemoteId = value;
        }
        public bool ShouldSerializeRemoteId() => __pbn__RemoteId != null;
        public void ResetRemoteId() => __pbn__RemoteId = null;
        private byte[] __pbn__RemoteId;

        [global::ProtoBuf.ProtoMember(2, Name = @"views_count")]
        public uint ViewsCount
        {
            get => __pbn__ViewsCount.GetValueOrDefault();
            set => __pbn__ViewsCount = value;
        }
        public bool ShouldSerializeViewsCount() => __pbn__ViewsCount != null;
        public void ResetViewsCount() => __pbn__ViewsCount = null;
        private uint? __pbn__ViewsCount;

        [global::ProtoBuf.ProtoMember(3, Name = @"wins_count")]
        public uint WinsCount
        {
            get => __pbn__WinsCount.GetValueOrDefault();
            set => __pbn__WinsCount = value;
        }
        public bool ShouldSerializeWinsCount() => __pbn__WinsCount != null;
        public void ResetWinsCount() => __pbn__WinsCount = null;
        private uint? __pbn__WinsCount;

        [global::ProtoBuf.ProtoMember(4, Name = @"platform")]
        public uint Platform
        {
            get => __pbn__Platform.GetValueOrDefault();
            set => __pbn__Platform = value;
        }
        public bool ShouldSerializePlatform() => __pbn__Platform != null;
        public void ResetPlatform() => __pbn__Platform = null;
        private uint? __pbn__Platform;

        [global::ProtoBuf.ProtoMember(5, Name = @"category")]
        public uint Category
        {
            get => __pbn__Category.GetValueOrDefault();
            set => __pbn__Category = value;
        }
        public bool ShouldSerializeCategory() => __pbn__Category != null;
        public void ResetCategory() => __pbn__Category = null;
        private uint? __pbn__Category;

        [global::ProtoBuf.ProtoMember(6, Name = @"was_reported")]
        public bool WasReported
        {
            get => __pbn__WasReported.GetValueOrDefault();
            set => __pbn__WasReported = value;
        }
        public bool ShouldSerializeWasReported() => __pbn__WasReported != null;
        public void ResetWasReported() => __pbn__WasReported = null;
        private bool? __pbn__WasReported;

        [global::ProtoBuf.ProtoMember(7, Name = @"expires_epoch_sec")]
        public ulong ExpiresEpochSec
        {
            get => __pbn__ExpiresEpochSec.GetValueOrDefault();
            set => __pbn__ExpiresEpochSec = value;
        }
        public bool ShouldSerializeExpiresEpochSec() => __pbn__ExpiresEpochSec != null;
        public void ResetExpiresEpochSec() => __pbn__ExpiresEpochSec = null;
        private ulong? __pbn__ExpiresEpochSec;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialCandidatesMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

        [global::ProtoBuf.ProtoMember(2, Name = @"platform_restriction")]
        public uint PlatformRestriction
        {
            get => __pbn__PlatformRestriction.GetValueOrDefault();
            set => __pbn__PlatformRestriction = value;
        }
        public bool ShouldSerializePlatformRestriction() => __pbn__PlatformRestriction != null;
        public void ResetPlatformRestriction() => __pbn__PlatformRestriction = null;
        private uint? __pbn__PlatformRestriction;

        [global::ProtoBuf.ProtoMember(3, Name = @"category_restriction")]
        public uint CategoryRestriction
        {
            get => __pbn__CategoryRestriction.GetValueOrDefault();
            set => __pbn__CategoryRestriction = value;
        }
        public bool ShouldSerializeCategoryRestriction() => __pbn__CategoryRestriction != null;
        public void ResetCategoryRestriction() => __pbn__CategoryRestriction = null;
        private uint? __pbn__CategoryRestriction;

        [global::ProtoBuf.ProtoMember(4, Name = @"challenge")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Challenge
        {
            get => __pbn__Challenge ?? "";
            set => __pbn__Challenge = value;
        }
        public bool ShouldSerializeChallenge() => __pbn__Challenge != null;
        public void ResetChallenge() => __pbn__Challenge = null;
        private string __pbn__Challenge;

        [global::ProtoBuf.ProtoMember(5, Name = @"digest")]
        public byte[] Digest
        {
            get => __pbn__Digest;
            set => __pbn__Digest = value;
        }
        public bool ShouldSerializeDigest() => __pbn__Digest != null;
        public void ResetDigest() => __pbn__Digest = null;
        private byte[] __pbn__Digest;

        [global::ProtoBuf.ProtoMember(6, Name = @"candidates")]
        public global::System.Collections.Generic.List<SocialCandidateStatisticSubmessage> Candidates { get; } = new global::System.Collections.Generic.List<SocialCandidateStatisticSubmessage>();

        [global::ProtoBuf.ProtoMember(7, Name = @"expire_epoch_secs")]
        public ulong ExpireEpochSecs
        {
            get => __pbn__ExpireEpochSecs.GetValueOrDefault();
            set => __pbn__ExpireEpochSecs = value;
        }
        public bool ShouldSerializeExpireEpochSecs() => __pbn__ExpireEpochSecs != null;
        public void ResetExpireEpochSecs() => __pbn__ExpireEpochSecs = null;
        private ulong? __pbn__ExpireEpochSecs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialEvaluationResultsMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"winner_ids")]
        public global::System.Collections.Generic.List<string> WinnerIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, Name = @"loser_ids")]
        public global::System.Collections.Generic.List<string> LoserIds { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"digest")]
        public byte[] Digest
        {
            get => __pbn__Digest;
            set => __pbn__Digest = value;
        }
        public bool ShouldSerializeDigest() => __pbn__Digest != null;
        public void ResetDigest() => __pbn__Digest = null;
        private byte[] __pbn__Digest;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialCGDigestMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"challenge")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Challenge
        {
            get => __pbn__Challenge ?? "";
            set => __pbn__Challenge = value;
        }
        public bool ShouldSerializeChallenge() => __pbn__Challenge != null;
        public void ResetChallenge() => __pbn__Challenge = null;
        private string __pbn__Challenge;

        [global::ProtoBuf.ProtoMember(2, Name = @"candidates")]
        public global::System.Collections.Generic.List<SocialCandidateStatisticSubmessage> Candidates { get; } = new global::System.Collections.Generic.List<SocialCandidateStatisticSubmessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SocialFeedItemType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_ITEM_DOWNLOADED")]
        SfiItemDownloaded = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_ITEM_UPLOADED")]
        SfiItemUploaded = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_ITEM_FAVORITED")]
        SfiItemFavorited = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_ITEM_COMMENTED")]
        SfiItemCommented = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_ITEM_SHOWCASED")]
        SfiItemShowcased = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_PROFILE_COMMENTED")]
        SfiProfileCommented = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"SFI_NEW_FOLLOWERS")]
        SfiNewFollowers = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SocialClusterMessageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_LOGIN")]
        SocLogin = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_LOGOFF")]
        SocLogoff = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_PRESENCEUPDATE")]
        SocPresenceupdate = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_FEEDUPDATE")]
        SocFeedupdate = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_ADD_FEEDSUB")]
        SocAddFeedsub = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_REMOVE_FEEDSUB")]
        SocRemoveFeedsub = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_BROADCAST_PRIVOP")]
        SocBroadcastPrivop = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_BROADCAST_QUEUED")]
        SocBroadcastQueued = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_BROADCAST_CACHE_INVALIDATE")]
        SocBroadcastCacheInvalidate = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"SOC_REST_USER_REGISTER")]
        SocRestUserRegister = 10,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
