// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: WeatherSeasons.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SeasonWeatherInterpolationMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message_type", IsRequired = true)]
        public SeasonWeatherInterpolatedType MessageType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"start_value", IsRequired = true)]
        public float StartValue { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"start_time", IsRequired = true)]
        public ulong StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"end_value", IsRequired = true)]
        public float EndValue { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"end_time", IsRequired = true)]
        public ulong EndTime { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum SeasonWeatherInterpolatedType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SEASON")]
            Season = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"LEAF_ACCUMULATION")]
            LeafAccumulation = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FLOWER_GROWTH")]
            FlowerGrowth = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"FOLIAGE_REDUCTION")]
            FoliageReduction = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"FOLIAGE_COLORSHIFT")]
            FoliageColorshift = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"RAINFALL")]
            Rainfall = 1000,
            [global::ProtoBuf.ProtoEnum(Name = @"SNOWFALL")]
            Snowfall = 1001,
            [global::ProtoBuf.ProtoEnum(Name = @"RAIN_ACCUMULATION")]
            RainAccumulation = 1002,
            [global::ProtoBuf.ProtoEnum(Name = @"SNOW_ACCUMULATION")]
            SnowAccumulation = 1003,
            [global::ProtoBuf.ProtoEnum(Name = @"WINDOW_FROST")]
            WindowFrost = 1004,
            [global::ProtoBuf.ProtoEnum(Name = @"WATER_FROZEN")]
            WaterFrozen = 1005,
            [global::ProtoBuf.ProtoEnum(Name = @"WIND")]
            Wind = 1006,
            [global::ProtoBuf.ProtoEnum(Name = @"TEMPERATURE")]
            Temperature = 1007,
            [global::ProtoBuf.ProtoEnum(Name = @"THUNDER")]
            Thunder = 1008,
            [global::ProtoBuf.ProtoEnum(Name = @"LIGHTNING")]
            Lightning = 1009,
            [global::ProtoBuf.ProtoEnum(Name = @"SNOW_FRESHNESS")]
            SnowFreshness = 1010,
            [global::ProtoBuf.ProtoEnum(Name = @"STORY_ACT")]
            StoryAct = 1011,
            [global::ProtoBuf.ProtoEnum(Name = @"ECO_FOOTPRINT")]
            EcoFootprint = 1012,
            [global::ProtoBuf.ProtoEnum(Name = @"ACID_RAIN")]
            AcidRain = 1013,
            [global::ProtoBuf.ProtoEnum(Name = @"STARWARS_RESISTANCE")]
            StarwarsResistance = 1014,
            [global::ProtoBuf.ProtoEnum(Name = @"STARWARS_FIRST_ORDER")]
            StarwarsFirstOrder = 1015,
            [global::ProtoBuf.ProtoEnum(Name = @"SNOW_ICINESS")]
            SnowIciness = 1016,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_PARTLY_CLOUDY")]
            SkyboxPartlyCloudy = 2000,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_CLEAR")]
            SkyboxClear = 2001,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_LIGHTRAINCLOUDS")]
            SkyboxLightrainclouds = 2002,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_DARKRAINCLOUDS")]
            SkyboxDarkrainclouds = 2003,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_LIGHTSNOWCLOUDS")]
            SkyboxLightsnowclouds = 2004,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_DARKSNOWCLOUDS")]
            SkyboxDarksnowclouds = 2005,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_CLOUDY")]
            SkyboxCloudy = 2006,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_HEATWAVE")]
            SkyboxHeatwave = 2007,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_STRANGE")]
            SkyboxStrange = 2008,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_VERYSTRANGE")]
            SkyboxVerystrange = 2009,
            [global::ProtoBuf.ProtoEnum(Name = @"SKYBOX_INDUSTRIAL")]
            SkyboxIndustrial = 2010,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SeasonWeatherInterpolations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"season_weather_interlops")]
        public global::System.Collections.Generic.List<SeasonWeatherInterpolationMessage> SeasonWeatherInterlops { get; } = new global::System.Collections.Generic.List<SeasonWeatherInterpolationMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionWeather : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"region", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong Region { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"weather", IsRequired = true)]
        public SeasonWeatherInterpolations Weather { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"weather_event", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong WeatherEvent { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"forecast_time_stamp", IsRequired = true)]
        public ulong ForecastTimeStamp { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"next_weather_event_time", IsRequired = true)]
        public ulong NextWeatherEventTime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"forecasts")]
        public ulong[] Forecasts { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"override_forecast")]
        public ulong OverrideForecast
        {
            get => __pbn__OverrideForecast.GetValueOrDefault();
            set => __pbn__OverrideForecast = value;
        }
        public bool ShouldSerializeOverrideForecast() => __pbn__OverrideForecast != null;
        public void ResetOverrideForecast() => __pbn__OverrideForecast = null;
        private ulong? __pbn__OverrideForecast;

        [global::ProtoBuf.ProtoMember(8, Name = @"override_forecast_season_stamp")]
        public ulong OverrideForecastSeasonStamp
        {
            get => __pbn__OverrideForecastSeasonStamp.GetValueOrDefault();
            set => __pbn__OverrideForecastSeasonStamp = value;
        }
        public bool ShouldSerializeOverrideForecastSeasonStamp() => __pbn__OverrideForecastSeasonStamp != null;
        public void ResetOverrideForecastSeasonStamp() => __pbn__OverrideForecastSeasonStamp = null;
        private ulong? __pbn__OverrideForecastSeasonStamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PersistableWeatherService : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"region_weathers")]
        public global::System.Collections.Generic.List<RegionWeather> RegionWeathers { get; } = new global::System.Collections.Generic.List<RegionWeather>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UiWeatherUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"weather_type_enums")]
        public long[] WeatherTypeEnums { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UiWeatherForecastUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"forecast_instance_ids")]
        public ulong[] ForecastInstanceIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoonPhaseUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"current_moon_phase", IsRequired = true)]
        public MoonPhase CurrentMoonPhase { get; set; } = MoonPhase.DefaultNoMoon;

        [global::ProtoBuf.ProtoMember(2, Name = @"skip_environment_changes")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool SkipEnvironmentChanges
        {
            get => __pbn__SkipEnvironmentChanges ?? true;
            set => __pbn__SkipEnvironmentChanges = value;
        }
        public bool ShouldSerializeSkipEnvironmentChanges() => __pbn__SkipEnvironmentChanges != null;
        public void ResetSkipEnvironmentChanges() => __pbn__SkipEnvironmentChanges = null;
        private bool? __pbn__SkipEnvironmentChanges;

        [global::ProtoBuf.ProtoContract()]
        public enum MoonPhase
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DEFAULT_NO_MOON")]
            DefaultNoMoon = -1,
            [global::ProtoBuf.ProtoEnum(Name = @"NEW_MOON")]
            NewMoon = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"WAXING_CRESCENT")]
            WaxingCrescent = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FIRST_QUARTER")]
            FirstQuarter = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"WAXING_GIBBOUS")]
            WaxingGibbous = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"FULL_MOON")]
            FullMoon = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"WANING_GIBBOUS")]
            WaningGibbous = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"THIRD_QUARTER")]
            ThirdQuarter = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"WANING_CRESCENT")]
            WaningCrescent = 7,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UiLunarEffectTooltipUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"current_moon_phase", IsRequired = true)]
        public uint CurrentMoonPhase { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tooltip_text")]
        public LocalizedString TooltipText { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoonForecastUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"forecast_moon_phases")]
        public global::System.Collections.Generic.List<MoonPhase> ForecastMoonPhases { get; } = new global::System.Collections.Generic.List<MoonPhase>();

        [global::ProtoBuf.ProtoContract()]
        public enum MoonPhase
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DEFAULT_NO_MOON")]
            DefaultNoMoon = -1,
            [global::ProtoBuf.ProtoEnum(Name = @"NEW_MOON")]
            NewMoon = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"WAXING_CRESCENT")]
            WaxingCrescent = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FIRST_QUARTER")]
            FirstQuarter = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"WAXING_GIBBOUS")]
            WaxingGibbous = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"FULL_MOON")]
            FullMoon = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"WANING_GIBBOUS")]
            WaningGibbous = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"THIRD_QUARTER")]
            ThirdQuarter = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"WANING_CRESCENT")]
            WaningCrescent = 7,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
